## Reading

```{r include = FALSE}
answers <- yaml::yaml.load_file("../answers.yml")$rq5
```

### Reference {-}

[
Hayes, A. F. (2009). Beyond Baron and Kenny: Statistical mediation analysis in 
the new millennium. *Communication Monographs, 76*(4), 408--420.
](https://www.researchgate.net/profile/Gulnaz_Anjum2/post/Is_it_still_mediation_if_there_is_no_relationship_between_the_IV_DV/attachment/5e8c3227f155db0001f34b05/AS%3A877594253721600%401586246183233/download/2009-Hayes-BeyondBaronandKennyStatisticalmediationanalysisinthenewmillennium.pdf)

### Questions {-}

1. What is an indirect or mediated effect? 
1. What is the difference between the total and direct effect?
1. What is the main problem with the Barron & Kenny "Causal Steps Approach"?
1. What is bootstrapping, and why is it a better way to test mediation than 
Sobel's test?
1. Explain how it is possible that "effects that don't exist can be mediated".

```{asis echo = answers}
### Answers {-}

1. The indirect effect (IE) is the part of the effect of X on Y that is 
transmitted through M. We compute the IE by multiplying the effect of X on M (a) 
and the effect of M on Y (b): $IE = ab$.
1. The total effect is the effect of X on Y without accounting for M. The direct 
effect is the effect of X on Y after controlling for M.
1. The B&K approach infers mediation based on a sequence of significance tests, 
and this repeated testing lowers power. Moreover, if no significant total effect 
is found between X and Y, researchers apply the B&K logic must infer the absence 
of any indirect effect, but a nonsignificant total effect does not imply a lack 
of mediation.
1. Bootstrapping constructs an empirical sampling distribution for a parameter 
by resampling rows from the original data many (e.g., 1000) times, and conducting 
the same analysis on each of these samples. The distribution of these parameter 
estimates represents an empirical sampling distribution for the parameter. This 
sampling distribution is then used to support inference (e.g., by deriving 
confidence intervals or standard errors). Sobel's test assumes the IE is normally 
distributed, which cannot be true in finite samples. Bootstrapping is a 
nonparametric technique that directly estimates the sampling distribution of the
IE rather than assuming some parametric form.
1. The following passage from the reading (p. 414) explains: 

> That X can exert an indirect effect on Y through M in the absence of an 
> association between X and Y becomes explicable once you consider that a total 
> effect is the sum of many different paths of influence, direct and indirect, 
> not all of which may be a part of the formal model. For example, it could be 
> that two or more indirect paths carry the effect from X through Y, and those 
> paths operate in opposite directions (cf., MacKinnon, Krull, & Lockwood, 2000). 
> Much as a main effect in 2\$times$2 ANOVA might be nonsignificant if the 
> simple effects are opposite in sign (i.e., a crossover interaction), two or 
> more indirect effects with opposite signs can cancel each other out, producing 
> a total effect and perhaps even a total indirect effect that is not detectably 
> different from zero, in spite of the existence of specific indirect effects 
> that are not zero.
```

---

### Reference {-}

[
Holbert, R. L., & Stephenson, M. T. (2003). The importance of indirect effects 
in media effects research: Testing for mediation in structural equation modeling. 
*Journal of Broadcasting & Electronic Media, 47*, 556--572.
](http://www.academia.edu/download/30909266/JOBEM.pdf)


### Questions {-}

1. On p. 560 the four steps for complex mediation are discussed. The first three 
steps are for partial mediation. What is the difference between these two forms 
of mediation? 
1. What is the advantage of the *Product of Coefficients* approach (p. 561--562) 
in comparison to the *Causal Steps* approach (p. 560--561) and the *Difference 
in Coefficients* approach (p. 561)? 
1. How does the *Product of Coefficients* approach work, and why is it problematic? 
1. How many effects are there from Debate Viewing on Political Participation? 
Which effects can you easily obtain from SEM software?


```{asis, echo = answers}
### Answers {-}

1. Four steps are given:  
    a. X should predict Y  
    b. M should be correlated with X
    c. M should predict Y
    d. X is no longer a significant predictor of Y once M is included

    Partial mediation $\Rightarrow$ there is still a significant direct effect 
    of X on Y, after controlling for the mediator.  
    
    Full mediation $\Rightarrow$ The entire effect of X on Y is transmitted 
    through M, so the direct effect is nonsignificant after controlling for the 
    mediator.

1. The Product of Coefficients approach produces an actual statistical test with 
a corresponding p-value.
1. Define the indirect effect by the product of paths, and divide this estiamte
by the Sobel's standard error.
    - The IE is defined by the product of two normally distributed paths, so it 
    cannot be normally distributed. Hence the p-values for the test are derived 
    from an incorrect sampling distribution.
1. 1 direct effect and 2 indirect effects.  
    - We can use SEM/path modeling to estimate the direct effect, the total 
    effect, each individual indirect effect, and the total indirect effect.
```
