# Assignments {#assignments} {-}

1. Apply the “latent variable model” to a real-life problem, where observed variables do not directly measure, but are indicators of, an unobserved social scientific construct (G, 25%)
    a. Find a suitable dataset, for example: (no word limit)
        i.	Data you have collected for a previous course
        ii.	Open data, provided with a published paper
        iii.	The “Coping with COVID-19” dataset (if you can’t find anything)
    b.	Describe the dataset, and introduce the theoretical latent variable model (200 words)
    c.	Estimate the latent variable model (PCA, EFA, CFA) and conduct reliability analysis, provide relevant output in a suitable format (no word limit; as short as possible and as long as necessary to report the relevant output)
    d.	Explain your rationale for important modeling decisions (300 words)
        i.	Motivate your choice for the type of latent variable model
        ii.	Discuss assumptions
        iii.	Discuss other important decisions, as discussed in the course reading materials
    e.	Report and interpret the results in APA style  (no word limit; as short as possible and as long as necessary to report the relevant results)
    f.	Discuss the results in max 300 words
        i.	Devote attention to strengths and limitations
2. Use the “path model” to describe how several variables are causally related to one another (G, 25%)
    a.	Find a suitable dataset, for example: (no word limit)
        i.	Data you have collected and analyzed for a previous course
        ii.	Open data, provided with a published paper
        iii.	The “Coping with COVID-19” dataset (if you can’t find anything)
    b.	Describe the dataset, and introduce the theoretical path model (200 words)
    c.	Conduct a SEM path model to answer the theoretical questions  (no word limit; as short as possible and as long as necessary to report the relevant output)
        i. 	This can be a re-analysis of a question that had been tested using regression, ANOVA, or t-test analysis in the original paper
    d.	Explain your rationale for important modeling decisions (300 words)
        i.	Fit between theory and model
        ii.	Model assumptions
        iii.	Difference/similarity between the path model and the (original) regression, ANOVA, or t-test analysis
        iv.	Why you use standardized or unstandardized coefficients
    e.	Report and interpret the results in APA style  (no word limit; as short as possible and as long as necessary to report the relevant results)
        i. 	Include measures of explained variance for the dependent variables.
    f.	Discuss the results (max 300 words)
        i.	Devote attention to strengths and limitations
3. Independently analyze data using the free, open-source statistical software R (I, 50%) 
    a.	Find a suitable dataset, for example: (no word limit)
        i.	Data you have collected for a previous course
        ii.	Open data, provided with a published paper
        iii.	The “Coping with COVID-19” dataset (if you can’t find anything)
    b.	Describe the dataset, and introduce a theory involving at least 3 variables that can be tested using these data (300 words)
    c.	Translate the theory to lavaan syntax and estimate the model (could be multiple models if you think it’s necessary; no word limit)
    d.	Use at least all of the following: (no word limit)
        i.	One latent variable
        ii.	Moderation (continuous or multi-group)
        iii.	Mediation
    e. 	Explain your rationale for important modeling decisions (300 words)
        i.	Fit between theory and model
        ii.	Model assumptions
        iii.	Difference/similarity between the path model and the (original) regression, ANOVA, or t-test analysis
        iv.	Why you use standardized or unstandardized coefficients
    f.	Report and interpret your results in APA style  (no word limit; as short as possible and as long as necessary to report the relevant results)
    g.	Discuss your results in maximum 500 words

## Grading

For each assignment, every element labeled with a lower case letter is graded fail (0 points), pass (1 point), or excellent (1.5 points).
Grades are summed for each assignment, and rescaled from 1-10.
The final grade is a weighted average across assignments of the rescaled grades (weights in %).
Note that the assignments are **not** intended to be full-blown papers!
You only get 200 words to justify your theoretical model, and 300 words to discuss the results.
The focus should be on your analysis; how it relates to theory (introduction), and what you have learned from it and how you might improve it (discussion).

## Rules

- For all three graded assignments, you are allowed to use all course materials, 
including the GitBook, and search engines
- The first two assignments are made in groups.
   - For these assignments, it is not allowed to work together with other groups.
- The final assignment is made individually. 
   - For this assignment, it is not allowed to recruit outside help
- In all cases, you are obligated to hand in original work conducted by you or your group. Failure to do so constitutes fraud.
- You also have a moral obligation to obey the rules. For this course, I have chosen a form of examination that allows you to showcase what you have learned flexibly. This spares you the stress of long exams (the two exams for this course used to be 4 hours each) and cramming all course material. It also assumes that you make the assignment in good faith, so I simply ask that you hold up your end of the bargain, and hand in your original work to show what you’ve learned.
- The final assignment also helps you assess your ability to independently analyse data, which is important to know for your future courses and/or career.

### Academic misconduct

You will be completing this assignment remotely, instead of making a test at the university under the supervision of lecturers. For most students this will make no difference, but of course remote assessment is more susceptible to fraud. 
By handing in your final assignment, you therefore explicitly confirm that you have made this assignment by yourself and are submitting work you have written yourself, that you will be using your own login details, and that you have not had instrumental help in making the assignment.

All assignments are submitted via SafeAssign in Blackboard and are checked for plagiarism. If fraud or plagiarism is detected or suspected, the Board of Examiners will be informed in the usual manner, and in the event of fraud, the sanctions referred to in Article 5.14 of the Education and Examination Regulations (EER) will apply (download from https://students.uu.nl/files/fsw-ba-oer-engelstalig-2019-2020pdf). Note that the sanctions may apply to the person committing fraud, to the person(s) making fraud possible, and to the test as a whole.  
Lecturers also have the option of administering additional oral tests if they have reasons to do so.
Thank you for your cooperation, we will only be able to get through this period together!
