--- 
title: "Theory Construction and Statistical Modeling"
#subtitle: "A guide to structural equation modeling in R"
author: "Kyle M. Lang"
date: "Last updated: `r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config: 
      toc:
       collapse: section
#      search: yes
#      fontsettings:
#        size: 2
    split_by: section
    df_print: paged
documentclass: book
#bibliography: [../bibtex/book.bib, ../bibtex/packages.bib]
#biblio-style: apalike
#link-citations: yes
#description: "This is a guide for the elective course TCSM."
---

```{r global_options, include = FALSE}
library(knitr)
library(dplyr)

opts_chunk$set(warning = FALSE, message = FALSE)

dataDir  <- "../../data/"
```

<!------------------------------------------------------------------------------
```{r week_chapters, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
#knit_child("course_info.Rmd", quiet = TRUE) %>% cat(sep = "\n")
#knit_child("week0.Rmd", quiet = TRUE) %>% cat(sep = "\n")
#knit_child("week1.Rmd", quiet = TRUE) %>% cat(sep = "\n")
#knit_child("week2.Rmd", quiet = TRUE) %>% cat(sep = "\n")
```
------------------------------------------------------------------------------->