## Lecture

```{r, echo = FALSE}
knitr::include_url("https://www.youtube.com/embed/xg84x9BVHAI")
```

[Download slides](pdf/tcsm_week_5.pdf)

**Note that these are more recent versions of the slides than used in the video.**

Researchers often have theories about possible causal processes linking multiple
variables. Mediation is a particularly important example of such a process in 
which in an input variable, X, influences the outcome, Y, through an intermediary
variable, M (the mediator). For instance, psychotherapy (X), may affect thoughts 
(M), which in turn affects mood (Y). 

We can investigate mediation via a specific sequence of linear regression 
equations, but path modeling will make our lives much easier. We can use path 
models to simultaneously estimate multiple related regression equations. So, 
mediation analysis is an ideal application of path modeling. In this lecture, we 
consider both approaches and discuss their relative strengths and weaknesses.
