<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.3 At-Home Exercises | Theory Construction and Statistical Modeling</title>
  <meta name="description" content="7.3 At-Home Exercises | Theory Construction and Statistical Modeling" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="7.3 At-Home Exercises | Theory Construction and Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.3 At-Home Exercises | Theory Construction and Statistical Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reading-6.html"/>
<link rel="next" href="in-class-exercises-6.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">TCSM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reading-questions.html"><a href="reading-questions.html"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html"><i class="fa fa-check"></i>Weekly preparation</a>
<ul>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a></li>
<li class="chapter" data-level="" data-path="attendance.html"><a href="attendance.html"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html#submission"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html"><i class="fa fa-check"></i>Assignment 2: Confirmatory Factor Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html#evaluation-1"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html#submission-1"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html"><i class="fa fa-check"></i>Assignment 3: Full Structural Equation Model</a>
<ul>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#evaluation-2"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#results_format"><i class="fa fa-check"></i>Results</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html"><i class="fa fa-check"></i>Data</a>
<ul>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#coping-with-covid"><i class="fa fa-check"></i>Coping with Covid</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#feminist-perspectives-scale"><i class="fa fa-check"></i>Feminist Perspectives Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#hypersensitive-narcissism-scale-dirty-dozen"><i class="fa fa-check"></i>Hypersensitive Narcissism Scale &amp; Dirty Dozen</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#kentucky-inventory-of-mindfulness-skills"><i class="fa fa-check"></i>Kentucky Inventory of Mindfulness Skills</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#depression-anxiety-stress-scale"><i class="fa fa-check"></i>Depression Anxiety Stress Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#nomophobia"><i class="fa fa-check"></i>Nomophobia</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#recylced-water-acceptance"><i class="fa fa-check"></i>Recylced Water Acceptance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-3"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#group-assignments"><i class="fa fa-check"></i>Group Assignments</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#individual-assignment"><i class="fa fa-check"></i>Individual Assignment</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#resits"><i class="fa fa-check"></i>Resits</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#example-assignment"><i class="fa fa-check"></i>Example Assignment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html"><i class="fa fa-check"></i>Rules</a>
<ul>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#academic-integrity"><i class="fa fa-check"></i>Academic integrity</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#strict-stuff"><i class="fa fa-check"></i>Strict stuff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.1</b> </a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.1</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.2</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.3</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.1</b> Mediation</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.2</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.1</b> Mediation</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.2</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="efa.html"><a href="efa.html"><i class="fa fa-check"></i><b>4</b> EFA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recording"><i class="fa fa-check"></i><b>4.1.1</b> Recording</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-1-1"><i class="fa fa-check"></i>Reference 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-1-1"><i class="fa fa-check"></i>Questions 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-2-1"><i class="fa fa-check"></i>Reference 2</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-2-1"><i class="fa fa-check"></i>Questions 2</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-44"><i class="fa fa-check"></i><b>4.3.1</b> </a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#run_pca"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#pcScores"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#trust_efa"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaAtt"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#factorScores"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
<li class="chapter" data-level="4.4.13" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.13</b> </a></li>
<li class="chapter" data-level="4.4.14" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-64"><i class="fa fa-check"></i><b>4.4.14</b> </a></li>
<li class="chapter" data-level="4.4.15" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-65"><i class="fa fa-check"></i><b>4.4.15</b> </a></li>
<li class="chapter" data-level="4.4.16" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaRegression"><i class="fa fa-check"></i><b>4.4.16</b> </a></li>
<li class="chapter" data-level="4.4.17" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-66"><i class="fa fa-check"></i><b>4.4.17</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa.html"><a href="cfa.html"><i class="fa fa-check"></i><b>5</b> CFA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lecture-4.html"><a href="lecture-4.html#recording-1"><i class="fa fa-check"></i><b>5.1.1</b> Recording</a></li>
<li class="chapter" data-level="5.1.2" data-path="lecture-4.html"><a href="lecture-4.html#slides-4"><i class="fa fa-check"></i><b>5.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-67"><i class="fa fa-check"></i><b>5.3.1</b> </a></li>
<li class="chapter" data-level="5.3.2" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#cfaSyntax"><i class="fa fa-check"></i><b>5.3.2</b> </a></li>
<li class="chapter" data-level="5.3.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-68"><i class="fa fa-check"></i><b>5.3.3</b> </a></li>
<li class="chapter" data-level="5.3.4" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-69"><i class="fa fa-check"></i><b>5.3.4</b> </a></li>
<li class="chapter" data-level="5.3.5" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-70"><i class="fa fa-check"></i><b>5.3.5</b> </a></li>
<li class="chapter" data-level="5.3.6" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-71"><i class="fa fa-check"></i><b>5.3.6</b> </a></li>
<li class="chapter" data-level="5.3.7" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-72"><i class="fa fa-check"></i><b>5.3.7</b> </a></li>
<li class="chapter" data-level="5.3.8" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-73"><i class="fa fa-check"></i><b>5.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-74"><i class="fa fa-check"></i><b>5.4.1</b> </a></li>
<li class="chapter" data-level="5.4.2" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt"><i class="fa fa-check"></i><b>5.4.2</b> </a></li>
<li class="chapter" data-level="5.4.3" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-75"><i class="fa fa-check"></i><b>5.4.3</b> </a></li>
<li class="chapter" data-level="5.4.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt1f"><i class="fa fa-check"></i><b>5.4.4</b> </a></li>
<li class="chapter" data-level="5.4.5" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#compare1f5f"><i class="fa fa-check"></i><b>5.4.5</b> </a></li>
<li class="chapter" data-level="5.4.6" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-76"><i class="fa fa-check"></i><b>5.4.6</b> </a></li>
<li class="chapter" data-level="5.4.7" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfa2nd"><i class="fa fa-check"></i><b>5.4.7</b> </a></li>
<li class="chapter" data-level="5.4.8" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-77"><i class="fa fa-check"></i><b>5.4.8</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>6</b> Full SEM</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>6.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="lecture-5.html"><a href="lecture-5.html#recording-2"><i class="fa fa-check"></i><b>6.1.1</b> Recording</a></li>
<li class="chapter" data-level="6.1.2" data-path="lecture-5.html"><a href="lecture-5.html#slides-5"><i class="fa fa-check"></i><b>6.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>6.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#reference-4"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#questions-4"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>6.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-78"><i class="fa fa-check"></i><b>6.3.1</b> </a></li>
<li class="chapter" data-level="6.3.2" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-79"><i class="fa fa-check"></i><b>6.3.2</b> </a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>6.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-80"><i class="fa fa-check"></i><b>6.4.1</b> </a></li>
<li class="chapter" data-level="6.4.2" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#toraCFA"><i class="fa fa-check"></i><b>6.4.2</b> </a></li>
<li class="chapter" data-level="6.4.3" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-81"><i class="fa fa-check"></i><b>6.4.3</b> </a></li>
<li class="chapter" data-level="6.4.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#updatedModel"><i class="fa fa-check"></i><b>6.4.4</b> </a></li>
<li class="chapter" data-level="6.4.5" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-82"><i class="fa fa-check"></i><b>6.4.5</b> </a></li>
<li class="chapter" data-level="6.4.6" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-83"><i class="fa fa-check"></i><b>6.4.6</b> </a></li>
<li class="chapter" data-level="6.4.7" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-84"><i class="fa fa-check"></i><b>6.4.7</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>7</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="lecture-6.html"><a href="lecture-6.html#recordings-3"><i class="fa fa-check"></i><b>7.1.1</b> Recordings</a></li>
<li class="chapter" data-level="7.1.2" data-path="lecture-6.html"><a href="lecture-6.html#slides-6"><i class="fa fa-check"></i><b>7.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgPathAnalysis"><i class="fa fa-check"></i><b>7.3.1</b> Multiple-Group Path Analysis</a></li>
<li class="chapter" data-level="7.3.2" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgCFA"><i class="fa fa-check"></i><b>7.3.2</b> Multiple-Group CFA</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#w7MeasurementInvariance"><i class="fa fa-check"></i><b>7.4.1</b> Measurement Invariance</a></li>
<li class="chapter" data-level="7.4.2" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#testing-between-group-differences"><i class="fa fa-check"></i><b>7.4.2</b> Testing Between-Group Differences</a></li>
<li class="chapter" data-level="7.4.3" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#multiple-group-sem-for-moderation"><i class="fa fa-check"></i><b>7.4.3</b> Multiple-Group SEM for Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="wrap-up.html"><a href="wrap-up.html"><i class="fa fa-check"></i><b>8</b> Wrap-Up</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Theory Construction and Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="at-home-exercises-6" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> At-Home Exercises<a href="at-home-exercises-6.html#at-home-exercises-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
<div id="mgPathAnalysis" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Multiple-Group Path Analysis<a href="at-home-exercises-6.html#mgPathAnalysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>To fix ideas, we’ll start these practical exercises by re-running part of the
moderation analysis from the <a href="at-home-exercises-2.html#moderation">Week 3 At-Home Exercises</a>
as a multiple group model.</p>
<hr />
<div id="section-85" class="section level4" number="7.3.1.1">
<h4><span class="header-section-number">7.3.1.1</span> </h4>
<p>Load the <a href="https://surfdrive.surf.nl/files/index.php/s/dfzC7Tf5HHiTX8M/download"><em>Sesam2.sav</em></a> data.</p>
<ul>
<li><em>NOTE:</em> Unless otherwise specified, all analyses in Section <a href="at-home-exercises-6.html#mgPathAnalysis">7.3.1</a>
use these data.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="at-home-exercises-6.html#cb260-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb260-2"><a href="at-home-exercises-6.html#cb260-2" tabindex="-1"></a></span>
<span id="cb260-3"><a href="at-home-exercises-6.html#cb260-3" tabindex="-1"></a><span class="co"># Read the data into an object called &#39;sesam2&#39;:</span></span>
<span id="cb260-4"><a href="at-home-exercises-6.html#cb260-4" tabindex="-1"></a>sesam2 <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;Sesam2.sav&quot;</span>)</span></code></pre></div>
</details>
<hr />
<p><code>VIEWCAT</code> is a nominal grouping variable, but it is represented as a numeric
variable in the <code>sesam2</code> data. The levels represent the following frequencies of
Sesame Street viewership of the children in the data:</p>
<ul>
<li><code>VIEWCAT = 1</code>: Rarely/Never</li>
<li><code>VIEWCAT = 2</code>: 2–3 times a week</li>
<li><code>VIEWCAT = 3</code>: 4–5 times a week</li>
<li><code>VIEWCAT = 4</code>: &gt; 5 times a week</li>
</ul>
<p>We will use <code>VIEWCAT</code> as the grouping variable in our path model. To do so, we
don’t really need to convert <code>VIEWCAT</code> into a factor, but, if we do, <strong>lavaan</strong>
will give our groups meaningful labels in the output. That added clarity can be
pretty helpful.</p>
<hr />
</div>
<div id="section-86" class="section level4" number="7.3.1.2">
<h4><span class="header-section-number">7.3.1.2</span> </h4>
<p>Convert <em>VIEWCAT</em> into a factor.</p>
<ul>
<li>Make sure that <code>VIEWCAT = 1</code> is the reference group.</li>
<li>Assign the factor labels denoted above.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="at-home-exercises-6.html#cb261-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb261-2"><a href="at-home-exercises-6.html#cb261-2" tabindex="-1"></a></span>
<span id="cb261-3"><a href="at-home-exercises-6.html#cb261-3" tabindex="-1"></a><span class="do">## Store the old version for checking:</span></span>
<span id="cb261-4"><a href="at-home-exercises-6.html#cb261-4" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> sesam2<span class="sc">$</span>VIEWCAT</span>
<span id="cb261-5"><a href="at-home-exercises-6.html#cb261-5" tabindex="-1"></a></span>
<span id="cb261-6"><a href="at-home-exercises-6.html#cb261-6" tabindex="-1"></a><span class="do">## Convert &#39;VIEWCAT&#39; to a factor:</span></span>
<span id="cb261-7"><a href="at-home-exercises-6.html#cb261-7" tabindex="-1"></a> sesam2 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(sesam2,</span>
<span id="cb261-8"><a href="at-home-exercises-6.html#cb261-8" tabindex="-1"></a>                  <span class="at">VIEWCAT =</span> <span class="fu">factor</span>(VIEWCAT,</span>
<span id="cb261-9"><a href="at-home-exercises-6.html#cb261-9" tabindex="-1"></a>                                   <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Rarely/never&quot;</span>,</span>
<span id="cb261-10"><a href="at-home-exercises-6.html#cb261-10" tabindex="-1"></a>                                              <span class="st">&quot;2-3 times per week&quot;</span>,</span>
<span id="cb261-11"><a href="at-home-exercises-6.html#cb261-11" tabindex="-1"></a>                                              <span class="st">&quot;4-5 times per week&quot;</span>,</span>
<span id="cb261-12"><a href="at-home-exercises-6.html#cb261-12" tabindex="-1"></a>                                              <span class="st">&quot;&gt; 5 times per week&quot;</span>)</span>
<span id="cb261-13"><a href="at-home-exercises-6.html#cb261-13" tabindex="-1"></a>                                              )</span>
<span id="cb261-14"><a href="at-home-exercises-6.html#cb261-14" tabindex="-1"></a>                  )</span>
<span id="cb261-15"><a href="at-home-exercises-6.html#cb261-15" tabindex="-1"></a></span>
<span id="cb261-16"><a href="at-home-exercises-6.html#cb261-16" tabindex="-1"></a><span class="do">## Check the conversion:</span></span>
<span id="cb261-17"><a href="at-home-exercises-6.html#cb261-17" tabindex="-1"></a><span class="fu">table</span>(<span class="at">old =</span> tmp, <span class="at">new =</span> sesam2<span class="sc">$</span>VIEWCAT, <span class="at">useNA =</span> <span class="st">&quot;always&quot;</span>)</span></code></pre></div>
<pre><code>##       new
## old    Rarely/never 2-3 times per week 4-5 times per week &gt; 5 times per week
##   1              25                  0                  0                  0
##   2               0                 44                  0                  0
##   3               0                  0                 57                  0
##   4               0                  0                  0                 53
##   &lt;NA&gt;            0                  0                  0                  0
##       new
## old    &lt;NA&gt;
##   1       0
##   2       0
##   3       0
##   4       0
##   &lt;NA&gt;    0</code></pre>
</details>
<hr />
</div>
<div id="section-87" class="section level4" number="7.3.1.3">
<h4><span class="header-section-number">7.3.1.3</span> </h4>
<p>Create a conditional slopes plot to visualize the effect of <code>AGE</code> on <code>POSTNUMB</code>
within each of the <code>VIEWCAT</code> groups.</p>
<ul>
<li>Based on this visualization, do you think it is reasonable to expect that
<code>VIEWCAT</code> moderates the effect of <code>AGE</code> on <code>POSTNUMB</code>?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="at-home-exercises-6.html#cb263-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb263-2"><a href="at-home-exercises-6.html#cb263-2" tabindex="-1"></a></span>
<span id="cb263-3"><a href="at-home-exercises-6.html#cb263-3" tabindex="-1"></a><span class="fu">ggplot</span>(sesam2, <span class="fu">aes</span>(AGE, POSTNUMB, <span class="at">color =</span> VIEWCAT)) <span class="sc">+</span> </span>
<span id="cb263-4"><a href="at-home-exercises-6.html#cb263-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb263-5"><a href="at-home-exercises-6.html#cb263-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-433-1.png" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<p>The regression lines representing the conditional focal effects are not parallel,
so there appears to be some level of moderation. That being said, the differences
are pretty small, so the moderation may not be significant (i.e., the non-parallel
regression lines may simply be reflecting sampling variability).</p>
</details>
</details>
<hr />
<p>We will use path analysis to test if <code>VIEWCAT</code> moderates the effect of <code>AGE</code> on
<code>POSTNUMB</code>. This analysis will entail three steps:</p>
<ol style="list-style-type: decimal">
<li>Estimate the unrestricted multiple-group model wherein we regress <code>POSTNUMB</code>
onto <code>AGE</code> and specify <code>VIEWCAT</code> as the grouping factor.</li>
<li>Estimate the restricted model wherein we constrain the <code>AGE</code> <span class="math inline">\(\rightarrow\)</span>
<code>POSTNUMB</code> effect to be equal in all <code>VIEWCAT</code> groups.</li>
<li>Conduct a <span class="math inline">\(\Delta \chi^2\)</span> test to compare the fit of the two models.</li>
</ol>
<hr />
</div>
<div id="fullPaMod" class="section level4" number="7.3.1.4">
<h4><span class="header-section-number">7.3.1.4</span> </h4>
<p>Estimate the unrestricted path model described above.</p>
<ul>
<li>Include the intercept term in your model.</li>
<li>Judging from the focal effects estimate in each group, do you think moderation
is plausible?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="at-home-exercises-6.html#cb264-1" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb264-2"><a href="at-home-exercises-6.html#cb264-2" tabindex="-1"></a></span>
<span id="cb264-3"><a href="at-home-exercises-6.html#cb264-3" tabindex="-1"></a><span class="do">## Estimate the additive model a view the results:</span></span>
<span id="cb264-4"><a href="at-home-exercises-6.html#cb264-4" tabindex="-1"></a>out_full <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39;POSTNUMB ~ 1 + AGE&#39;</span>, <span class="at">data =</span> sesam2, <span class="at">group =</span> <span class="st">&quot;VIEWCAT&quot;</span>)</span>
<span id="cb264-5"><a href="at-home-exercises-6.html#cb264-5" tabindex="-1"></a><span class="fu">summary</span>(out_full)</span></code></pre></div>
<pre><code>## lavaan 0.6-18 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        12
## 
##   Number of observations per group:                   
##     Rarely/never                                    25
##     4-5 times per week                              57
##     &gt; 5 times per week                              53
##     2-3 times per week                              44
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
##   Test statistic for each group:
##     Rarely/never                                 0.000
##     4-5 times per week                           0.000
##     &gt; 5 times per week                           0.000
##     2-3 times per week                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [Rarely/never]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE               0.747    0.239    3.118    0.002
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        -18.721   12.142   -1.542    0.123
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB         73.285   20.728    3.536    0.000
## 
## 
## Group 2 [4-5 times per week]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE               0.554    0.234    2.369    0.018
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB          4.861   12.178    0.399    0.690
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        135.923   25.461    5.339    0.000
## 
## 
## Group 3 [&gt; 5 times per week]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE               0.405    0.214    1.894    0.058
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB         15.676   11.249    1.394    0.163
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        115.942   22.523    5.148    0.000
## 
## 
## Group 4 [2-3 times per week]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE               0.729    0.255    2.855    0.004
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB         -8.747   13.003   -0.673    0.501
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        112.019   23.882    4.690    0.000</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>There are some notable differences in the <code>AGE</code> <span class="math inline">\(\rightarrow\)</span> <code>POSTNUMB</code> focal
effect between <code>VIEWCAT</code> groups. It looks like <code>VIEWCAT</code> could moderate the
focal effect.</p>
</details>
</details>
<hr />
</div>
<div id="resPaMod" class="section level4" number="7.3.1.5">
<h4><span class="header-section-number">7.3.1.5</span> </h4>
<p>Estimate the restricted model described above.</p>
<ul>
<li>Equate the focal effect across all <code>VIEWCAT</code> groups.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="at-home-exercises-6.html#cb266-1" tabindex="-1"></a><span class="do">## Estimate the restricted model and view the results:</span></span>
<span id="cb266-2"><a href="at-home-exercises-6.html#cb266-2" tabindex="-1"></a>out_res <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="st">&#39;POSTNUMB ~ 1 + c(&quot;b1&quot;, &quot;b1&quot;, &quot;b1&quot;, &quot;b1&quot;) * AGE&#39;</span>,</span>
<span id="cb266-3"><a href="at-home-exercises-6.html#cb266-3" tabindex="-1"></a>               <span class="at">data =</span> sesam2,</span>
<span id="cb266-4"><a href="at-home-exercises-6.html#cb266-4" tabindex="-1"></a>               <span class="at">group =</span> <span class="st">&quot;VIEWCAT&quot;</span>)</span>
<span id="cb266-5"><a href="at-home-exercises-6.html#cb266-5" tabindex="-1"></a><span class="fu">summary</span>(out_res)</span></code></pre></div>
<pre><code>## lavaan 0.6-18 ended normally after 38 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        12
##   Number of equality constraints                     3
## 
##   Number of observations per group:                   
##     Rarely/never                                    25
##     4-5 times per week                              57
##     &gt; 5 times per week                              53
##     2-3 times per week                              44
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 1.486
##   Degrees of freedom                                 3
##   P-value (Chi-square)                           0.685
##   Test statistic for each group:
##     Rarely/never                                 0.413
##     4-5 times per week                           0.027
##     &gt; 5 times per week                           0.760
##     2-3 times per week                           0.287
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [Rarely/never]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE       (b1)    0.592    0.118    5.032    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        -10.966    6.154   -1.782    0.075
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB         74.505   21.073    3.536    0.000
## 
## 
## Group 2 [4-5 times per week]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE       (b1)    0.592    0.118    5.032    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB          2.869    6.275    0.457    0.647
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        135.988   25.473    5.339    0.000
## 
## 
## Group 3 [&gt; 5 times per week]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE       (b1)    0.592    0.118    5.032    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB          5.923    6.313    0.938    0.348
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        117.616   22.848    5.148    0.000
## 
## 
## Group 4 [2-3 times per week]:
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   POSTNUMB ~                                          
##     AGE       (b1)    0.592    0.118    5.032    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB         -1.826    6.157   -0.297    0.767
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .POSTNUMB        112.751   24.039    4.690    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-88" class="section level4" number="7.3.1.6">
<h4><span class="header-section-number">7.3.1.6</span> </h4>
<p>Test for moderation by comparing the full and restricted models from
<a href="at-home-exercises-6.html#fullPaMod">7.3.1.4</a> and <a href="at-home-exercises-6.html#resPaMod">7.3.1.5</a>, respectively:</p>
<ul>
<li>Does <code>VIEWCAT</code> significantly moderate the effect of <code>AGE</code> on <code>POSTNUMB</code>?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="at-home-exercises-6.html#cb268-1" tabindex="-1"></a><span class="do">## Test for moderation:</span></span>
<span id="cb268-2"><a href="at-home-exercises-6.html#cb268-2" tabindex="-1"></a><span class="fu">anova</span>(out_full, out_res)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Chisq diff"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["RMSEA"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Df diff"],"name":[7],"type":["int"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"0","2":"1378.863","3":"1417.112","4":"0.000000","5":"NA","6":"NA","7":"NA","8":"NA","_rn_":"out_full"},{"1":"3","2":"1374.349","3":"1403.036","4":"1.486213","5":"1.486213","6":"0","7":"3","8":"0.6854559","_rn_":"out_res"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>No, <em>VIEWCAT</em> does not significantly moderate the effect of <em>AGE</em> on <em>POSTNUMB</em>
(<span class="math inline">\(\Delta \chi^2[3] = 1.486\)</span>, <span class="math inline">\(p = 0.685\)</span>).</p>
</details>
</details>
<hr />
</div>
</div>
<div id="mgCFA" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Multiple-Group CFA<a href="at-home-exercises-6.html#mgCFA" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>In the next part of these exercises, we will estimate a multiple-group CFA to
evaluate the measurement structure of a scale assessing <em>Prolonged Grief Disorder</em>.
The relevant data are contained in the <a href="https://surfdrive.surf.nl/files/index.php/s/xxkp4gZY682AGyY/download"><em>PGDdata2.txt</em></a> file. This dataset
consists of a grouping variable, <code>Kin2</code> (with two levels: “partner” and “else”)
and 5 items taken from the <em>Inventory of Complicated Grief</em>:</p>
<ol style="list-style-type: decimal">
<li>Yearning</li>
<li>Part of self died</li>
<li>Difficulty accepting the loss</li>
<li>Avoiding reminders of deceased</li>
<li>Bitterness about the loss</li>
</ol>
<p>You can find more information about this scale in <a href="https://doi.org/10.1016/j.jad.2010.01.076">Boelen et al. (2010)</a>.</p>
<hr />
<div id="section-89" class="section level4" number="7.3.2.1">
<h4><span class="header-section-number">7.3.2.1</span> </h4>
<p>Load the <em>PGDdata2.txt</em> data.</p>
<ul>
<li><p>Use the <code>read.table()</code> function to load the data.</p>
<ul>
<li>Convert the missing values to <code>NA</code> via the <code>na.strings</code> argument.</li>
<li>Retain the column labels via the <code>header</code> argument.</li>
<li>Specify the field delimiter as the tab character (i.e., <code>"\t"</code>).</li>
</ul></li>
<li><p>Exclude any cases with missing values on <code>Kin2</code>.</p></li>
<li><p><em>NOTE:</em> Unless otherwise specified, all analyses in Section <a href="at-home-exercises-6.html#mgCFA">7.3.2</a> use
these data.</p></li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="at-home-exercises-6.html#cb269-1" tabindex="-1"></a><span class="do">## Load the data:</span></span>
<span id="cb269-2"><a href="at-home-exercises-6.html#cb269-2" tabindex="-1"></a>pgd <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;PGDdata2.txt&quot;</span>,</span>
<span id="cb269-3"><a href="at-home-exercises-6.html#cb269-3" tabindex="-1"></a>                  <span class="at">na.strings =</span> <span class="st">&quot;-999&quot;</span>,</span>
<span id="cb269-4"><a href="at-home-exercises-6.html#cb269-4" tabindex="-1"></a>                  <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb269-5"><a href="at-home-exercises-6.html#cb269-5" tabindex="-1"></a>                  <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb269-6"><a href="at-home-exercises-6.html#cb269-6" tabindex="-1"></a>       <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Kin2))</span>
<span id="cb269-7"><a href="at-home-exercises-6.html#cb269-7" tabindex="-1"></a></span>
<span id="cb269-8"><a href="at-home-exercises-6.html#cb269-8" tabindex="-1"></a><span class="do">## Check the results:</span></span>
<span id="cb269-9"><a href="at-home-exercises-6.html#cb269-9" tabindex="-1"></a><span class="fu">head</span>(pgd)</span>
<span id="cb269-10"><a href="at-home-exercises-6.html#cb269-10" tabindex="-1"></a><span class="fu">summary</span>(pdg)</span>
<span id="cb269-11"><a href="at-home-exercises-6.html#cb269-11" tabindex="-1"></a><span class="fu">str</span>(pgd)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Kin2"],"name":[1],"type":["int"],"align":["right"]},{"label":["b1pss1"],"name":[2],"type":["int"],"align":["right"]},{"label":["b2pss2"],"name":[3],"type":["int"],"align":["right"]},{"label":["b3pss3"],"name":[4],"type":["int"],"align":["right"]},{"label":["b4pss4"],"name":[5],"type":["int"],"align":["right"]},{"label":["b5pss5"],"name":[6],"type":["int"],"align":["right"]}],"data":[{"1":"0","2":"1","3":"1","4":"1","5":"1","6":"1","_rn_":"1"},{"1":"0","2":"1","3":"0","4":"0","5":"1","6":"0","_rn_":"2"},{"1":"1","2":"1","3":"1","4":"1","5":"1","6":"0","_rn_":"3"},{"1":"1","2":"1","3":"0","4":"1","5":"1","6":"0","_rn_":"4"},{"1":"0","2":"1","3":"1","4":"2","5":"0","6":"0","_rn_":"5"},{"1":"1","2":"2","3":"2","4":"2","5":"2","6":"1","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre><code>##       Kin2            b1pss1          b2pss2           b3pss3      
##  Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :1.000   Median :0.0000   Median :1.0000  
##  Mean   :0.6661   Mean   :1.236   Mean   :0.4622   Mean   :0.9771  
##  3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :5.000   Max.   :3.0000   Max.   :5.0000  
##                                                    NA&#39;s   :1       
##      b4pss4          b5pss5      
##  Min.   :0.000   Min.   :0.0000  
##  1st Qu.:0.000   1st Qu.:0.0000  
##  Median :1.000   Median :0.0000  
##  Mean   :1.009   Mean   :0.6761  
##  3rd Qu.:2.000   3rd Qu.:1.0000  
##  Max.   :3.000   Max.   :3.0000  
##                  NA&#39;s   :1</code></pre>
<pre><code>## &#39;data.frame&#39;:    569 obs. of  6 variables:
##  $ Kin2  : int  0 0 1 1 0 1 1 1 1 1 ...
##  $ b1pss1: int  1 1 1 1 1 2 1 3 1 1 ...
##  $ b2pss2: int  1 0 1 0 1 2 1 2 0 0 ...
##  $ b3pss3: int  1 0 1 1 2 2 1 2 1 1 ...
##  $ b4pss4: int  1 1 1 1 0 2 2 3 0 1 ...
##  $ b5pss5: int  1 0 0 0 0 1 2 3 0 0 ...</code></pre>
</details>
<hr />
</div>
<div id="oneGroupCFA" class="section level4" number="7.3.2.2">
<h4><span class="header-section-number">7.3.2.2</span> </h4>
<p>Run a single-group CFA wherein the five scale variables described above indicate
a single latent factor.</p>
<ul>
<li>Do not include any grouping variable.</li>
<li>Use the default settings in the <code>cfa()</code> function.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="at-home-exercises-6.html#cb272-1" tabindex="-1"></a><span class="do">## Define the model syntax:</span></span>
<span id="cb272-2"><a href="at-home-exercises-6.html#cb272-2" tabindex="-1"></a>cfaMod <span class="ot">&lt;-</span> <span class="st">&#39;grief =~ b1pss1 + b2pss2 + b3pss3 + b4pss4 + b5pss5&#39;</span></span>
<span id="cb272-3"><a href="at-home-exercises-6.html#cb272-3" tabindex="-1"></a></span>
<span id="cb272-4"><a href="at-home-exercises-6.html#cb272-4" tabindex="-1"></a><span class="do">## Estimate the model:</span></span>
<span id="cb272-5"><a href="at-home-exercises-6.html#cb272-5" tabindex="-1"></a>out0 <span class="ot">&lt;-</span> <span class="fu">cfa</span>(cfaMod, <span class="at">data =</span> pgd)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-90" class="section level4" number="7.3.2.3">
<h4><span class="header-section-number">7.3.2.3</span> </h4>
<p>Summarize the evaluate the fitted CFA</p>
<ul>
<li>Does the model fit well?</li>
<li>Are the items homogeneously associated with the latent factor?</li>
<li>Which item is most weakly associated with the latent factor?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="at-home-exercises-6.html#cb273-1" tabindex="-1"></a><span class="do">## Summarize the fitted model:</span></span>
<span id="cb273-2"><a href="at-home-exercises-6.html#cb273-2" tabindex="-1"></a><span class="fu">summary</span>(out0, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-18 ended normally after 19 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        10
## 
##                                                   Used       Total
##   Number of observations                           567         569
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 8.110
##   Degrees of freedom                                 5
##   P-value (Chi-square)                           0.150
## 
## Model Test Baseline Model:
## 
##   Test statistic                               775.364
##   Degrees of freedom                                10
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.996
##   Tucker-Lewis Index (TLI)                       0.992
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -3219.918
##   Loglikelihood unrestricted model (H1)      -3215.863
##                                                       
##   Akaike (AIC)                                6459.836
##   Bayesian (BIC)                              6503.240
##   Sample-size adjusted Bayesian (SABIC)       6471.495
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.033
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.073
##   P-value H_0: RMSEA &lt;= 0.050                    0.710
##   P-value H_0: RMSEA &gt;= 0.080                    0.023
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.018
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   grief =~                                                              
##     b1pss1            1.000                               0.752    0.759
##     b2pss2            0.454    0.043   10.570    0.000    0.341    0.495
##     b3pss3            0.831    0.058   14.445    0.000    0.625    0.691
##     b4pss4            0.770    0.055   14.010    0.000    0.579    0.667
##     b5pss5            0.817    0.057   14.410    0.000    0.614    0.689
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .b1pss1            0.416    0.037   11.300    0.000    0.416    0.424
##    .b2pss2            0.358    0.023   15.549    0.000    0.358    0.755
##    .b3pss3            0.427    0.033   13.117    0.000    0.427    0.522
##    .b4pss4            0.419    0.031   13.599    0.000    0.419    0.555
##    .b5pss5            0.417    0.032   13.160    0.000    0.417    0.525
##     grief             0.565    0.059    9.514    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     b1pss1            0.576
##     b2pss2            0.245
##     b3pss3            0.478
##     b4pss4            0.445
##     b5pss5            0.475</code></pre>
<details>
<summary>
Click for explanation
</summary>
<ul>
<li><p>The model fits the data quite well (<span class="math inline">\(\chi^2[5] = 8.11\)</span>,
<span class="math inline">\(p = 0.15\)</span>,
<span class="math inline">\(\textit{RMSEA} = 0.033\)</span>,
<span class="math inline">\(\textit{CFI} = 0.996\)</span>,
<span class="math inline">\(\textit{SRMR} = 0.018\)</span>).</p></li>
<li><p>All of the indicators appear to be more-or-less equally good indicators of the
latent factor except for b2pss2 which has a standardized factor loading of
<span class="math inline">\(\lambda = 0.495\)</span> and <span class="math inline">\(R^2 = 0.245\)</span>.</p>
</details></li>
</ul>
</details>
<hr />
</div>
<div id="twoGroupCFA" class="section level4" number="7.3.2.4">
<h4><span class="header-section-number">7.3.2.4</span> </h4>
<p>Rerun the CFA from <a href="at-home-exercises-6.html#oneGroupCFA">7.3.2.2</a> as a multiple-group model.</p>
<ul>
<li>Use the <code>Kin2</code> variable as the grouping factor.</li>
<li>Do not place any equality constraints across groups.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="at-home-exercises-6.html#cb275-1" tabindex="-1"></a>out1 <span class="ot">&lt;-</span> <span class="fu">cfa</span>(cfaMod, <span class="at">data =</span> pgd, <span class="at">group =</span> <span class="st">&quot;Kin2&quot;</span>)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-91" class="section level4" number="7.3.2.5">
<h4><span class="header-section-number">7.3.2.5</span> </h4>
<p>Summarize the fitted multiple-group CFA from <a href="at-home-exercises-6.html#twoGroupCFA">7.3.2.4</a>.</p>
<ul>
<li>Does the two-group model fit the data well?</li>
<li>Do you notice any salient differences between the two sets of within-group
estimates?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="at-home-exercises-6.html#cb276-1" tabindex="-1"></a><span class="fu">summary</span>(out1, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-18 ended normally after 27 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        30
## 
##   Number of observations per group:               Used       Total
##     0                                              188         190
##     1                                              379         379
## 
## Model Test User Model:
##                                                       
##   Test statistic                                11.317
##   Degrees of freedom                                10
##   P-value (Chi-square)                           0.333
##   Test statistic for each group:
##     0                                            8.976
##     1                                            2.340
## 
## Model Test Baseline Model:
## 
##   Test statistic                               781.358
##   Degrees of freedom                                20
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.998
##   Tucker-Lewis Index (TLI)                       0.997
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -3206.363
##   Loglikelihood unrestricted model (H1)      -3200.705
##                                                       
##   Akaike (AIC)                                6472.727
##   Bayesian (BIC)                              6602.937
##   Sample-size adjusted Bayesian (SABIC)       6507.701
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.022
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.070
##   P-value H_0: RMSEA &lt;= 0.050                    0.789
##   P-value H_0: RMSEA &gt;= 0.080                    0.018
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.017
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   grief =~                                                              
##     b1pss1            1.000                               0.702    0.712
##     b2pss2            0.372    0.076    4.922    0.000    0.261    0.410
##     b3pss3            0.938    0.118    7.986    0.000    0.659    0.709
##     b4pss4            0.909    0.116    7.848    0.000    0.638    0.691
##     b5pss5            0.951    0.122    7.774    0.000    0.667    0.683
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .b1pss1            1.346    0.072   18.727    0.000    1.346    1.366
##    .b2pss2            0.441    0.046    9.499    0.000    0.441    0.693
##    .b3pss3            1.059    0.068   15.618    0.000    1.059    1.139
##    .b4pss4            1.122    0.067   16.671    0.000    1.122    1.216
##    .b5pss5            0.745    0.071   10.442    0.000    0.745    0.762
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .b1pss1            0.478    0.067    7.118    0.000    0.478    0.493
##    .b2pss2            0.338    0.037    9.205    0.000    0.338    0.832
##    .b3pss3            0.430    0.060    7.170    0.000    0.430    0.498
##    .b4pss4            0.445    0.060    7.408    0.000    0.445    0.522
##    .b5pss5            0.511    0.068    7.519    0.000    0.511    0.534
##     grief             0.493    0.098    5.007    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     b1pss1            0.507
##     b2pss2            0.168
##     b3pss3            0.502
##     b4pss4            0.478
##     b5pss5            0.466
## 
## 
## Group 2 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   grief =~                                                              
##     b1pss1            1.000                               0.769    0.778
##     b2pss2            0.502    0.052    9.597    0.000    0.386    0.542
##     b3pss3            0.785    0.066   11.945    0.000    0.604    0.680
##     b4pss4            0.708    0.062   11.497    0.000    0.544    0.652
##     b5pss5            0.762    0.062   12.185    0.000    0.586    0.696
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .b1pss1            1.182    0.051   23.277    0.000    1.182    1.196
##    .b2pss2            0.475    0.037   12.973    0.000    0.475    0.666
##    .b3pss3            0.934    0.046   20.460    0.000    0.934    1.051
##    .b4pss4            0.955    0.043   22.270    0.000    0.955    1.144
##    .b5pss5            0.644    0.043   14.879    0.000    0.644    0.764
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .b1pss1            0.385    0.043    8.862    0.000    0.385    0.394
##    .b2pss2            0.359    0.029   12.468    0.000    0.359    0.706
##    .b3pss3            0.425    0.039   11.025    0.000    0.425    0.538
##    .b4pss4            0.401    0.035   11.420    0.000    0.401    0.575
##    .b5pss5            0.366    0.034   10.767    0.000    0.366    0.516
##     grief             0.592    0.073    8.081    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     b1pss1            0.606
##     b2pss2            0.294
##     b3pss3            0.462
##     b4pss4            0.425
##     b5pss5            0.484</code></pre>
<details>
<summary>
Click for explanation
</summary>
<ul>
<li><p>The two-group model also fits the data very well (<span class="math inline">\(\chi^2[10] = 11.32\)</span>,
<span class="math inline">\(p = 0.333\)</span>,
<span class="math inline">\(\textit{RMSEA} = 0.022\)</span>,
<span class="math inline">\(\textit{CFI} = 0.998\)</span>,
<span class="math inline">\(\textit{SRMR} = 0.017\)</span>).</p></li>
<li><p>No, there are no striking differences between the two sets of estimates. Although
there is certainly some variability between groups, the two sets of estimates
don’t look systematically different.</p>
</details></li>
</ul>
</details>
<hr />
</div>
<div id="section-92" class="section level4" number="7.3.2.6">
<h4><span class="header-section-number">7.3.2.6</span> </h4>
<p>Based on the above results, what can you conclude about configural, weak, and
strong measurement invariance across the <code>Kin2</code> groups?</p>
<details>
<summary>
Click for explanation
</summary>
<ul>
<li>Configural invariance holds. The unrestricted multiple-group CFA fits the data
adequately (very well, actually), and the measurement model parameters are
reasonable in both groups.</li>
<li>We cannot yet draw any conclusions about weak or strong invariance. We need to
do the appropriate model comparison tests first.</li>
</ul>
</details>
<hr />
<p>End of At-Home Exercises</p>
<hr />
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reading-6.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="in-class-exercises-6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["willy_wallaby_from_wasatch.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"search": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
