<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.4 In-Class Exercises | Theory Construction and Statistical Modeling</title>
  <meta name="description" content="7.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="7.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises-6.html"/>
<link rel="next" href="wrap-up.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">TCSM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reading-questions.html"><a href="reading-questions.html"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html"><i class="fa fa-check"></i>Weekly preparation</a>
<ul>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="evaluation.html"><a href="evaluation.html"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="attendance.html"><a href="attendance.html"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="a1_components.html"><a href="a1_components.html"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="a1_components.html"><a href="a1_components.html#evaluation-1"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a1_components.html"><a href="a1_components.html#submission"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a2_worksheet.html"><a href="a2_worksheet.html"><i class="fa fa-check"></i>Assignment 2: Confirmatory Factor Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="a2_worksheet.html"><a href="a2_worksheet.html#evaluation-2"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a2_worksheet.html"><a href="a2_worksheet.html#submission-1"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html"><i class="fa fa-check"></i>Assignment 3: Full Structural Equation Model</a>
<ul>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#evaluation-3"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#progression"><i class="fa fa-check"></i>Progression</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#reporting_standards"><i class="fa fa-check"></i>Reporting Standards</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html"><i class="fa fa-check"></i>Data</a>
<ul>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#coping-with-covid"><i class="fa fa-check"></i>Coping with Covid</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#feminist-perspectives-scale"><i class="fa fa-check"></i>Feminist Perspectives Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#hypersensitive-narcissism-scale-dirty-dozen"><i class="fa fa-check"></i>Hypersensitive Narcissism Scale &amp; Dirty Dozen</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#kentucky-inventory-of-mindfulness-skills"><i class="fa fa-check"></i>Kentucky Inventory of Mindfulness Skills</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#depression-anxiety-stress-scale"><i class="fa fa-check"></i>Depression Anxiety Stress Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#nomophobia"><i class="fa fa-check"></i>Nomophobia</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#recycled-water-acceptance"><i class="fa fa-check"></i>Recycled Water Acceptance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-3"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#group-assignments"><i class="fa fa-check"></i>Group Assignments</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#individual-assignment"><i class="fa fa-check"></i>Individual Assignment</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#resits"><i class="fa fa-check"></i>Resits</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#example-assignment"><i class="fa fa-check"></i>Example Assignment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html"><i class="fa fa-check"></i>Rules</a>
<ul>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#academic-integrity"><i class="fa fa-check"></i>Academic integrity</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#using-ai-tools"><i class="fa fa-check"></i>Using AI tools</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#strict-stuff"><i class="fa fa-check"></i>Strict stuff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.1</b> </a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.1</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.2</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.3</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.1</b> Mediation</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.2</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.1</b> Mediation</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.2</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="efa.html"><a href="efa.html"><i class="fa fa-check"></i><b>4</b> EFA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recording"><i class="fa fa-check"></i><b>4.1.1</b> Recording</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-1-1"><i class="fa fa-check"></i>Reference 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-1-1"><i class="fa fa-check"></i>Questions 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-2-1"><i class="fa fa-check"></i>Reference 2</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-2-1"><i class="fa fa-check"></i>Questions 2</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-44"><i class="fa fa-check"></i><b>4.3.1</b> </a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#run_pca"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#pcScores"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#trust_efa"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaAtt"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#factorScores"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
<li class="chapter" data-level="4.4.13" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.13</b> </a></li>
<li class="chapter" data-level="4.4.14" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-64"><i class="fa fa-check"></i><b>4.4.14</b> </a></li>
<li class="chapter" data-level="4.4.15" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-65"><i class="fa fa-check"></i><b>4.4.15</b> </a></li>
<li class="chapter" data-level="4.4.16" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaRegression"><i class="fa fa-check"></i><b>4.4.16</b> </a></li>
<li class="chapter" data-level="4.4.17" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-66"><i class="fa fa-check"></i><b>4.4.17</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa.html"><a href="cfa.html"><i class="fa fa-check"></i><b>5</b> CFA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lecture-4.html"><a href="lecture-4.html#recordings-3"><i class="fa fa-check"></i><b>5.1.1</b> Recordings</a></li>
<li class="chapter" data-level="5.1.2" data-path="lecture-4.html"><a href="lecture-4.html#slides-4"><i class="fa fa-check"></i><b>5.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-67"><i class="fa fa-check"></i><b>5.3.1</b> </a></li>
<li class="chapter" data-level="5.3.2" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#cfaSyntax"><i class="fa fa-check"></i><b>5.3.2</b> </a></li>
<li class="chapter" data-level="5.3.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-68"><i class="fa fa-check"></i><b>5.3.3</b> </a></li>
<li class="chapter" data-level="5.3.4" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-69"><i class="fa fa-check"></i><b>5.3.4</b> </a></li>
<li class="chapter" data-level="5.3.5" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-70"><i class="fa fa-check"></i><b>5.3.5</b> </a></li>
<li class="chapter" data-level="5.3.6" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-71"><i class="fa fa-check"></i><b>5.3.6</b> </a></li>
<li class="chapter" data-level="5.3.7" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-72"><i class="fa fa-check"></i><b>5.3.7</b> </a></li>
<li class="chapter" data-level="5.3.8" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-73"><i class="fa fa-check"></i><b>5.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-74"><i class="fa fa-check"></i><b>5.4.1</b> </a></li>
<li class="chapter" data-level="5.4.2" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt"><i class="fa fa-check"></i><b>5.4.2</b> </a></li>
<li class="chapter" data-level="5.4.3" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-75"><i class="fa fa-check"></i><b>5.4.3</b> </a></li>
<li class="chapter" data-level="5.4.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt1f"><i class="fa fa-check"></i><b>5.4.4</b> </a></li>
<li class="chapter" data-level="5.4.5" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#compare1f5f"><i class="fa fa-check"></i><b>5.4.5</b> </a></li>
<li class="chapter" data-level="5.4.6" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-76"><i class="fa fa-check"></i><b>5.4.6</b> </a></li>
<li class="chapter" data-level="5.4.7" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfa2nd"><i class="fa fa-check"></i><b>5.4.7</b> </a></li>
<li class="chapter" data-level="5.4.8" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-77"><i class="fa fa-check"></i><b>5.4.8</b> </a></li>
<li class="chapter" data-level="5.4.9" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-78"><i class="fa fa-check"></i><b>5.4.9</b> </a></li>
<li class="chapter" data-level="5.4.10" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-79"><i class="fa fa-check"></i><b>5.4.10</b> </a></li>
<li class="chapter" data-level="5.4.11" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-80"><i class="fa fa-check"></i><b>5.4.11</b> </a></li>
<li class="chapter" data-level="5.4.12" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-81"><i class="fa fa-check"></i><b>5.4.12</b> </a></li>
<li class="chapter" data-level="5.4.13" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-82"><i class="fa fa-check"></i><b>5.4.13</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="extra-resources.html"><a href="extra-resources.html"><i class="fa fa-check"></i><b>5.5</b> Extra Resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>6</b> Full SEM</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>6.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="lecture-5.html"><a href="lecture-5.html#recording-1"><i class="fa fa-check"></i><b>6.1.1</b> Recording</a></li>
<li class="chapter" data-level="6.1.2" data-path="lecture-5.html"><a href="lecture-5.html#slides-5"><i class="fa fa-check"></i><b>6.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>6.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#reference-4"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#questions-4"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>6.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-83"><i class="fa fa-check"></i><b>6.3.1</b> </a></li>
<li class="chapter" data-level="6.3.2" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-84"><i class="fa fa-check"></i><b>6.3.2</b> </a></li>
<li class="chapter" data-level="6.3.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-85"><i class="fa fa-check"></i><b>6.3.3</b> </a></li>
<li class="chapter" data-level="6.3.4" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-86"><i class="fa fa-check"></i><b>6.3.4</b> </a></li>
<li class="chapter" data-level="6.3.5" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-87"><i class="fa fa-check"></i><b>6.3.5</b> </a></li>
<li class="chapter" data-level="6.3.6" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-88"><i class="fa fa-check"></i><b>6.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>6.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-89"><i class="fa fa-check"></i><b>6.4.1</b> </a></li>
<li class="chapter" data-level="6.4.2" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#toraCFA"><i class="fa fa-check"></i><b>6.4.2</b> </a></li>
<li class="chapter" data-level="6.4.3" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-90"><i class="fa fa-check"></i><b>6.4.3</b> </a></li>
<li class="chapter" data-level="6.4.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#updatedModel"><i class="fa fa-check"></i><b>6.4.4</b> </a></li>
<li class="chapter" data-level="6.4.5" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-91"><i class="fa fa-check"></i><b>6.4.5</b> </a></li>
<li class="chapter" data-level="6.4.6" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-92"><i class="fa fa-check"></i><b>6.4.6</b> </a></li>
<li class="chapter" data-level="6.4.7" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-93"><i class="fa fa-check"></i><b>6.4.7</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>7</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="lecture-6.html"><a href="lecture-6.html#recordings-4"><i class="fa fa-check"></i><b>7.1.1</b> Recordings</a></li>
<li class="chapter" data-level="7.1.2" data-path="lecture-6.html"><a href="lecture-6.html#slides-6"><i class="fa fa-check"></i><b>7.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgPathAnalysis"><i class="fa fa-check"></i><b>7.3.1</b> Multiple-Group Path Analysis</a></li>
<li class="chapter" data-level="7.3.2" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgCFA"><i class="fa fa-check"></i><b>7.3.2</b> Multiple-Group CFA</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#w7MeasurementInvariance"><i class="fa fa-check"></i><b>7.4.1</b> Measurement Invariance</a></li>
<li class="chapter" data-level="7.4.2" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#testing-between-group-differences"><i class="fa fa-check"></i><b>7.4.2</b> Testing Between-Group Differences</a></li>
<li class="chapter" data-level="7.4.3" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#multiple-group-sem-for-moderation"><i class="fa fa-check"></i><b>7.4.3</b> Multiple-Group SEM for Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="wrap-up.html"><a href="wrap-up.html"><i class="fa fa-check"></i><b>8</b> Wrap-Up</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Theory Construction and Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises-6" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> In-Class Exercises<a href="in-class-exercises-6.html#in-class-exercises-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
<div id="w7MeasurementInvariance" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Measurement Invariance<a href="in-class-exercises-6.html#w7MeasurementInvariance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>We’ll now pick up where we left off with the <a href="at-home-exercises-6.html">At-Home Exercises</a>
by testing measurement invariance in the two-group CFA from <a href="at-home-exercises-6.html#twoGroupCFA">7.3.2.4</a>.</p>
<p>As you saw in the lecture, measurement invariance testing allows us to
empirically test for differences in the measurement model between the groups. If
we can establish measurement invariance, we can draw the following (equivalent)
conclusions:</p>
<ul>
<li>Our latent constructs are defined equivalently in all groups.</li>
<li>The participants in every group are interpreting our items in the same way.</li>
<li>Participants in different groups who have the same values for the observed
indicators will also have the same score on the latent variable.</li>
<li>Between-group differences in latent parameters are due to true differences in
the underlying latent constructs and not caused by differences in measurement.</li>
</ul>
<p>Anytime we make between-group comparisons (e.g., ANOVA, t-tests, moderation by
group, etc.) we assume invariant measurement. That is, we assume that the scores
we’re comparing have the same meaning in each group. When doing multiple group
SEM, however, we’re apprised of the incredibly powerful capability of actually
testing this—very important, and often violated—assumption.</p>
<p>The process of testing measurement invariance can get quite complex, but the
basic procedure boils down to using model comparison tests to evaluate the
plausibility of increasingly strong between-group constraints. For most problems,
these constraints amount to the following three levels:</p>
<ol style="list-style-type: decimal">
<li><em>Configural:</em> The same pattern of free and fixed effects in all groups</li>
<li><em>Weak (aka Metric):</em> Configural + Equal factor loadings in all groups</li>
<li><em>Strong (aka Scalar):</em> Weak + Equal item intercepts in all groups</li>
</ol>
<p>You can read more about measurement invariance <a href="https://doi.org/10.1080/17405629.2012.686740">here</a> and
<a href="https://doi.org/10.1016/j.dr.2016.06.004">here</a>, and you can find a brief discussion of how to
conduct measurement invariance tests in <strong>lavaan</strong> <a href="https://www.lavaan.ugent.be/tutorial/groups.html">here</a>.</p>
<hr />
<div id="section-102" class="section level4" number="7.4.1.1">
<h4><span class="header-section-number">7.4.1.1</span> </h4>
<p>Load the <em>PGDdata2.txt</em> data as you did for the <a href="at-home-exercises-6.html">At-Home Exercises</a>.</p>
<ul>
<li><em>Note:</em> Unless otherwise specified, all analyses in Section
<a href="in-class-exercises-6.html#w7MeasurementInvariance">7.4.1</a> use these data.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="in-class-exercises-6.html#cb300-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb300-2"><a href="in-class-exercises-6.html#cb300-2" tabindex="-1"></a></span>
<span id="cb300-3"><a href="in-class-exercises-6.html#cb300-3" tabindex="-1"></a><span class="do">## Load the data:</span></span>
<span id="cb300-4"><a href="in-class-exercises-6.html#cb300-4" tabindex="-1"></a>pgd <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;PGDdata2.txt&quot;</span>,</span>
<span id="cb300-5"><a href="in-class-exercises-6.html#cb300-5" tabindex="-1"></a>                  <span class="at">na.strings =</span> <span class="st">&quot;-999&quot;</span>,</span>
<span id="cb300-6"><a href="in-class-exercises-6.html#cb300-6" tabindex="-1"></a>                  <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb300-7"><a href="in-class-exercises-6.html#cb300-7" tabindex="-1"></a>                  <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb300-8"><a href="in-class-exercises-6.html#cb300-8" tabindex="-1"></a>       <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Kin2))</span>
<span id="cb300-9"><a href="in-class-exercises-6.html#cb300-9" tabindex="-1"></a></span>
<span id="cb300-10"><a href="in-class-exercises-6.html#cb300-10" tabindex="-1"></a><span class="do">## Check the results:</span></span>
<span id="cb300-11"><a href="in-class-exercises-6.html#cb300-11" tabindex="-1"></a><span class="fu">head</span>(pgd)</span>
<span id="cb300-12"><a href="in-class-exercises-6.html#cb300-12" tabindex="-1"></a><span class="fu">summary</span>(pdg)</span>
<span id="cb300-13"><a href="in-class-exercises-6.html#cb300-13" tabindex="-1"></a><span class="fu">str</span>(pgd)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Kin2"],"name":[1],"type":["int"],"align":["right"]},{"label":["b1pss1"],"name":[2],"type":["int"],"align":["right"]},{"label":["b2pss2"],"name":[3],"type":["int"],"align":["right"]},{"label":["b3pss3"],"name":[4],"type":["int"],"align":["right"]},{"label":["b4pss4"],"name":[5],"type":["int"],"align":["right"]},{"label":["b5pss5"],"name":[6],"type":["int"],"align":["right"]}],"data":[{"1":"0","2":"1","3":"1","4":"1","5":"1","6":"1","_rn_":"1"},{"1":"0","2":"1","3":"0","4":"0","5":"1","6":"0","_rn_":"2"},{"1":"1","2":"1","3":"1","4":"1","5":"1","6":"0","_rn_":"3"},{"1":"1","2":"1","3":"0","4":"1","5":"1","6":"0","_rn_":"4"},{"1":"0","2":"1","3":"1","4":"2","5":"0","6":"0","_rn_":"5"},{"1":"1","2":"2","3":"2","4":"2","5":"2","6":"1","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre><code>##       Kin2            b1pss1          b2pss2           b3pss3      
##  Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :1.000   Median :0.0000   Median :1.0000  
##  Mean   :0.6661   Mean   :1.236   Mean   :0.4622   Mean   :0.9771  
##  3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :5.000   Max.   :3.0000   Max.   :5.0000  
##                                                    NA&#39;s   :1       
##      b4pss4          b5pss5      
##  Min.   :0.000   Min.   :0.0000  
##  1st Qu.:0.000   1st Qu.:0.0000  
##  Median :1.000   Median :0.0000  
##  Mean   :1.009   Mean   :0.6761  
##  3rd Qu.:2.000   3rd Qu.:1.0000  
##  Max.   :3.000   Max.   :3.0000  
##                  NA&#39;s   :1</code></pre>
<pre><code>## &#39;data.frame&#39;:    569 obs. of  6 variables:
##  $ Kin2  : int  0 0 1 1 0 1 1 1 1 1 ...
##  $ b1pss1: int  1 1 1 1 1 2 1 3 1 1 ...
##  $ b2pss2: int  1 0 1 0 1 2 1 2 0 0 ...
##  $ b3pss3: int  1 0 1 1 2 2 1 2 1 1 ...
##  $ b4pss4: int  1 1 1 1 0 2 2 3 0 1 ...
##  $ b5pss5: int  1 0 0 0 0 1 2 3 0 0 ...</code></pre>
</details>
<hr />
</div>
<div id="miTesting" class="section level4" number="7.4.1.2">
<h4><span class="header-section-number">7.4.1.2</span> </h4>
<p>Test <em>configural</em>, <em>weak</em>, and <em>strong</em> invariance using the multiple-group CFA
from <a href="at-home-exercises-6.html#twoGroupCFA">7.3.2.4</a>.</p>
<ul>
<li>What are your conclusions?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="in-class-exercises-6.html#cb303-1" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb303-2"><a href="in-class-exercises-6.html#cb303-2" tabindex="-1"></a><span class="fu">library</span>(semTools) <span class="co"># provides the compareFit() function</span></span>
<span id="cb303-3"><a href="in-class-exercises-6.html#cb303-3" tabindex="-1"></a></span>
<span id="cb303-4"><a href="in-class-exercises-6.html#cb303-4" tabindex="-1"></a><span class="do">## Define the syntax for the CFA model:</span></span>
<span id="cb303-5"><a href="in-class-exercises-6.html#cb303-5" tabindex="-1"></a>cfaMod <span class="ot">&lt;-</span> <span class="st">&#39;grief =~ b1pss1 + b2pss2 + b3pss3 + b4pss4 + b5pss5&#39;</span></span>
<span id="cb303-6"><a href="in-class-exercises-6.html#cb303-6" tabindex="-1"></a></span>
<span id="cb303-7"><a href="in-class-exercises-6.html#cb303-7" tabindex="-1"></a><span class="do">## Estimate the configural model:</span></span>
<span id="cb303-8"><a href="in-class-exercises-6.html#cb303-8" tabindex="-1"></a>configOut <span class="ot">&lt;-</span> <span class="fu">cfa</span>(cfaMod, <span class="at">data =</span> pgd, <span class="at">group =</span> <span class="st">&quot;Kin2&quot;</span>)</span>
<span id="cb303-9"><a href="in-class-exercises-6.html#cb303-9" tabindex="-1"></a></span>
<span id="cb303-10"><a href="in-class-exercises-6.html#cb303-10" tabindex="-1"></a><span class="do">## Estimate the weak invariance model:</span></span>
<span id="cb303-11"><a href="in-class-exercises-6.html#cb303-11" tabindex="-1"></a>weakOut <span class="ot">&lt;-</span> <span class="fu">cfa</span>(cfaMod, <span class="at">data =</span> pgd, <span class="at">group =</span> <span class="st">&quot;Kin2&quot;</span>, <span class="at">group.equal =</span> <span class="st">&quot;loadings&quot;</span>)</span>
<span id="cb303-12"><a href="in-class-exercises-6.html#cb303-12" tabindex="-1"></a></span>
<span id="cb303-13"><a href="in-class-exercises-6.html#cb303-13" tabindex="-1"></a><span class="do">## Estimate the strong invariance model:</span></span>
<span id="cb303-14"><a href="in-class-exercises-6.html#cb303-14" tabindex="-1"></a>strongOut <span class="ot">&lt;-</span> <span class="fu">cfa</span>(cfaMod,</span>
<span id="cb303-15"><a href="in-class-exercises-6.html#cb303-15" tabindex="-1"></a>                 <span class="at">data =</span> pgd,</span>
<span id="cb303-16"><a href="in-class-exercises-6.html#cb303-16" tabindex="-1"></a>                 <span class="at">group =</span> <span class="st">&quot;Kin2&quot;</span>,</span>
<span id="cb303-17"><a href="in-class-exercises-6.html#cb303-17" tabindex="-1"></a>                 <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;intercepts&quot;</span>)</span>
<span id="cb303-18"><a href="in-class-exercises-6.html#cb303-18" tabindex="-1"></a>                 )</span>
<span id="cb303-19"><a href="in-class-exercises-6.html#cb303-19" tabindex="-1"></a></span>
<span id="cb303-20"><a href="in-class-exercises-6.html#cb303-20" tabindex="-1"></a><span class="fu">summary</span>(configOut)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 27 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        30
## 
##   Number of observations per group:               Used       Total
##     0                                              188         190
##     1                                              379         379
## 
## Model Test User Model:
##                                                       
##   Test statistic                                11.317
##   Degrees of freedom                                10
##   P-value (Chi-square)                           0.333
##   Test statistic for each group:
##     0                                            8.976
##     1                                            2.340
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2            0.372    0.076    4.922    0.000
##     b3pss3            0.938    0.118    7.986    0.000
##     b4pss4            0.909    0.116    7.848    0.000
##     b5pss5            0.951    0.122    7.774    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            1.346    0.072   18.727    0.000
##    .b2pss2            0.441    0.046    9.499    0.000
##    .b3pss3            1.059    0.068   15.618    0.000
##    .b4pss4            1.122    0.067   16.671    0.000
##    .b5pss5            0.745    0.071   10.442    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.478    0.067    7.118    0.000
##    .b2pss2            0.338    0.037    9.205    0.000
##    .b3pss3            0.430    0.060    7.170    0.000
##    .b4pss4            0.445    0.060    7.408    0.000
##    .b5pss5            0.511    0.068    7.519    0.000
##     grief             0.493    0.098    5.007    0.000
## 
## 
## Group 2 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2            0.502    0.052    9.597    0.000
##     b3pss3            0.785    0.066   11.945    0.000
##     b4pss4            0.708    0.062   11.497    0.000
##     b5pss5            0.762    0.062   12.185    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            1.182    0.051   23.277    0.000
##    .b2pss2            0.475    0.037   12.973    0.000
##    .b3pss3            0.934    0.046   20.460    0.000
##    .b4pss4            0.955    0.043   22.270    0.000
##    .b5pss5            0.644    0.043   14.879    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.385    0.043    8.862    0.000
##    .b2pss2            0.359    0.029   12.468    0.000
##    .b3pss3            0.425    0.039   11.025    0.000
##    .b4pss4            0.401    0.035   11.420    0.000
##    .b5pss5            0.366    0.034   10.767    0.000
##     grief             0.592    0.073    8.081    0.000</code></pre>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="in-class-exercises-6.html#cb305-1" tabindex="-1"></a><span class="fu">summary</span>(weakOut)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 22 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        30
##   Number of equality constraints                     4
## 
##   Number of observations per group:               Used       Total
##     0                                              188         190
##     1                                              379         379
## 
## Model Test User Model:
##                                                       
##   Test statistic                                19.275
##   Degrees of freedom                                14
##   P-value (Chi-square)                           0.155
##   Test statistic for each group:
##     0                                           14.525
##     1                                            4.751
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2  (.p2.)    0.457    0.043   10.680    0.000
##     b3pss3  (.p3.)    0.824    0.057   14.374    0.000
##     b4pss4  (.p4.)    0.756    0.054   13.890    0.000
##     b5pss5  (.p5.)    0.805    0.056   14.388    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            1.346    0.073   18.353    0.000
##    .b2pss2            0.441    0.049    9.045    0.000
##    .b3pss3            1.059    0.067   15.828    0.000
##    .b4pss4            1.122    0.066   17.102    0.000
##    .b5pss5            0.745    0.070   10.688    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.434    0.064    6.779    0.000
##    .b2pss2            0.327    0.037    8.898    0.000
##    .b3pss3            0.449    0.058    7.786    0.000
##    .b4pss4            0.480    0.058    8.209    0.000
##    .b5pss5            0.539    0.066    8.207    0.000
##     grief             0.577    0.086    6.691    0.000
## 
## 
## Group 2 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2  (.p2.)    0.457    0.043   10.680    0.000
##     b3pss3  (.p3.)    0.824    0.057   14.374    0.000
##     b4pss4  (.p4.)    0.756    0.054   13.890    0.000
##     b5pss5  (.p5.)    0.805    0.056   14.388    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            1.182    0.050   23.496    0.000
##    .b2pss2            0.475    0.036   13.281    0.000
##    .b3pss3            0.934    0.046   20.325    0.000
##    .b4pss4            0.955    0.043   21.999    0.000
##    .b5pss5            0.644    0.044   14.731    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.399    0.042    9.474    0.000
##    .b2pss2            0.367    0.029   12.831    0.000
##    .b3pss3            0.420    0.038   11.019    0.000
##    .b4pss4            0.394    0.035   11.304    0.000
##    .b5pss5            0.361    0.034   10.686    0.000
##     grief             0.561    0.065    8.564    0.000</code></pre>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="in-class-exercises-6.html#cb307-1" tabindex="-1"></a><span class="fu">summary</span>(strongOut)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 26 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        31
##   Number of equality constraints                     9
## 
##   Number of observations per group:               Used       Total
##     0                                              188         190
##     1                                              379         379
## 
## Model Test User Model:
##                                                       
##   Test statistic                                23.968
##   Degrees of freedom                                18
##   P-value (Chi-square)                           0.156
##   Test statistic for each group:
##     0                                           17.123
##     1                                            6.846
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2  (.p2.)    0.449    0.042   10.562    0.000
##     b3pss3  (.p3.)    0.824    0.057   14.467    0.000
##     b4pss4  (.p4.)    0.760    0.054   14.007    0.000
##     b5pss5  (.p5.)    0.803    0.056   14.457    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1  (.12.)    1.332    0.066   20.221    0.000
##    .b2pss2  (.13.)    0.505    0.037   13.718    0.000
##    .b3pss3  (.14.)    1.055    0.057   18.601    0.000
##    .b4pss4  (.15.)    1.081    0.053   20.237    0.000
##    .b5pss5  (.16.)    0.756    0.056   13.525    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.435    0.064    6.773    0.000
##    .b2pss2            0.332    0.037    8.937    0.000
##    .b3pss3            0.448    0.058    7.776    0.000
##    .b4pss4            0.480    0.059    8.190    0.000
##    .b5pss5            0.539    0.066    8.207    0.000
##     grief             0.579    0.086    6.701    0.000
## 
## 
## Group 2 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2  (.p2.)    0.449    0.042   10.562    0.000
##     b3pss3  (.p3.)    0.824    0.057   14.467    0.000
##     b4pss4  (.p4.)    0.760    0.054   14.007    0.000
##     b5pss5  (.p5.)    0.803    0.056   14.457    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1  (.12.)    1.332    0.066   20.221    0.000
##    .b2pss2  (.13.)    0.505    0.037   13.718    0.000
##    .b3pss3  (.14.)    1.055    0.057   18.601    0.000
##    .b4pss4  (.15.)    1.081    0.053   20.237    0.000
##    .b5pss5  (.16.)    0.756    0.056   13.525    0.000
##     grief            -0.144    0.076   -1.911    0.056
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.398    0.042    9.469    0.000
##    .b2pss2            0.370    0.029   12.872    0.000
##    .b3pss3            0.419    0.038   11.014    0.000
##    .b4pss4            0.393    0.035   11.276    0.000
##    .b5pss5            0.361    0.034   10.700    0.000
##     grief             0.561    0.065    8.586    0.000</code></pre>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="in-class-exercises-6.html#cb309-1" tabindex="-1"></a><span class="do">## Test invariance through model comparison tests:</span></span>
<span id="cb309-2"><a href="in-class-exercises-6.html#cb309-2" tabindex="-1"></a><span class="fu">compareFit</span>(configOut, weakOut, strongOut) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## ################### Nested Model Comparison #########################
## 
## Chi-Squared Difference Test
## 
##           Df    AIC    BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)  
## configOut 10 6472.7 6602.9 11.317                                         
## weakOut   14 6472.7 6585.5 19.275     7.9585 0.059083       4    0.09311 .
## strongOut 18 6469.4 6564.9 23.968     4.6931 0.024722       4    0.32026  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## ####################### Model Fit Indices ###########################
##             chisq df pvalue rmsea    cfi    tli  srmr       aic       bic
## configOut 11.317† 10   .333 .022† 0.998† 0.997† .017† 6472.727  6602.937 
## weakOut   19.275  14   .155 .036   .993   .990  .038  6472.685  6585.534 
## strongOut 23.968  18   .156 .034   .992   .991  .042  6469.378† 6564.866†
## 
## ################## Differences in Fit Indices #######################
##                     df  rmsea    cfi    tli  srmr    aic     bic
## weakOut - configOut  4  0.015 -0.005 -0.006 0.021 -0.041 -17.403
## strongOut - weakOut  4 -0.002 -0.001  0.001 0.004 -3.307 -20.668</code></pre>
<details>
<summary>
Click for explanation
</summary>
<ul>
<li>Configural invariance holds.
<ul>
<li>The unrestricted, two-group model fits the data very well
(<span class="math inline">\(\chi^2[10] = 11.32\)</span>,
<span class="math inline">\(p = 0.333\)</span>,
<span class="math inline">\(\textit{RMSEA} = 0.022\)</span>,
<span class="math inline">\(\textit{CFI} = 0.998\)</span>,
<span class="math inline">\(\textit{SRMR} = 0.017\)</span>).</li>
</ul></li>
<li>Weak invariance holds.
<ul>
<li>The model comparison test shows a non-significant loss of fit between the
configural and weak models (<span class="math inline">\(\Delta \chi^2[4] = 7.96\)</span>, <span class="math inline">\(p = 0.093\)</span>).</li>
</ul></li>
<li>Strong invariance holds.
<ul>
<li>The model comparison test shows a non-significant loss of fit between the
weak and strong models (<span class="math inline">\(\Delta \chi^2[4] = 4.69\)</span>, <span class="math inline">\(p = 0.32\)</span>).</li>
<li>The strongly invariant model still fits the data well
(<span class="math inline">\(\chi^2[18] = 23.97\)</span>,
<span class="math inline">\(p = 0.156\)</span>,
<span class="math inline">\(\textit{RMSEA} = 0.034\)</span>,
<span class="math inline">\(\textit{CFI} = 0.992\)</span>,
<span class="math inline">\(\textit{SRMR} = 0.042\)</span>).</li>
</ul>
</details></li>
</ul>
</details>
<hr />
</div>
</div>
<div id="testing-between-group-differences" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Testing Between-Group Differences<a href="in-class-exercises-6.html#testing-between-group-differences" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>Once we establish strong invariance, we have empirical evidence that latent mean
levels are comparable across groups. Hence, we can test for differences in those
latent means. In this section, we’ll conduct the equivalent of a t-test using
our two-group CFA model.</p>
<p>More specifically, we want to know if the latent mean of <code>grief</code> differs
significantly between the <code>Kin2</code> groups. The null and alternative hypotheses for
this test are as follows:</p>
<p><span class="math display">\[
H_0: \alpha_1 = \alpha_2\\
H_1: \alpha_1 \neq \alpha_2
\]</span></p>
<p>Where, <span class="math inline">\(\alpha_1\)</span> and <span class="math inline">\(\alpha_2\)</span> represent the latent means in Group 1 and
Group 2, respectively.</p>
<hr />
<div id="section-103" class="section level4" number="7.4.2.1">
<h4><span class="header-section-number">7.4.2.1</span> </h4>
<p>Use the strongly invariant model from <a href="in-class-exercises-6.html#miTesting">7.4.1.2</a> to test the latent mean
difference described above.</p>
<ul>
<li>What is your conclusion?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="in-class-exercises-6.html#cb311-1" tabindex="-1"></a><span class="do">## Estimate the model with the latent means equated:</span></span>
<span id="cb311-2"><a href="in-class-exercises-6.html#cb311-2" tabindex="-1"></a>resOut <span class="ot">&lt;-</span> <span class="fu">cfa</span>(cfaMod,</span>
<span id="cb311-3"><a href="in-class-exercises-6.html#cb311-3" tabindex="-1"></a>              <span class="at">data =</span> pgd,</span>
<span id="cb311-4"><a href="in-class-exercises-6.html#cb311-4" tabindex="-1"></a>              <span class="at">group =</span> <span class="st">&quot;Kin2&quot;</span>,</span>
<span id="cb311-5"><a href="in-class-exercises-6.html#cb311-5" tabindex="-1"></a>              <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;intercepts&quot;</span>, <span class="st">&quot;means&quot;</span>)</span>
<span id="cb311-6"><a href="in-class-exercises-6.html#cb311-6" tabindex="-1"></a>              )</span>
<span id="cb311-7"><a href="in-class-exercises-6.html#cb311-7" tabindex="-1"></a></span>
<span id="cb311-8"><a href="in-class-exercises-6.html#cb311-8" tabindex="-1"></a><span class="do">## Check the results:</span></span>
<span id="cb311-9"><a href="in-class-exercises-6.html#cb311-9" tabindex="-1"></a><span class="fu">summary</span>(resOut)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 24 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        30
##   Number of equality constraints                     9
## 
##   Number of observations per group:               Used       Total
##     0                                              188         190
##     1                                              379         379
## 
## Model Test User Model:
##                                                       
##   Test statistic                                27.615
##   Degrees of freedom                                19
##   P-value (Chi-square)                           0.091
##   Test statistic for each group:
##     0                                           19.755
##     1                                            7.860
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2  (.p2.)    0.451    0.043   10.591    0.000
##     b3pss3  (.p3.)    0.824    0.057   14.450    0.000
##     b4pss4  (.p4.)    0.759    0.054   13.976    0.000
##     b5pss5  (.p5.)    0.804    0.056   14.448    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1  (.12.)    1.234    0.042   29.668    0.000
##    .b2pss2  (.13.)    0.461    0.029   15.988    0.000
##    .b3pss3  (.14.)    0.974    0.038   25.664    0.000
##    .b4pss4  (.15.)    1.006    0.036   27.699    0.000
##    .b5pss5  (.16.)    0.676    0.037   18.267    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.436    0.064    6.770    0.000
##    .b2pss2            0.331    0.037    8.925    0.000
##    .b3pss3            0.448    0.058    7.767    0.000
##    .b4pss4            0.482    0.059    8.194    0.000
##    .b5pss5            0.538    0.066    8.197    0.000
##     grief             0.588    0.088    6.714    0.000
## 
## 
## Group 2 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   grief =~                                            
##     b1pss1            1.000                           
##     b2pss2  (.p2.)    0.451    0.043   10.591    0.000
##     b3pss3  (.p3.)    0.824    0.057   14.450    0.000
##     b4pss4  (.p4.)    0.759    0.054   13.976    0.000
##     b5pss5  (.p5.)    0.804    0.056   14.448    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1  (.12.)    1.234    0.042   29.668    0.000
##    .b2pss2  (.13.)    0.461    0.029   15.988    0.000
##    .b3pss3  (.14.)    0.974    0.038   25.664    0.000
##    .b4pss4  (.15.)    1.006    0.036   27.699    0.000
##    .b5pss5  (.16.)    0.676    0.037   18.267    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .b1pss1            0.399    0.042    9.469    0.000
##    .b2pss2            0.370    0.029   12.863    0.000
##    .b3pss3            0.419    0.038   11.012    0.000
##    .b4pss4            0.394    0.035   11.283    0.000
##    .b5pss5            0.361    0.034   10.691    0.000
##     grief             0.563    0.066    8.584    0.000</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="in-class-exercises-6.html#cb313-1" tabindex="-1"></a><span class="do">## Test the mean differences via a LRT:</span></span>
<span id="cb313-2"><a href="in-class-exercises-6.html#cb313-2" tabindex="-1"></a><span class="fu">anova</span>(strongOut, resOut)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Chisq diff"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["RMSEA"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Df diff"],"name":[7],"type":["int"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"18","2":"6469.378","3":"6564.866","4":"23.96850","5":"NA","6":"NA","7":"NA","8":"NA","_rn_":"strongOut"},{"1":"19","2":"6471.024","3":"6562.172","4":"27.61472","5":"3.646228","6":"0.09661335","7":"1","8":"0.05619634","_rn_":"resOut"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>We can equate the latent means by specifying the <code>group.equal = "means"</code>
argument in <code>cfa()</code>. Then, we simply compare this constrained model to the
strong invariance model to get our test of mean differences.</p>
<p>In this case, the means of the <code>grief</code> factor do not significantly differ between
<code>Kin2</code> groups (<span class="math inline">\(\Delta \chi^2[1] = 3.65\)</span>, <span class="math inline">\(p = 0.056\)</span>), assuming we
adopt an alpha-level of 0.05 or lower for the test.</p>
</details>
</details>
<hr />
</div>
</div>
<div id="multiple-group-sem-for-moderation" class="section level3 hasAnchor" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Multiple-Group SEM for Moderation<a href="in-class-exercises-6.html#multiple-group-sem-for-moderation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>Now, we’re going to revisit the TORA model from the
<a href="in-class-exercises-5.html">Week 6 In-Class Exercises</a>, and use a multiple-group
model to test the moderating effect of <em>sex</em>.</p>
<hr />
<div id="section-104" class="section level4" number="7.4.3.1">
<h4><span class="header-section-number">7.4.3.1</span> </h4>
<p>Load the data contained in the <em>toradata.csv</em> file.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="in-class-exercises-6.html#cb314-1" tabindex="-1"></a>condom <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;toradata.csv&quot;</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<hr />
<p>Before we get to any moderation tests, however, we first need to establish
measurement invariance. The first step in any multiple-group analysis that
includes latent variables is measurement invariance testing.</p>
<hr />
</div>
<div id="section-105" class="section level4" number="7.4.3.2">
<h4><span class="header-section-number">7.4.3.2</span> </h4>
<p>Test for measurement invariance across <em>sex</em> groups in the three latent variables
of the TORA model from <a href="in-class-exercises-5.html#toraCFA">6.4.2</a>.</p>
<ul>
<li>Test configural, weak, and strong invariance.</li>
<li>Test for invariance in all three latent factors simultaneously.</li>
<li>Is full measurement invariance (i.e., up to and including strong invariance)
supported?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="in-class-exercises-6.html#cb315-1" tabindex="-1"></a>tora_cfa <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb315-2"><a href="in-class-exercises-6.html#cb315-2" tabindex="-1"></a><span class="st">  attitudes =~ attit_1   + attit_2   + attit_3</span></span>
<span id="cb315-3"><a href="in-class-exercises-6.html#cb315-3" tabindex="-1"></a><span class="st">  norms     =~ norm_1    + norm_2    + norm_3</span></span>
<span id="cb315-4"><a href="in-class-exercises-6.html#cb315-4" tabindex="-1"></a><span class="st">  control   =~ control_1 + control_2 + control_3</span></span>
<span id="cb315-5"><a href="in-class-exercises-6.html#cb315-5" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb315-6"><a href="in-class-exercises-6.html#cb315-6" tabindex="-1"></a></span>
<span id="cb315-7"><a href="in-class-exercises-6.html#cb315-7" tabindex="-1"></a><span class="do">## Estimate the models:</span></span>
<span id="cb315-8"><a href="in-class-exercises-6.html#cb315-8" tabindex="-1"></a>config <span class="ot">&lt;-</span> <span class="fu">cfa</span>(tora_cfa, <span class="at">data =</span> condom, <span class="at">group =</span> <span class="st">&quot;sex&quot;</span>)</span>
<span id="cb315-9"><a href="in-class-exercises-6.html#cb315-9" tabindex="-1"></a>weak <span class="ot">&lt;-</span> <span class="fu">cfa</span>(tora_cfa, <span class="at">data =</span> condom, <span class="at">group =</span> <span class="st">&quot;sex&quot;</span>, <span class="at">group.equal =</span> <span class="st">&quot;loadings&quot;</span>)</span>
<span id="cb315-10"><a href="in-class-exercises-6.html#cb315-10" tabindex="-1"></a>strong <span class="ot">&lt;-</span> <span class="fu">cfa</span>(tora_cfa, </span>
<span id="cb315-11"><a href="in-class-exercises-6.html#cb315-11" tabindex="-1"></a>              <span class="at">data =</span> condom, </span>
<span id="cb315-12"><a href="in-class-exercises-6.html#cb315-12" tabindex="-1"></a>              <span class="at">group =</span> <span class="st">&quot;sex&quot;</span>,</span>
<span id="cb315-13"><a href="in-class-exercises-6.html#cb315-13" tabindex="-1"></a>              <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;intercepts&quot;</span>)</span>
<span id="cb315-14"><a href="in-class-exercises-6.html#cb315-14" tabindex="-1"></a>              )</span>
<span id="cb315-15"><a href="in-class-exercises-6.html#cb315-15" tabindex="-1"></a></span>
<span id="cb315-16"><a href="in-class-exercises-6.html#cb315-16" tabindex="-1"></a><span class="do">## Check that everything went well:</span></span>
<span id="cb315-17"><a href="in-class-exercises-6.html#cb315-17" tabindex="-1"></a><span class="fu">summary</span>(config)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 54 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        60
## 
##   Number of observations per group:                   
##     woman                                          161
##     man                                             89
## 
## Model Test User Model:
##                                                       
##   Test statistic                                66.565
##   Degrees of freedom                                48
##   P-value (Chi-square)                           0.039
##   Test statistic for each group:
##     woman                                       42.623
##     man                                         23.941
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [woman]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes =~                                        
##     attit_1           1.000                           
##     attit_2           1.005    0.075   13.427    0.000
##     attit_3          -0.965    0.075  -12.878    0.000
##   norms =~                                            
##     norm_1            1.000                           
##     norm_2            0.952    0.101    9.470    0.000
##     norm_3            0.879    0.101    8.742    0.000
##   control =~                                          
##     control_1         1.000                           
##     control_2         0.794    0.144    5.526    0.000
##     control_3         0.989    0.152    6.523    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes ~~                                        
##     norms             0.450    0.087    5.200    0.000
##     control           0.468    0.089    5.249    0.000
##   norms ~~                                            
##     control           0.387    0.079    4.912    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           2.839    0.090   31.702    0.000
##    .attit_2           2.907    0.084   34.728    0.000
##    .attit_3           3.174    0.084   37.969    0.000
##    .norm_1            2.832    0.080   35.342    0.000
##    .norm_2            2.832    0.079   35.775    0.000
##    .norm_3            2.795    0.081   34.694    0.000
##    .control_1         2.851    0.082   34.755    0.000
##    .control_2         2.857    0.081   35.104    0.000
##    .control_3         2.888    0.081   35.877    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           0.398    0.059    6.739    0.000
##    .attit_2           0.227    0.045    5.011    0.000
##    .attit_3           0.294    0.048    6.092    0.000
##    .norm_1            0.346    0.065    5.328    0.000
##    .norm_2            0.385    0.065    5.962    0.000
##    .norm_3            0.513    0.072    7.108    0.000
##    .control_1         0.587    0.090    6.531    0.000
##    .control_2         0.754    0.096    7.815    0.000
##    .control_3         0.557    0.086    6.453    0.000
##     attitudes         0.893    0.142    6.273    0.000
##     norms             0.688    0.121    5.706    0.000
##     control           0.497    0.119    4.184    0.000
## 
## 
## Group 2 [man]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes =~                                        
##     attit_1           1.000                           
##     attit_2           1.167    0.149    7.843    0.000
##     attit_3          -1.060    0.142   -7.443    0.000
##   norms =~                                            
##     norm_1            1.000                           
##     norm_2            1.070    0.215    4.965    0.000
##     norm_3            0.922    0.189    4.869    0.000
##   control =~                                          
##     control_1         1.000                           
##     control_2         0.995    0.290    3.435    0.001
##     control_3         0.949    0.285    3.332    0.001
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes ~~                                        
##     norms             0.086    0.103    0.837    0.403
##     control           0.388    0.113    3.430    0.001
##   norms ~~                                            
##     control           0.200    0.101    1.976    0.048
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           3.270    0.117   28.063    0.000
##    .attit_2           3.180    0.128   24.905    0.000
##    .attit_3           2.787    0.126   22.187    0.000
##    .norm_1            3.236    0.131   24.692    0.000
##    .norm_2            3.337    0.132   25.293    0.000
##    .norm_3            3.303    0.131   25.136    0.000
##    .control_1         3.157    0.111   28.415    0.000
##    .control_2         3.135    0.129   24.249    0.000
##    .control_3         3.213    0.130   24.805    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           0.440    0.095    4.631    0.000
##    .attit_2           0.405    0.109    3.699    0.000
##    .attit_3           0.541    0.112    4.822    0.000
##    .norm_1            0.740    0.175    4.230    0.000
##    .norm_2            0.647    0.182    3.555    0.000
##    .norm_3            0.868    0.175    4.972    0.000
##    .control_1         0.673    0.146    4.602    0.000
##    .control_2         1.066    0.197    5.417    0.000
##    .control_3         1.110    0.199    5.582    0.000
##     attitudes         0.768    0.182    4.220    0.000
##     norms             0.788    0.242    3.259    0.001
##     control           0.426    0.168    2.537    0.011</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="in-class-exercises-6.html#cb317-1" tabindex="-1"></a><span class="fu">summary</span>(weak)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 37 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        60
##   Number of equality constraints                     6
## 
##   Number of observations per group:                   
##     woman                                          161
##     man                                             89
## 
## Model Test User Model:
##                                                       
##   Test statistic                                68.557
##   Degrees of freedom                                54
##   P-value (Chi-square)                           0.088
##   Test statistic for each group:
##     woman                                       43.148
##     man                                         25.409
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [woman]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes =~                                        
##     attit_1           1.000                           
##     attit_2 (.p2.)    1.048    0.068   15.413    0.000
##     attit_3 (.p3.)   -0.995    0.067  -14.762    0.000
##   norms =~                                            
##     norm_1            1.000                           
##     norm_2  (.p5.)    0.977    0.091   10.708    0.000
##     norm_3  (.p6.)    0.889    0.089    9.996    0.000
##   control =~                                          
##     cntrl_1           1.000                           
##     cntrl_2 (.p8.)    0.843    0.130    6.506    0.000
##     cntrl_3 (.p9.)    0.983    0.135    7.306    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes ~~                                        
##     norms             0.431    0.082    5.256    0.000
##     control           0.450    0.083    5.395    0.000
##   norms ~~                                            
##     control           0.378    0.075    5.031    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           2.839    0.088   32.194    0.000
##    .attit_2           2.907    0.084   34.445    0.000
##    .attit_3           3.174    0.084   37.913    0.000
##    .norm_1            2.832    0.080   35.504    0.000
##    .norm_2            2.832    0.080   35.571    0.000
##    .norm_3            2.795    0.080   34.727    0.000
##    .control_1         2.851    0.082   34.882    0.000
##    .control_2         2.857    0.082   34.746    0.000
##    .control_3         2.888    0.080   36.037    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           0.408    0.058    6.987    0.000
##    .attit_2           0.221    0.045    4.896    0.000
##    .attit_3           0.293    0.048    6.128    0.000
##    .norm_1            0.353    0.063    5.580    0.000
##    .norm_2            0.380    0.064    5.952    0.000
##    .norm_3            0.512    0.071    7.178    0.000
##    .control_1         0.590    0.088    6.695    0.000
##    .control_2         0.744    0.096    7.731    0.000
##    .control_3         0.565    0.085    6.663    0.000
##     attitudes         0.844    0.129    6.540    0.000
##     norms             0.672    0.113    5.921    0.000
##     control           0.485    0.110    4.417    0.000
## 
## 
## Group 2 [man]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes =~                                        
##     attit_1           1.000                           
##     attit_2 (.p2.)    1.048    0.068   15.413    0.000
##     attit_3 (.p3.)   -0.995    0.067  -14.762    0.000
##   norms =~                                            
##     norm_1            1.000                           
##     norm_2  (.p5.)    0.977    0.091   10.708    0.000
##     norm_3  (.p6.)    0.889    0.089    9.996    0.000
##   control =~                                          
##     cntrl_1           1.000                           
##     cntrl_2 (.p8.)    0.843    0.130    6.506    0.000
##     cntrl_3 (.p9.)    0.983    0.135    7.306    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes ~~                                        
##     norms             0.092    0.114    0.807    0.420
##     control           0.425    0.109    3.912    0.000
##   norms ~~                                            
##     control           0.217    0.103    2.100    0.036
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           3.270    0.120   27.254    0.000
##    .attit_2           3.180    0.125   25.501    0.000
##    .attit_3           2.787    0.125   22.275    0.000
##    .norm_1            3.236    0.132   24.423    0.000
##    .norm_2            3.337    0.130   25.610    0.000
##    .norm_3            3.303    0.132   25.086    0.000
##    .control_1         3.157    0.112   28.208    0.000
##    .control_2         3.135    0.127   24.750    0.000
##    .control_3         3.213    0.131   24.540    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           0.419    0.093    4.528    0.000
##    .attit_2           0.438    0.099    4.436    0.000
##    .attit_3           0.540    0.107    5.057    0.000
##    .norm_1            0.704    0.158    4.456    0.000
##    .norm_2            0.692    0.153    4.520    0.000
##    .norm_3            0.864    0.164    5.271    0.000
##    .control_1         0.668    0.139    4.797    0.000
##    .control_2         1.110    0.186    5.960    0.000
##    .control_3         1.094    0.193    5.663    0.000
##     attitudes         0.862    0.166    5.200    0.000
##     norms             0.859    0.193    4.443    0.000
##     control           0.447    0.137    3.260    0.001</code></pre>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="in-class-exercises-6.html#cb319-1" tabindex="-1"></a><span class="fu">summary</span>(strong)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 60 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        63
##   Number of equality constraints                    15
## 
##   Number of observations per group:                   
##     woman                                          161
##     man                                             89
## 
## Model Test User Model:
##                                                       
##   Test statistic                                72.050
##   Degrees of freedom                                60
##   P-value (Chi-square)                           0.137
##   Test statistic for each group:
##     woman                                       43.961
##     man                                         28.089
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [woman]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes =~                                        
##     attit_1           1.000                           
##     attit_2 (.p2.)    1.028    0.065   15.693    0.000
##     attit_3 (.p3.)   -0.990    0.065  -15.114    0.000
##   norms =~                                            
##     norm_1            1.000                           
##     norm_2  (.p5.)    0.998    0.089   11.182    0.000
##     norm_3  (.p6.)    0.918    0.088   10.467    0.000
##   control =~                                          
##     cntrl_1           1.000                           
##     cntrl_2 (.p8.)    0.848    0.126    6.736    0.000
##     cntrl_3 (.p9.)    0.987    0.131    7.558    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes ~~                                        
##     norms             0.428    0.081    5.259    0.000
##     control           0.454    0.084    5.438    0.000
##   norms ~~                                            
##     control           0.372    0.073    5.060    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1 (.25.)    2.864    0.085   33.535    0.000
##    .attit_2 (.26.)    2.887    0.083   34.826    0.000
##    .attit_3 (.27.)    3.166    0.082   38.500    0.000
##    .norm_1  (.28.)    2.816    0.078   36.330    0.000
##    .norm_2  (.29.)    2.838    0.078   36.453    0.000
##    .norm_3  (.30.)    2.812    0.078   36.253    0.000
##    .cntrl_1 (.31.)    2.847    0.078   36.562    0.000
##    .cntrl_2 (.32.)    2.859    0.076   37.381    0.000
##    .cntrl_3 (.33.)    2.891    0.077   37.531    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           0.405    0.058    6.931    0.000
##    .attit_2           0.226    0.045    5.051    0.000
##    .attit_3           0.291    0.048    6.084    0.000
##    .norm_1            0.362    0.062    5.795    0.000
##    .norm_2            0.377    0.064    5.931    0.000
##    .norm_3            0.506    0.071    7.109    0.000
##    .control_1         0.592    0.088    6.743    0.000
##    .control_2         0.743    0.096    7.739    0.000
##    .control_3         0.566    0.085    6.684    0.000
##     attitudes         0.861    0.130    6.607    0.000
##     norms             0.650    0.109    5.950    0.000
##     control           0.482    0.108    4.477    0.000
## 
## 
## Group 2 [man]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes =~                                        
##     attit_1           1.000                           
##     attit_2 (.p2.)    1.028    0.065   15.693    0.000
##     attit_3 (.p3.)   -0.990    0.065  -15.114    0.000
##   norms =~                                            
##     norm_1            1.000                           
##     norm_2  (.p5.)    0.998    0.089   11.182    0.000
##     norm_3  (.p6.)    0.918    0.088   10.467    0.000
##   control =~                                          
##     cntrl_1           1.000                           
##     cntrl_2 (.p8.)    0.848    0.126    6.736    0.000
##     cntrl_3 (.p9.)    0.987    0.131    7.558    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   attitudes ~~                                        
##     norms             0.093    0.113    0.825    0.409
##     control           0.428    0.109    3.926    0.000
##   norms ~~                                            
##     control           0.213    0.101    2.102    0.036
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1 (.25.)    2.864    0.085   33.535    0.000
##    .attit_2 (.26.)    2.887    0.083   34.826    0.000
##    .attit_3 (.27.)    3.166    0.082   38.500    0.000
##    .norm_1  (.28.)    2.816    0.078   36.330    0.000
##    .norm_2  (.29.)    2.838    0.078   36.453    0.000
##    .norm_3  (.30.)    2.812    0.078   36.253    0.000
##    .cntrl_1 (.31.)    2.847    0.078   36.562    0.000
##    .cntrl_2 (.32.)    2.859    0.076   37.381    0.000
##    .cntrl_3 (.33.)    2.891    0.077   37.531    0.000
##     attitds           0.356    0.133    2.680    0.007
##     norms             0.480    0.133    3.602    0.000
##     control           0.318    0.116    2.733    0.006
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .attit_1           0.420    0.094    4.484    0.000
##    .attit_2           0.456    0.100    4.557    0.000
##    .attit_3           0.537    0.107    5.023    0.000
##    .norm_1            0.724    0.157    4.599    0.000
##    .norm_2            0.686    0.153    4.489    0.000
##    .norm_3            0.859    0.165    5.220    0.000
##    .control_1         0.669    0.139    4.821    0.000
##    .control_2         1.109    0.186    5.958    0.000
##    .control_3         1.094    0.193    5.664    0.000
##     attitudes         0.872    0.167    5.214    0.000
##     norms             0.830    0.186    4.455    0.000
##     control           0.445    0.136    3.280    0.001</code></pre>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="in-class-exercises-6.html#cb321-1" tabindex="-1"></a><span class="do">## Test measurement invariance:</span></span>
<span id="cb321-2"><a href="in-class-exercises-6.html#cb321-2" tabindex="-1"></a><span class="fu">compareFit</span>(config, weak, strong) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## ################### Nested Model Comparison #########################
## 
## Chi-Squared Difference Test
## 
##        Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
## config 48 6021.5 6232.8 66.565                                    
## weak   54 6011.5 6201.6 68.557     1.9924     0       6     0.9204
## strong 60 6003.0 6172.0 72.050     3.4934     0       6     0.7448
## 
## ####################### Model Fit Indices ###########################
##          chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
## config 66.565† 48   .039 .056  .979  .968  .048† 6021.476  6232.764 
## weak   68.557  54   .088 .046  .983  .978  .050  6011.469  6201.628 
## strong 72.050  60   .137 .040† .986† .983† .051  6002.962† 6171.992†
## 
## ################## Differences in Fit Indices #######################
##               df  rmsea   cfi   tli  srmr     aic     bic
## weak - config  6 -0.009 0.005 0.010 0.003 -10.008 -31.136
## strong - weak  6 -0.006 0.003 0.006 0.001  -8.507 -29.635</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>Yes, we can establish full measurement invariance.</p>
<ul>
<li>Configural invariance holds.
<ul>
<li>The unrestricted, multiple-group model fits the data well
(<span class="math inline">\(\chi^2[48] = 66.56\)</span>,
<span class="math inline">\(p = 0.039\)</span>,
<span class="math inline">\(\textit{RMSEA} = 0.056\)</span>,
<span class="math inline">\(\textit{CFI} = 0.979\)</span>,
<span class="math inline">\(\textit{SRMR} = 0.048\)</span>).</li>
</ul></li>
<li>Weak invariance holds.
<ul>
<li>The model comparison test shows a non-significant loss of fit between the
configural and weak models (<span class="math inline">\(\Delta \chi^2[6] = 1.99\)</span>, <span class="math inline">\(p = 0.92\)</span>).</li>
</ul></li>
<li>Strong invariance holds.
<ul>
<li>The model comparison test shows a non-significant loss of fit between the
weak and strong models (<span class="math inline">\(\Delta \chi^2[6] = 3.49\)</span>, <span class="math inline">\(p = 0.745\)</span>).</li>
<li>The strongly invariant model still fits the data well
(<span class="math inline">\(\chi^2[60] = 72.05\)</span>,
<span class="math inline">\(p = 0.137\)</span>,
<span class="math inline">\(\textit{RMSEA} = 0.04\)</span>,
<span class="math inline">\(\textit{CFI} = 0.986\)</span>,
<span class="math inline">\(\textit{SRMR} = 0.051\)</span>).</li>
</ul>
</details></li>
</ul>
</details>
<hr />
<p>Once we’ve established measurement invariance, we can move on to testing
hypotheses about between-group differences secure in the knowledge that our
latent factors represent the same hypothetical constructs in all groups.</p>
<hr />
</div>
<div id="toraFullModel" class="section level4" number="7.4.3.3">
<h4><span class="header-section-number">7.4.3.3</span> </h4>
<p>Estimate the full TORA model from <a href="in-class-exercises-5.html#updatedModel">6.4.4</a> as a multiple-group model.</p>
<ul>
<li>Use <code>sex</code> as the grouping variables.</li>
<li>Keep the strong invariance constraints in place.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="in-class-exercises-6.html#cb323-1" tabindex="-1"></a><span class="do">## Add the structural paths to the model:</span></span>
<span id="cb323-2"><a href="in-class-exercises-6.html#cb323-2" tabindex="-1"></a>tora_sem <span class="ot">&lt;-</span> <span class="fu">paste</span>(tora_cfa,</span>
<span id="cb323-3"><a href="in-class-exercises-6.html#cb323-3" tabindex="-1"></a>                  <span class="st">&#39;intent ~ attitudes + norms</span></span>
<span id="cb323-4"><a href="in-class-exercises-6.html#cb323-4" tabindex="-1"></a><span class="st">                   behavior ~ intent + control&#39;</span>,</span>
<span id="cb323-5"><a href="in-class-exercises-6.html#cb323-5" tabindex="-1"></a>                  <span class="at">sep =</span> <span class="st">&#39;</span><span class="sc">\n</span><span class="st">&#39;</span>)</span>
<span id="cb323-6"><a href="in-class-exercises-6.html#cb323-6" tabindex="-1"></a></span>
<span id="cb323-7"><a href="in-class-exercises-6.html#cb323-7" tabindex="-1"></a><span class="do">## Estimate the model:</span></span>
<span id="cb323-8"><a href="in-class-exercises-6.html#cb323-8" tabindex="-1"></a>toraOut <span class="ot">&lt;-</span> <span class="fu">sem</span>(tora_sem, </span>
<span id="cb323-9"><a href="in-class-exercises-6.html#cb323-9" tabindex="-1"></a>               <span class="at">data =</span> condom, </span>
<span id="cb323-10"><a href="in-class-exercises-6.html#cb323-10" tabindex="-1"></a>               <span class="at">group =</span> <span class="st">&quot;sex&quot;</span>, </span>
<span id="cb323-11"><a href="in-class-exercises-6.html#cb323-11" tabindex="-1"></a>               <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;intercepts&quot;</span>)</span>
<span id="cb323-12"><a href="in-class-exercises-6.html#cb323-12" tabindex="-1"></a>               )</span>
<span id="cb323-13"><a href="in-class-exercises-6.html#cb323-13" tabindex="-1"></a></span>
<span id="cb323-14"><a href="in-class-exercises-6.html#cb323-14" tabindex="-1"></a><span class="do">## Check the results:</span></span>
<span id="cb323-15"><a href="in-class-exercises-6.html#cb323-15" tabindex="-1"></a><span class="fu">summary</span>(toraOut, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 62 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        79
##   Number of equality constraints                    17
## 
##   Number of observations per group:                   
##     woman                                          161
##     man                                             89
## 
## Model Test User Model:
##                                                       
##   Test statistic                               141.903
##   Degrees of freedom                                92
##   P-value (Chi-square)                           0.001
##   Test statistic for each group:
##     woman                                       83.870
##     man                                         58.033
## 
## Model Test Baseline Model:
## 
##   Test statistic                              1378.913
##   Degrees of freedom                               110
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.961
##   Tucker-Lewis Index (TLI)                       0.953
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -3470.878
##   Loglikelihood unrestricted model (H1)      -3399.927
##                                                       
##   Akaike (AIC)                                7065.756
##   Bayesian (BIC)                              7284.087
##   Sample-size adjusted Bayesian (SABIC)       7087.541
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.066
##   90 Percent confidence interval - lower         0.043
##   90 Percent confidence interval - upper         0.087
##   P-value H_0: RMSEA &lt;= 0.050                    0.114
##   P-value H_0: RMSEA &gt;= 0.080                    0.137
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.058
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [woman]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes =~                                                          
##     attit_1           1.000                               0.919    0.816
##     attit_2 (.p2.)    1.023    0.066   15.495    0.000    0.940    0.877
##     attit_3 (.p3.)   -1.016    0.066  -15.434    0.000   -0.935   -0.884
##   norms =~                                                              
##     norm_1            1.000                               0.808    0.798
##     norm_2  (.p5.)    0.956    0.083   11.551    0.000    0.772    0.766
##     norm_3  (.p6.)    0.942    0.084   11.256    0.000    0.761    0.743
##   control =~                                                            
##     cntrl_1           1.000                               0.671    0.646
##     cntrl_2 (.p8.)    0.846    0.125    6.768    0.000    0.567    0.545
##     cntrl_3 (.p9.)    1.008    0.129    7.814    0.000    0.676    0.665
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   intent ~                                                              
##     attitudes         0.436    0.082    5.335    0.000    0.401    0.403
##     norms             0.598    0.100    6.008    0.000    0.483    0.486
##   behavior ~                                                            
##     intent            0.347    0.064    5.436    0.000    0.347    0.351
##     control           0.727    0.138    5.274    0.000    0.488    0.496
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes ~~                                                          
##     norms             0.425    0.081    5.262    0.000    0.572    0.572
##     control           0.464    0.082    5.634    0.000    0.752    0.752
##   norms ~~                                                              
##     control           0.386    0.073    5.320    0.000    0.712    0.712
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1 (.31.)    2.863    0.084   34.071    0.000    2.863    2.542
##    .attit_2 (.32.)    2.884    0.082   35.225    0.000    2.884    2.690
##    .attit_3 (.33.)    3.168    0.081   39.065    0.000    3.168    2.995
##    .norm_1  (.34.)    2.802    0.076   36.874    0.000    2.802    2.767
##    .norm_2  (.35.)    2.830    0.075   37.555    0.000    2.830    2.807
##    .norm_3  (.36.)    2.796    0.076   36.725    0.000    2.796    2.730
##    .cntrl_1 (.37.)    2.855    0.077   37.078    0.000    2.855    2.749
##    .cntrl_2 (.38.)    2.866    0.076   37.909    0.000    2.866    2.753
##    .cntrl_3 (.39.)    2.897    0.076   37.969    0.000    2.897    2.849
##    .intent  (.40.)    2.712    0.078   34.861    0.000    2.712    2.726
##    .behavir (.41.)    1.630    0.175    9.289    0.000    1.630    1.658
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1           0.423    0.059    7.172    0.000    0.423    0.333
##    .attit_2           0.266    0.045    5.879    0.000    0.266    0.231
##    .attit_3           0.246    0.043    5.671    0.000    0.246    0.219
##    .norm_1            0.372    0.060    6.230    0.000    0.372    0.363
##    .norm_2            0.420    0.062    6.760    0.000    0.420    0.413
##    .norm_3            0.469    0.066    7.063    0.000    0.469    0.448
##    .control_1         0.629    0.085    7.426    0.000    0.629    0.583
##    .control_2         0.762    0.094    8.088    0.000    0.762    0.703
##    .control_3         0.577    0.080    7.238    0.000    0.577    0.558
##    .intent            0.374    0.049    7.615    0.000    0.374    0.378
##    .behavior          0.391    0.052    7.486    0.000    0.391    0.404
##     attitudes         0.845    0.129    6.561    0.000    1.000    1.000
##     norms             0.653    0.108    6.048    0.000    1.000    1.000
##     control           0.450    0.101    4.457    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     attit_1           0.667
##     attit_2           0.769
##     attit_3           0.781
##     norm_1            0.637
##     norm_2            0.587
##     norm_3            0.552
##     control_1         0.417
##     control_2         0.297
##     control_3         0.442
##     intent            0.622
##     behavior          0.596
## 
## 
## Group 2 [man]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes =~                                                          
##     attit_1           1.000                               0.922    0.815
##     attit_2 (.p2.)    1.023    0.066   15.495    0.000    0.943    0.817
##     attit_3 (.p3.)   -1.016    0.066  -15.434    0.000   -0.937   -0.782
##   norms =~                                                              
##     norm_1            1.000                               0.875    0.723
##     norm_2  (.p5.)    0.956    0.083   11.551    0.000    0.837    0.679
##     norm_3  (.p6.)    0.942    0.084   11.256    0.000    0.825    0.667
##   control =~                                                            
##     cntrl_1           1.000                               0.663    0.631
##     cntrl_2 (.p8.)    0.846    0.125    6.768    0.000    0.561    0.467
##     cntrl_3 (.p9.)    1.008    0.129    7.814    0.000    0.668    0.540
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   intent ~                                                              
##     attitudes         0.535    0.097    5.497    0.000    0.494    0.446
##     norms             0.858    0.111    7.702    0.000    0.751    0.679
##   behavior ~                                                            
##     intent            0.613    0.060   10.188    0.000    0.613    0.706
##     control           0.007    0.159    0.045    0.964    0.005    0.005
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes ~~                                                          
##     norms             0.060    0.108    0.552    0.581    0.074    0.074
##     control           0.426    0.107    3.978    0.000    0.697    0.697
##   norms ~~                                                              
##     control           0.220    0.096    2.291    0.022    0.380    0.380
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1 (.31.)    2.863    0.084   34.071    0.000    2.863    2.531
##    .attit_2 (.32.)    2.884    0.082   35.225    0.000    2.884    2.499
##    .attit_3 (.33.)    3.168    0.081   39.065    0.000    3.168    2.645
##    .norm_1  (.34.)    2.802    0.076   36.874    0.000    2.802    2.314
##    .norm_2  (.35.)    2.830    0.075   37.555    0.000    2.830    2.296
##    .norm_3  (.36.)    2.796    0.076   36.725    0.000    2.796    2.261
##    .cntrl_1 (.37.)    2.855    0.077   37.078    0.000    2.855    2.719
##    .cntrl_2 (.38.)    2.866    0.076   37.909    0.000    2.866    2.385
##    .cntrl_3 (.39.)    2.897    0.076   37.969    0.000    2.897    2.344
##    .intent  (.40.)    2.712    0.078   34.861    0.000    2.712    2.450
##    .behavir (.41.)    1.630    0.175    9.289    0.000    1.630    1.696
##     attitds           0.369    0.130    2.834    0.005    0.400    0.400
##     norms             0.534    0.126    4.246    0.000    0.610    0.610
##     control           0.309    0.115    2.691    0.007    0.466    0.466
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1           0.430    0.091    4.710    0.000    0.430    0.336
##    .attit_2           0.443    0.094    4.691    0.000    0.443    0.333
##    .attit_3           0.556    0.108    5.130    0.000    0.556    0.388
##    .norm_1            0.699    0.137    5.088    0.000    0.699    0.477
##    .norm_2            0.819    0.150    5.457    0.000    0.819    0.539
##    .norm_3            0.849    0.153    5.538    0.000    0.849    0.555
##    .control_1         0.663    0.135    4.908    0.000    0.663    0.602
##    .control_2         1.130    0.187    6.025    0.000    1.130    0.782
##    .control_3         1.082    0.191    5.673    0.000    1.082    0.708
##    .intent            0.363    0.089    4.091    0.000    0.363    0.296
##    .behavior          0.460    0.069    6.671    0.000    0.460    0.498
##     attitudes         0.850    0.164    5.190    0.000    1.000    1.000
##     norms             0.766    0.171    4.495    0.000    1.000    1.000
##     control           0.440    0.133    3.301    0.001    1.000    1.000
## 
## R-Square:
##                    Estimate
##     attit_1           0.664
##     attit_2           0.667
##     attit_3           0.612
##     norm_1            0.523
##     norm_2            0.461
##     norm_3            0.445
##     control_1         0.398
##     control_2         0.218
##     control_3         0.292
##     intent            0.704
##     behavior          0.502</code></pre>
</details>
<hr />
</div>
<div id="section-106" class="section level4" number="7.4.3.4">
<h4><span class="header-section-number">7.4.3.4</span> </h4>
<p>Conduct an omnibus test to check if <code>sex</code> moderates any of the latent regression
paths in the model from <a href="in-class-exercises-6.html#toraFullModel">7.4.3.3</a>.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="in-class-exercises-6.html#cb325-1" tabindex="-1"></a><span class="do">## Estimate a restricted model wherein all latent regression paths are equated</span></span>
<span id="cb325-2"><a href="in-class-exercises-6.html#cb325-2" tabindex="-1"></a><span class="do">## across groups.</span></span>
<span id="cb325-3"><a href="in-class-exercises-6.html#cb325-3" tabindex="-1"></a>toraOut0 <span class="ot">&lt;-</span> <span class="fu">sem</span>(tora_sem, </span>
<span id="cb325-4"><a href="in-class-exercises-6.html#cb325-4" tabindex="-1"></a>                <span class="at">data =</span> condom, </span>
<span id="cb325-5"><a href="in-class-exercises-6.html#cb325-5" tabindex="-1"></a>                <span class="at">group =</span> <span class="st">&quot;sex&quot;</span>, </span>
<span id="cb325-6"><a href="in-class-exercises-6.html#cb325-6" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;intercepts&quot;</span>, <span class="st">&quot;regressions&quot;</span>)</span>
<span id="cb325-7"><a href="in-class-exercises-6.html#cb325-7" tabindex="-1"></a>                )</span>
<span id="cb325-8"><a href="in-class-exercises-6.html#cb325-8" tabindex="-1"></a></span>
<span id="cb325-9"><a href="in-class-exercises-6.html#cb325-9" tabindex="-1"></a><span class="do">## Test the constraints:</span></span>
<span id="cb325-10"><a href="in-class-exercises-6.html#cb325-10" tabindex="-1"></a><span class="fu">anova</span>(toraOut, toraOut0)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Chisq diff"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["RMSEA"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Df diff"],"name":[7],"type":["int"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"92","2":"7065.756","3":"7284.087","4":"141.9027","5":"NA","6":"NA","7":"NA","8":"NA","_rn_":"toraOut"},{"1":"96","2":"7110.616","3":"7314.860","4":"194.7621","5":"52.85934","6":"0.3125999","7":"4","8":"9.119284e-11","_rn_":"toraOut0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>We can equate the latent regressions by specifying the <code>group.equal = "regressions"</code>
argument in <code>sem()</code>. Then, we simply compare this constrained model to the
unconstrained model from <a href="in-class-exercises-6.html#toraFullModel">7.4.3.3</a> to get our test of moderation.</p>
<p>Equating all regression paths across groups produces a significant loss of fit
(<span class="math inline">\(\Delta \chi^2[4] = 52.86\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). Therefore, <em>sex</em> must
moderate at least some of these paths.</p>
</details>
</details>
<hr />
</div>
<div id="section-107" class="section level4" number="7.4.3.5">
<h4><span class="header-section-number">7.4.3.5</span> </h4>
<p>Conduct a two-parameter test to check if <code>sex</code> moderates the effects of <code>intent</code>
and <code>control</code> on <code>behavior</code>.</p>
<ul>
<li>Use the <code>lavTestWald()</code> function to conduct your test.</li>
<li>Keep only the weak invariance constraints when estimating the model.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="in-class-exercises-6.html#cb326-1" tabindex="-1"></a><span class="do">## Add the structural paths to the model and assign labels:</span></span>
<span id="cb326-2"><a href="in-class-exercises-6.html#cb326-2" tabindex="-1"></a>tora_sem <span class="ot">&lt;-</span> <span class="fu">paste</span>(tora_cfa,</span>
<span id="cb326-3"><a href="in-class-exercises-6.html#cb326-3" tabindex="-1"></a>                  <span class="st">&#39;intent ~ attitudes + norms</span></span>
<span id="cb326-4"><a href="in-class-exercises-6.html#cb326-4" tabindex="-1"></a><span class="st">                   behavior ~ c(b1f, b1m) * intent + c(b2f, b2m) * control&#39;</span>,</span>
<span id="cb326-5"><a href="in-class-exercises-6.html#cb326-5" tabindex="-1"></a>                  <span class="at">sep =</span> <span class="st">&#39;</span><span class="sc">\n</span><span class="st">&#39;</span>)</span>
<span id="cb326-6"><a href="in-class-exercises-6.html#cb326-6" tabindex="-1"></a></span>
<span id="cb326-7"><a href="in-class-exercises-6.html#cb326-7" tabindex="-1"></a><span class="do">## Estimate the model with weak invariance constraints:</span></span>
<span id="cb326-8"><a href="in-class-exercises-6.html#cb326-8" tabindex="-1"></a>toraOut <span class="ot">&lt;-</span> <span class="fu">sem</span>(tora_sem, <span class="at">data =</span> condom, <span class="at">group =</span> <span class="st">&quot;sex&quot;</span>, <span class="at">group.equal =</span> <span class="st">&quot;loadings&quot;</span>)</span>
<span id="cb326-9"><a href="in-class-exercises-6.html#cb326-9" tabindex="-1"></a></span>
<span id="cb326-10"><a href="in-class-exercises-6.html#cb326-10" tabindex="-1"></a><span class="do">## Check the results:</span></span>
<span id="cb326-11"><a href="in-class-exercises-6.html#cb326-11" tabindex="-1"></a><span class="fu">summary</span>(toraOut, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 60 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        76
##   Number of equality constraints                     6
## 
##   Number of observations per group:                   
##     woman                                          161
##     man                                             89
## 
## Model Test User Model:
##                                                       
##   Test statistic                               119.722
##   Degrees of freedom                                84
##   P-value (Chi-square)                           0.006
##   Test statistic for each group:
##     woman                                       76.908
##     man                                         42.814
## 
## Model Test Baseline Model:
## 
##   Test statistic                              1378.913
##   Degrees of freedom                               110
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.972
##   Tucker-Lewis Index (TLI)                       0.963
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -3459.788
##   Loglikelihood unrestricted model (H1)      -3399.927
##                                                       
##   Akaike (AIC)                                7059.576
##   Bayesian (BIC)                              7306.078
##   Sample-size adjusted Bayesian (SABIC)       7084.172
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.058
##   90 Percent confidence interval - lower         0.032
##   90 Percent confidence interval - upper         0.081
##   P-value H_0: RMSEA &lt;= 0.050                    0.272
##   P-value H_0: RMSEA &gt;= 0.080                    0.058
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.047
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## 
## Group 1 [woman]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes =~                                                          
##     attit_1           1.000                               0.909    0.813
##     attit_2 (.p2.)    1.047    0.069   15.249    0.000    0.951    0.882
##     attit_3 (.p3.)   -1.025    0.068  -15.075    0.000   -0.931   -0.882
##   norms =~                                                              
##     norm_1            1.000                               0.824    0.809
##     norm_2  (.p5.)    0.936    0.083   11.256    0.000    0.771    0.768
##     norm_3  (.p6.)    0.908    0.084   10.810    0.000    0.748    0.734
##   control =~                                                            
##     cntrl_1           1.000                               0.690    0.666
##     cntrl_2 (.p8.)    0.832    0.126    6.593    0.000    0.574    0.551
##     cntrl_3 (.p9.)    1.006    0.131    7.673    0.000    0.694    0.682
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   intent ~                                                              
##     attituds          0.441    0.083    5.294    0.000    0.400    0.403
##     norms             0.580    0.098    5.918    0.000    0.478    0.480
##   behavior ~                                                            
##     intent   (b1f)    0.531    0.074    7.127    0.000    0.531    0.524
##     control  (b2f)    0.490    0.130    3.767    0.000    0.338    0.336
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes ~~                                                          
##     norms             0.428    0.081    5.266    0.000    0.572    0.572
##     control           0.454    0.082    5.517    0.000    0.723    0.723
##   norms ~~                                                              
##     control           0.384    0.074    5.169    0.000    0.676    0.676
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1           2.839    0.088   32.237    0.000    2.839    2.541
##    .attit_2           2.907    0.085   34.191    0.000    2.907    2.695
##    .attit_3           3.174    0.083   38.126    0.000    3.174    3.005
##    .norm_1            2.832    0.080   35.280    0.000    2.832    2.780
##    .norm_2            2.832    0.079   35.765    0.000    2.832    2.819
##    .norm_3            2.795    0.080   34.787    0.000    2.795    2.742
##    .control_1         2.851    0.082   34.875    0.000    2.851    2.749
##    .control_2         2.857    0.082   34.813    0.000    2.857    2.744
##    .control_3         2.888    0.080   35.985    0.000    2.888    2.836
##    .intent            2.677    0.078   34.159    0.000    2.677    2.692
##    .behavior          1.107    0.207    5.338    0.000    1.107    1.098
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1           0.423    0.059    7.208    0.000    0.423    0.339
##    .attit_2           0.259    0.045    5.713    0.000    0.259    0.223
##    .attit_3           0.248    0.044    5.701    0.000    0.248    0.222
##    .norm_1            0.359    0.060    5.989    0.000    0.359    0.346
##    .norm_2            0.415    0.062    6.711    0.000    0.415    0.411
##    .norm_3            0.479    0.067    7.152    0.000    0.479    0.461
##    .control_1         0.599    0.085    7.027    0.000    0.599    0.557
##    .control_2         0.755    0.095    7.940    0.000    0.755    0.696
##    .control_3         0.555    0.081    6.822    0.000    0.555    0.535
##    .intent            0.382    0.050    7.657    0.000    0.382    0.386
##    .behavior          0.402    0.049    8.152    0.000    0.402    0.396
##     attitudes         0.825    0.127    6.495    0.000    1.000    1.000
##     norms             0.679    0.112    6.066    0.000    1.000    1.000
##     control           0.477    0.106    4.483    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     attit_1           0.661
##     attit_2           0.777
##     attit_3           0.778
##     norm_1            0.654
##     norm_2            0.589
##     norm_3            0.539
##     control_1         0.443
##     control_2         0.304
##     control_3         0.465
##     intent            0.614
##     behavior          0.604
## 
## 
## Group 2 [man]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes =~                                                          
##     attit_1           1.000                               0.921    0.812
##     attit_2 (.p2.)    1.047    0.069   15.249    0.000    0.964    0.831
##     attit_3 (.p3.)   -1.025    0.068  -15.075    0.000   -0.944   -0.787
##   norms =~                                                              
##     norm_1            1.000                               0.928    0.753
##     norm_2  (.p5.)    0.936    0.083   11.256    0.000    0.869    0.698
##     norm_3  (.p6.)    0.908    0.084   10.810    0.000    0.843    0.676
##   control =~                                                            
##     cntrl_1           1.000                               0.669    0.634
##     cntrl_2 (.p8.)    0.832    0.126    6.593    0.000    0.556    0.464
##     cntrl_3 (.p9.)    1.006    0.131    7.673    0.000    0.673    0.547
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   intent ~                                                              
##     attituds          0.501    0.098    5.134    0.000    0.462    0.432
##     norms             0.749    0.112    6.696    0.000    0.695    0.649
##   behavior ~                                                            
##     intent   (b1m)    0.344    0.086    4.005    0.000    0.344    0.453
##     control  (b2m)    0.307    0.168    1.830    0.067    0.205    0.253
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitudes ~~                                                          
##     norms             0.084    0.113    0.742    0.458    0.098    0.098
##     control           0.424    0.107    3.960    0.000    0.688    0.688
##   norms ~~                                                              
##     control           0.240    0.102    2.361    0.018    0.387    0.387
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1           3.270    0.120   27.179    0.000    3.270    2.881
##    .attit_2           3.180    0.123   25.848    0.000    3.180    2.740
##    .attit_3           2.787    0.127   21.900    0.000    2.787    2.321
##    .norm_1            3.236    0.131   24.790    0.000    3.236    2.628
##    .norm_2            3.337    0.132   25.309    0.000    3.337    2.683
##    .norm_3            3.303    0.132   24.992    0.000    3.303    2.649
##    .control_1         3.157    0.112   28.223    0.000    3.157    2.992
##    .control_2         3.135    0.127   24.653    0.000    3.135    2.613
##    .control_3         3.213    0.130   24.627    0.000    3.213    2.610
##    .intent            3.427    0.113   30.233    0.000    3.427    3.205
##    .behavior          2.607    0.303    8.614    0.000    2.607    3.211
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .attit_1           0.439    0.092    4.795    0.000    0.439    0.341
##    .attit_2           0.417    0.092    4.518    0.000    0.417    0.310
##    .attit_3           0.549    0.107    5.120    0.000    0.549    0.381
##    .norm_1            0.656    0.137    4.801    0.000    0.656    0.432
##    .norm_2            0.792    0.148    5.342    0.000    0.792    0.512
##    .norm_3            0.845    0.153    5.504    0.000    0.845    0.543
##    .control_1         0.666    0.134    4.955    0.000    0.666    0.598
##    .control_2         1.130    0.187    6.053    0.000    1.130    0.785
##    .control_3         1.063    0.187    5.669    0.000    1.063    0.701
##    .intent            0.385    0.086    4.471    0.000    0.385    0.337
##    .behavior          0.399    0.063    6.328    0.000    0.399    0.605
##     attitudes         0.849    0.164    5.174    0.000    1.000    1.000
##     norms             0.861    0.190    4.528    0.000    1.000    1.000
##     control           0.447    0.134    3.334    0.001    1.000    1.000
## 
## R-Square:
##                    Estimate
##     attit_1           0.659
##     attit_2           0.690
##     attit_3           0.619
##     norm_1            0.568
##     norm_2            0.488
##     norm_3            0.457
##     control_1         0.402
##     control_2         0.215
##     control_3         0.299
##     intent            0.663
##     behavior          0.395</code></pre>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="in-class-exercises-6.html#cb328-1" tabindex="-1"></a><span class="do">## Test for moderation:</span></span>
<span id="cb328-2"><a href="in-class-exercises-6.html#cb328-2" tabindex="-1"></a><span class="fu">lavTestWald</span>(toraOut, <span class="st">&quot;b1f == b1m; b2f == b2m&quot;</span>)</span></code></pre></div>
<pre><code>## $stat
## [1] 9.85773
## 
## $df
## [1] 2
## 
## $p.value
## [1] 0.00723471
## 
## $se
## [1] &quot;standard&quot;</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>The Wald test suggest significant moderation (<span class="math inline">\(\Delta \chi^2[2] = 9.86\)</span>,
<span class="math inline">\(p = 0.007\)</span>). Equating these two regression slopes across groups produces a
significant loss of fit. Therefore, <em>sex</em> must moderate one or both of these paths.</p>
</details>
</details>
<hr />
<p>End of In-Class Exercises</p>
<hr />

</div>
</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises-6.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="wrap-up.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"search": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
