<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.4 In-Class Exercises | Theory Construction and Statistical Modeling</title>
  <meta name="description" content="3.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="3.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises-2.html"/>
<link rel="next" href="efa.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">TCSM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reading-questions.html"><a href="reading-questions.html"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html"><i class="fa fa-check"></i>Weekly preparation</a>
<ul>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a></li>
<li class="chapter" data-level="" data-path="attendance.html"><a href="attendance.html"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html#submission"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html"><i class="fa fa-check"></i>Assignment 2: Confirmatory Factor Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html#evaluation-1"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html#submission-1"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html"><i class="fa fa-check"></i>Assignment 3: Full Structural Equation Model</a>
<ul>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#evaluation-2"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#results_format"><i class="fa fa-check"></i>Results</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html"><i class="fa fa-check"></i>Data</a>
<ul>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#coping-with-covid"><i class="fa fa-check"></i>Coping with Covid</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#feminist-perspectives-scale"><i class="fa fa-check"></i>Feminist Perspectives Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#hypersensitive-narcissism-scale-dirty-dozen"><i class="fa fa-check"></i>Hypersensitive Narcissism Scale &amp; Dirty Dozen</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#kentucky-inventory-of-mindfulness-skills"><i class="fa fa-check"></i>Kentucky Inventory of Mindfulness Skills</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#depression-anxiety-stress-scale"><i class="fa fa-check"></i>Depression Anxiety Stress Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#nomophobia"><i class="fa fa-check"></i>Nomophobia</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#recylced-water-acceptance"><i class="fa fa-check"></i>Recylced Water Acceptance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-3"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#group-assignments"><i class="fa fa-check"></i>Group Assignments</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#individual-assignment"><i class="fa fa-check"></i>Individual Assignment</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#resits"><i class="fa fa-check"></i>Resits</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#example-assignment"><i class="fa fa-check"></i>Example Assignment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html"><i class="fa fa-check"></i>Rules</a>
<ul>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#academic-integrity"><i class="fa fa-check"></i>Academic integrity</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#strict-stuff"><i class="fa fa-check"></i>Strict stuff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="at-home-exercises.html"><a href="at-home-exercises.html#visualizations-with-r"><i class="fa fa-check"></i><b>1.3.1</b> Visualizations with R</a></li>
<li class="chapter" data-level="1.3.2" data-path="at-home-exercises.html"><a href="at-home-exercises.html#programming-with-r"><i class="fa fa-check"></i><b>1.3.2</b> Programming with R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="in-class-exercises.html"><a href="in-class-exercises.html#viewing-data"><i class="fa fa-check"></i><b>1.4.1</b> Viewing Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="in-class-exercises.html"><a href="in-class-exercises.html#dissecting-data"><i class="fa fa-check"></i><b>1.4.2</b> Dissecting Data</a></li>
<li class="chapter" data-level="1.4.3" data-path="in-class-exercises.html"><a href="in-class-exercises.html#grouping-and-manipulating-data"><i class="fa fa-check"></i><b>1.4.3</b> Grouping and Manipulating Data</a></li>
<li class="chapter" data-level="1.4.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>1.4.4</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="1.4.5" data-path="in-class-exercises.html"><a href="in-class-exercises.html#visualizing-data"><i class="fa fa-check"></i><b>1.4.5</b> Visualizing Data</a></li>
<li class="chapter" data-level="1.4.6" data-path="in-class-exercises.html"><a href="in-class-exercises.html#tidying-data"><i class="fa fa-check"></i><b>1.4.6</b> Tidying Data</a></li>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.1</b> </a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.1</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.2</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.3</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.1</b> Mediation</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.2</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.1</b> Mediation</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.2</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="efa.html"><a href="efa.html"><i class="fa fa-check"></i><b>4</b> EFA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recording"><i class="fa fa-check"></i><b>4.1.1</b> Recording</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-1-1"><i class="fa fa-check"></i>Reference 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-1-1"><i class="fa fa-check"></i>Questions 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-2-1"><i class="fa fa-check"></i>Reference 2</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-2-1"><i class="fa fa-check"></i>Questions 2</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-44"><i class="fa fa-check"></i><b>4.3.1</b> </a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#run_pca"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#pcScores"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#trust_efa"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaAtt"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#factorScores"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
<li class="chapter" data-level="4.4.13" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.13</b> </a></li>
<li class="chapter" data-level="4.4.14" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-64"><i class="fa fa-check"></i><b>4.4.14</b> </a></li>
<li class="chapter" data-level="4.4.15" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-65"><i class="fa fa-check"></i><b>4.4.15</b> </a></li>
<li class="chapter" data-level="4.4.16" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaRegression"><i class="fa fa-check"></i><b>4.4.16</b> </a></li>
<li class="chapter" data-level="4.4.17" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-66"><i class="fa fa-check"></i><b>4.4.17</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa.html"><a href="cfa.html"><i class="fa fa-check"></i><b>5</b> CFA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lecture-4.html"><a href="lecture-4.html#recording-1"><i class="fa fa-check"></i><b>5.1.1</b> Recording</a></li>
<li class="chapter" data-level="5.1.2" data-path="lecture-4.html"><a href="lecture-4.html#slides-4"><i class="fa fa-check"></i><b>5.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-67"><i class="fa fa-check"></i><b>5.3.1</b> </a></li>
<li class="chapter" data-level="5.3.2" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#cfaSyntax"><i class="fa fa-check"></i><b>5.3.2</b> </a></li>
<li class="chapter" data-level="5.3.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-68"><i class="fa fa-check"></i><b>5.3.3</b> </a></li>
<li class="chapter" data-level="5.3.4" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-69"><i class="fa fa-check"></i><b>5.3.4</b> </a></li>
<li class="chapter" data-level="5.3.5" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-70"><i class="fa fa-check"></i><b>5.3.5</b> </a></li>
<li class="chapter" data-level="5.3.6" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-71"><i class="fa fa-check"></i><b>5.3.6</b> </a></li>
<li class="chapter" data-level="5.3.7" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-72"><i class="fa fa-check"></i><b>5.3.7</b> </a></li>
<li class="chapter" data-level="5.3.8" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-73"><i class="fa fa-check"></i><b>5.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-74"><i class="fa fa-check"></i><b>5.4.1</b> </a></li>
<li class="chapter" data-level="5.4.2" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt"><i class="fa fa-check"></i><b>5.4.2</b> </a></li>
<li class="chapter" data-level="5.4.3" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-75"><i class="fa fa-check"></i><b>5.4.3</b> </a></li>
<li class="chapter" data-level="5.4.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt1f"><i class="fa fa-check"></i><b>5.4.4</b> </a></li>
<li class="chapter" data-level="5.4.5" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#compare1f5f"><i class="fa fa-check"></i><b>5.4.5</b> </a></li>
<li class="chapter" data-level="5.4.6" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-76"><i class="fa fa-check"></i><b>5.4.6</b> </a></li>
<li class="chapter" data-level="5.4.7" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfa2nd"><i class="fa fa-check"></i><b>5.4.7</b> </a></li>
<li class="chapter" data-level="5.4.8" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-77"><i class="fa fa-check"></i><b>5.4.8</b> </a></li>
<li class="chapter" data-level="5.4.9" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-78"><i class="fa fa-check"></i><b>5.4.9</b> </a></li>
<li class="chapter" data-level="5.4.10" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-79"><i class="fa fa-check"></i><b>5.4.10</b> </a></li>
<li class="chapter" data-level="5.4.11" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-80"><i class="fa fa-check"></i><b>5.4.11</b> </a></li>
<li class="chapter" data-level="5.4.12" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-81"><i class="fa fa-check"></i><b>5.4.12</b> </a></li>
<li class="chapter" data-level="5.4.13" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-82"><i class="fa fa-check"></i><b>5.4.13</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>6</b> Full SEM</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>6.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="lecture-5.html"><a href="lecture-5.html#recording-2"><i class="fa fa-check"></i><b>6.1.1</b> Recording</a></li>
<li class="chapter" data-level="6.1.2" data-path="lecture-5.html"><a href="lecture-5.html#slides-5"><i class="fa fa-check"></i><b>6.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>6.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#reference-4"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#questions-4"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>6.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-83"><i class="fa fa-check"></i><b>6.3.1</b> </a></li>
<li class="chapter" data-level="6.3.2" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-84"><i class="fa fa-check"></i><b>6.3.2</b> </a></li>
<li class="chapter" data-level="6.3.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-85"><i class="fa fa-check"></i><b>6.3.3</b> </a></li>
<li class="chapter" data-level="6.3.4" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-86"><i class="fa fa-check"></i><b>6.3.4</b> </a></li>
<li class="chapter" data-level="6.3.5" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-87"><i class="fa fa-check"></i><b>6.3.5</b> </a></li>
<li class="chapter" data-level="6.3.6" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-88"><i class="fa fa-check"></i><b>6.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>6.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-89"><i class="fa fa-check"></i><b>6.4.1</b> </a></li>
<li class="chapter" data-level="6.4.2" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-90"><i class="fa fa-check"></i><b>6.4.2</b> </a></li>
<li class="chapter" data-level="6.4.3" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-91"><i class="fa fa-check"></i><b>6.4.3</b> </a></li>
<li class="chapter" data-level="6.4.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#updatedModel"><i class="fa fa-check"></i><b>6.4.4</b> </a></li>
<li class="chapter" data-level="6.4.5" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-92"><i class="fa fa-check"></i><b>6.4.5</b> </a></li>
<li class="chapter" data-level="6.4.6" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-93"><i class="fa fa-check"></i><b>6.4.6</b> </a></li>
<li class="chapter" data-level="6.4.7" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-94"><i class="fa fa-check"></i><b>6.4.7</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>7</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="lecture-6.html"><a href="lecture-6.html#recordings-3"><i class="fa fa-check"></i><b>7.1.1</b> Recordings</a></li>
<li class="chapter" data-level="7.1.2" data-path="lecture-6.html"><a href="lecture-6.html#slides-6"><i class="fa fa-check"></i><b>7.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgPathAnalysis"><i class="fa fa-check"></i><b>7.3.1</b> Multiple-Group Path Analysis</a></li>
<li class="chapter" data-level="7.3.2" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgCFA"><i class="fa fa-check"></i><b>7.3.2</b> Multiple-Group CFA</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="wrap-up.html"><a href="wrap-up.html"><i class="fa fa-check"></i><b>8</b> Wrap-Up</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Theory Construction and Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises-2" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> In-Class Exercises<a href="in-class-exercises-2.html#in-class-exercises-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
<div id="mediation-1" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Mediation<a href="in-class-exercises-2.html#mediation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>In this practical, we’ll go back to the data from the at-home exercises,
<em>SelfEsteem.sav</em>. Recall that these data comprise 143 observations of the
following variables.</p>
<ul>
<li><em>case</em>: Participant ID number</li>
<li><em>ParAtt</em>: Parental Attachment</li>
<li><em>PeerAtt</em>: Peer Attachment</li>
<li><em>Emp</em>: Empathy</li>
<li><em>ProSoc</em>: Prosocial behavior</li>
<li><em>Aggr</em>: Aggression</li>
<li><em>SelfEst</em>: Self-esteem</li>
</ul>
<p>When we last worked with the data, we built a model with one mediator (<em>Emp</em>),
creating indirect effects between our predictors <em>ParAtt</em> and <em>PeerAtt</em>, and our
outcome variable <em>SelfEst</em>. Below, you will estimate a more complex,
multiple-mediator model.</p>
<hr />
<div id="section-30" class="section level4" number="3.4.1.1">
<h4><span class="header-section-number">3.4.1.1</span> </h4>
<p>Load the data into the object <code>seData</code> using <code>haven::read_sav()</code></p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="in-class-exercises-2.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb82-2"><a href="in-class-exercises-2.html#cb82-2" aria-hidden="true" tabindex="-1"></a>seData <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;SelfEsteem.sav&quot;</span>)</span></code></pre></div>
</details>
<hr />
<p>For this analysis, we are interested in the (indirect) effects of parental and
peer attachment on self-esteem. Furthermore, we want to evaluate the mediating
roles of empathy and social behavior (i.e., prosocial behavior and aggression).</p>
<p>Specifically, we have the following hypotheses.</p>
<ol style="list-style-type: decimal">
<li>Better peer relationships will promote higher self-esteem via a three-step
indirect process.
<ol style="list-style-type: lower-alpha">
<li>Better peer relationships will increase empathy levels.</li>
<li>Higher empathy will increase prosocial behavior and decrease aggressive
behavior.</li>
<li>More prosocial behaviors and less aggressive behavior will both produce
higher self-esteem.</li>
</ol></li>
<li>Better relationships with parents directly increase self-esteem.</li>
</ol>
<hr />
<p>To evaluate these hypotheses, we will use <strong>lavaan</strong> to estimate the following
multiple mediator model as a path model.</p>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-82-1.png" width="672" />
<!-- ![](images/week5_home_full_model.png) --></p>
<hr />
</div>
<div id="w3csyntax" class="section level4" number="3.4.1.2">
<h4><span class="header-section-number">3.4.1.2</span> </h4>
<p>Specify the lavaan model syntax implied by the path diagram shown above.</p>
<ul>
<li>Save the resulting character string as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="in-class-exercises-2.html#cb83-1" aria-hidden="true" tabindex="-1"></a>mod0 <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb83-2"><a href="in-class-exercises-2.html#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="st">## Equation for outcome:</span></span>
<span id="cb83-3"><a href="in-class-exercises-2.html#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="st">SelfEst ~ ProSoc + Aggr + Emp + ParAtt + PeerAtt</span></span>
<span id="cb83-4"><a href="in-class-exercises-2.html#cb83-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-5"><a href="in-class-exercises-2.html#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="st">## Equations for stage 2 mediators:</span></span>
<span id="cb83-6"><a href="in-class-exercises-2.html#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="st">ProSoc ~ PeerAtt + ParAtt + Emp</span></span>
<span id="cb83-7"><a href="in-class-exercises-2.html#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="st">Aggr ~ PeerAtt + ParAtt + Emp</span></span>
<span id="cb83-8"><a href="in-class-exercises-2.html#cb83-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-9"><a href="in-class-exercises-2.html#cb83-9" aria-hidden="true" tabindex="-1"></a><span class="st">## Equation for stage 1 mediator:</span></span>
<span id="cb83-10"><a href="in-class-exercises-2.html#cb83-10" aria-hidden="true" tabindex="-1"></a><span class="st">Emp ~ ParAtt + PeerAtt</span></span>
<span id="cb83-11"><a href="in-class-exercises-2.html#cb83-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-12"><a href="in-class-exercises-2.html#cb83-12" aria-hidden="true" tabindex="-1"></a><span class="st">## Covariances:</span></span>
<span id="cb83-13"><a href="in-class-exercises-2.html#cb83-13" aria-hidden="true" tabindex="-1"></a><span class="st">ProSoc ~~ Aggr</span></span>
<span id="cb83-14"><a href="in-class-exercises-2.html#cb83-14" aria-hidden="true" tabindex="-1"></a><span class="st">ParAtt ~~ PeerAtt</span></span>
<span id="cb83-15"><a href="in-class-exercises-2.html#cb83-15" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="w3cfit" class="section level4" number="3.4.1.3">
<h4><span class="header-section-number">3.4.1.3</span> </h4>
<p>Use the <code>lavaan::sem()</code> function to estimate the model defined in <a href="in-class-exercises-2.html#w3csyntax">3.4.1.2</a>.</p>
<ul>
<li>Use the default settings in <code>sem()</code>.</li>
<li>Summarize the fitted model.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="in-class-exercises-2.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb84-2"><a href="in-class-exercises-2.html#cb84-2" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod0, <span class="at">data =</span> seData)</span>
<span id="cb84-3"><a href="in-class-exercises-2.html#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 16 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        21
## 
##   Number of observations                           143
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   SelfEst ~                                           
##     ProSoc            0.252    0.096    2.634    0.008
##     Aggr              0.185    0.085    2.172    0.030
##     Emp               0.143    0.098    1.460    0.144
##     ParAtt            0.244    0.078    3.133    0.002
##     PeerAtt           0.051    0.091    0.555    0.579
##   ProSoc ~                                            
##     PeerAtt          -0.037    0.080   -0.469    0.639
##     ParAtt            0.193    0.067    2.886    0.004
##     Emp               0.477    0.074    6.411    0.000
##   Aggr ~                                              
##     PeerAtt          -0.095    0.090   -1.055    0.291
##     ParAtt           -0.034    0.075   -0.454    0.650
##     Emp              -0.309    0.084   -3.697    0.000
##   Emp ~                                               
##     ParAtt            0.078    0.075    1.045    0.296
##     PeerAtt           0.306    0.086    3.557    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##  .ProSoc ~~                                           
##    .Aggr             -0.086    0.058   -1.476    0.140
##   ParAtt ~~                                           
##     PeerAtt           0.537    0.103    5.215    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .SelfEst           0.796    0.094    8.456    0.000
##    .ProSoc            0.618    0.073    8.456    0.000
##    .Aggr              0.777    0.092    8.456    0.000
##    .Emp               0.779    0.092    8.456    0.000
##     ParAtt            1.277    0.151    8.456    0.000
##     PeerAtt           0.963    0.114    8.456    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-31" class="section level4" number="3.4.1.4">
<h4><span class="header-section-number">3.4.1.4</span> </h4>
<p>Considering the parameter estimates from <a href="in-class-exercises-2.html#w3cfit">3.4.1.3</a>, what can you say about
the hypotheses?</p>
<details>
<summary>
Click for explanation
</summary>
<p>Notice that all of the hypotheses stated above are explicitly directional. Hence,
when evaluating the significance of the structural paths that speak to these
hypotheses, we should use one-tailed tests. We cannot ask <strong>lavaan</strong> to return
one-tailed p-values, but we have no need to do so. We can simply divide the
two-tailed p-values in half.</p>
<p>The significant direct effect of <code>ParAtt</code> on <code>SelfEst</code>
(<span class="math inline">\(\beta = 0.244\)</span>,
<span class="math inline">\(Z = 3.13\)</span>,
<span class="math inline">\(p = 0.001\)</span>) and the lack of a significant direct
effect of <code>PeerAtt</code> on <code>SelfEst</code> (<span class="math inline">\(\beta = 0.051\)</span>,
<span class="math inline">\(Z = 0.555\)</span>,
<span class="math inline">\(p = 0.29\)</span>) align with our hypotheses.</p>
<p>The remaining patterns of individual estimates also seem to conform to the
hypotheses (e.g., all of the individual paths comprising the indirect effects of
<code>PeerAtt</code> on <code>SelfEst</code> are significant). We cannot make any firm conclusions
until we actually estimate and test the indirect effects, though.</p>
</details>
<hr />
</div>
<div id="section-32" class="section level4" number="3.4.1.5">
<h4><span class="header-section-number">3.4.1.5</span> </h4>
<p>Modify the model syntax from <a href="in-class-exercises-2.html#w3csyntax">3.4.1.2</a> by adding definitions of the two
hypothesized IEs from <code>PeerAtt</code> to <code>SelfEst</code>.</p>
<details>
<summary>
Click to show code
</summary>
<p>You can use any labeling scheme that makes sense to you, but I recommend adopting
some kind of systematic rule. Here, I will label the individual estimates in
terms of the short variable names used in the path diagram above.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="in-class-exercises-2.html#cb86-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb86-2"><a href="in-class-exercises-2.html#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="st">## Equation for outcome:</span></span>
<span id="cb86-3"><a href="in-class-exercises-2.html#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="st">SelfEst ~ y_m21 * ProSoc + y_m22 * Aggr + Emp + ParAtt + PeerAtt</span></span>
<span id="cb86-4"><a href="in-class-exercises-2.html#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="in-class-exercises-2.html#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="st">## Equations for stage 2 mediators:</span></span>
<span id="cb86-6"><a href="in-class-exercises-2.html#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="st">ProSoc ~ m21_x2 * PeerAtt + ParAtt + m21_m1 * Emp</span></span>
<span id="cb86-7"><a href="in-class-exercises-2.html#cb86-7" aria-hidden="true" tabindex="-1"></a><span class="st">Aggr ~ m22_x2 * PeerAtt + ParAtt + m22_m1 * Emp</span></span>
<span id="cb86-8"><a href="in-class-exercises-2.html#cb86-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-9"><a href="in-class-exercises-2.html#cb86-9" aria-hidden="true" tabindex="-1"></a><span class="st">## Equation for stage 1 mediator:</span></span>
<span id="cb86-10"><a href="in-class-exercises-2.html#cb86-10" aria-hidden="true" tabindex="-1"></a><span class="st">Emp ~ ParAtt + m1_x2 * PeerAtt</span></span>
<span id="cb86-11"><a href="in-class-exercises-2.html#cb86-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-12"><a href="in-class-exercises-2.html#cb86-12" aria-hidden="true" tabindex="-1"></a><span class="st">## Covariances:</span></span>
<span id="cb86-13"><a href="in-class-exercises-2.html#cb86-13" aria-hidden="true" tabindex="-1"></a><span class="st">ProSoc ~~ Aggr</span></span>
<span id="cb86-14"><a href="in-class-exercises-2.html#cb86-14" aria-hidden="true" tabindex="-1"></a><span class="st">ParAtt ~~ PeerAtt</span></span>
<span id="cb86-15"><a href="in-class-exercises-2.html#cb86-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-16"><a href="in-class-exercises-2.html#cb86-16" aria-hidden="true" tabindex="-1"></a><span class="st">## Indirect effects:</span></span>
<span id="cb86-17"><a href="in-class-exercises-2.html#cb86-17" aria-hidden="true" tabindex="-1"></a><span class="st">ie_pro := m1_x2 * m21_m1 * y_m21</span></span>
<span id="cb86-18"><a href="in-class-exercises-2.html#cb86-18" aria-hidden="true" tabindex="-1"></a><span class="st">ie_agg := m1_x2 * m22_m1 * y_m22</span></span>
<span id="cb86-19"><a href="in-class-exercises-2.html#cb86-19" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="w3ctest" class="section level4" number="3.4.1.6">
<h4><span class="header-section-number">3.4.1.6</span> </h4>
<p>Use <code>lavaan::sem()</code> to estimate the model with the IEs defined.</p>
<ul>
<li>Use the default settings for <code>sem()</code>.</li>
<li>Are the hypothesized IEs significant according to the default tests?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="in-class-exercises-2.html#cb87-1" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> seData)</span>
<span id="cb87-2"><a href="in-class-exercises-2.html#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 16 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        21
## 
##   Number of observations                           143
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   SelfEst ~                                           
##     ProSoc  (y_21)    0.252    0.096    2.634    0.008
##     Aggr    (y_22)    0.185    0.085    2.172    0.030
##     Emp               0.143    0.098    1.460    0.144
##     ParAtt            0.244    0.078    3.133    0.002
##     PerAtt            0.051    0.091    0.555    0.579
##   ProSoc ~                                            
##     PerAtt (m21_2)   -0.037    0.080   -0.469    0.639
##     ParAtt            0.193    0.067    2.886    0.004
##     Emp    (m21_1)    0.477    0.074    6.411    0.000
##   Aggr ~                                              
##     PerAtt (m22_2)   -0.095    0.090   -1.055    0.291
##     ParAtt           -0.034    0.075   -0.454    0.650
##     Emp    (m22_1)   -0.309    0.084   -3.697    0.000
##   Emp ~                                               
##     ParAtt            0.078    0.075    1.045    0.296
##     PerAtt  (m1_2)    0.306    0.086    3.557    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##  .ProSoc ~~                                           
##    .Aggr             -0.086    0.058   -1.476    0.140
##   ParAtt ~~                                           
##     PeerAtt           0.537    0.103    5.215    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .SelfEst           0.796    0.094    8.456    0.000
##    .ProSoc            0.618    0.073    8.456    0.000
##    .Aggr              0.777    0.092    8.456    0.000
##    .Emp               0.779    0.092    8.456    0.000
##     ParAtt            1.277    0.151    8.456    0.000
##     PeerAtt           0.963    0.114    8.456    0.000
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ie_pro            0.037    0.018    2.010    0.044
##     ie_agg           -0.017    0.011   -1.657    0.098</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>The IE of <em>Peer Attachment</em> on <em>Self Esteem</em> through <em>Empathy</em> and <em>Prosocial
Behavior</em> is significant (<span class="math inline">\(\hat{\textit{IE}} = 0.037\)</span>,
<span class="math inline">\(Z = 2.01\)</span>, <span class="math inline">\(p = 0.022\)</span>), as is the
analogous IE through <em>Aggressive Behavior</em>
(<span class="math inline">\(\hat{\textit{IE}} = -0.017\)</span>,
<span class="math inline">\(Z = -1.66\)</span>, <span class="math inline">\(p = 0.049\)</span>). Though,
this latter effect is just barely significant at the <span class="math inline">\(\alpha = 0.05\)</span> level.</p>
</details>
</details>
<hr />
<p>The tests we used to evaluate the significance of the IEs in <a href="in-class-exercises-2.html#w3ctest">3.4.1.6</a> are
flawed because they assume normal sampling distributions for the IEs. However
the IEs are defined as products of multiple, normally distributed, regression
slopes. So the IEs themselves cannot be normally distributed (at least in finite
samples), and the results of the normal-theory significance tests may be
misleading.</p>
<p>To get an accurate test of the IEs, we should use <em>bootstrapping</em> to generate an
empirical sampling distribution for each IE. In <strong>lavaan</strong>, we implement
bootstrapping by specifying the <code>se = "bootstrap"</code> option in the fitting
function (i.e., the <code>cfa()</code> or <code>sem()</code> function) and specifying the number of
bootstrap samples via the <code>bootstrap</code> option.</p>
<p><strong><em>Workflow Tip</em></strong></p>
<p>To draw reliable conclusions from bootstrapped results, we need many
bootstrap samples (i.e., B &gt; 1000), but we must estimate the full model for each
of these samples, so the estimation can take a long time. To avoid too much
frustration, you should first estimate the model without bootstrapping to make
sure everything is specified correctly. Only after you are certain that your
code is correct do you want to run the full bootstrapped version.</p>
<hr />
</div>
<div id="w3cboot" class="section level4" number="3.4.1.7">
<h4><span class="header-section-number">3.4.1.7</span> </h4>
<p>Re-estimate the model from <a href="in-class-exercises-2.html#w3ctest">3.4.1.6</a> using 1000 bootstrap samples.</p>
<ul>
<li>Other than the <code>se</code> and <code>bootstrap</code> options, use the defaults.</li>
<li>Are the hypothesized IEs significant according to the bootstrap-based test
statistics?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="in-class-exercises-2.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Set a seed to get replicable bootstrap samples:</span></span>
<span id="cb89-2"><a href="in-class-exercises-2.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">235711</span>)</span>
<span id="cb89-3"><a href="in-class-exercises-2.html#cb89-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-4"><a href="in-class-exercises-2.html#cb89-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the model with bootstrapping:</span></span>
<span id="cb89-5"><a href="in-class-exercises-2.html#cb89-5" aria-hidden="true" tabindex="-1"></a>out_boot <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> seData, <span class="at">se =</span> <span class="st">&quot;bootstrap&quot;</span>, <span class="at">bootstrap =</span> <span class="dv">1000</span>)</span>
<span id="cb89-6"><a href="in-class-exercises-2.html#cb89-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-7"><a href="in-class-exercises-2.html#cb89-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Summarize the model:</span></span>
<span id="cb89-8"><a href="in-class-exercises-2.html#cb89-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out_boot)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 16 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        21
## 
##   Number of observations                           143
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                            Bootstrap
##   Number of requested bootstrap draws             1000
##   Number of successful bootstrap draws            1000
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   SelfEst ~                                           
##     ProSoc  (y_21)    0.252    0.100    2.529    0.011
##     Aggr    (y_22)    0.185    0.085    2.174    0.030
##     Emp               0.143    0.095    1.507    0.132
##     ParAtt            0.244    0.079    3.089    0.002
##     PerAtt            0.051    0.095    0.530    0.596
##   ProSoc ~                                            
##     PerAtt (m21_2)   -0.037    0.082   -0.456    0.648
##     ParAtt            0.193    0.068    2.831    0.005
##     Emp    (m21_1)    0.477    0.078    6.092    0.000
##   Aggr ~                                              
##     PerAtt (m22_2)   -0.095    0.087   -1.093    0.275
##     ParAtt           -0.034    0.076   -0.448    0.654
##     Emp    (m22_1)   -0.309    0.092   -3.356    0.001
##   Emp ~                                               
##     ParAtt            0.078    0.072    1.092    0.275
##     PerAtt  (m1_2)    0.306    0.079    3.896    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##  .ProSoc ~~                                           
##    .Aggr             -0.086    0.058   -1.493    0.135
##   ParAtt ~~                                           
##     PeerAtt           0.537    0.128    4.195    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .SelfEst           0.796    0.082    9.698    0.000
##    .ProSoc            0.618    0.068    9.114    0.000
##    .Aggr              0.777    0.104    7.476    0.000
##    .Emp               0.779    0.090    8.651    0.000
##     ParAtt            1.277    0.197    6.473    0.000
##     PeerAtt           0.963    0.105    9.203    0.000
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ie_pro            0.037    0.019    1.891    0.059
##     ie_agg           -0.017    0.011   -1.638    0.101</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>As with the normal-theory tests, the hypothesized IE of <em>Peer Attachment</em> on
<em>Self Esteem</em> was significant (<span class="math inline">\(\hat{\textit{IE}} = 0.037\)</span>,
<span class="math inline">\(Z = 1.89\)</span>,
<span class="math inline">\(p = 0.029\)</span>), but the IE of <em>Aggressive Behavior</em> has
crossed into nonsignificant territory
(<span class="math inline">\(\hat{\textit{IE}} = -0.017\)</span>,
<span class="math inline">\(Z = -1.64\)</span>,
<span class="math inline">\(p = 0.051\)</span>).</p>
<p><em>Note:</em> Bootstrapping is a stochastic method, so each run can provide different
results. Since the indirect effect of aggressive behavior is so close to the
critical value, you may come to a different conclusions vis-á-vis statistical
significance if you run this analysis with a different random number seed or a
different number of bootstrap samples.</p>
</details>
</details>
<hr />
<p>When you use the <code>summary()</code> function to summarize the bootstrapped model from
<a href="in-class-exercises-2.html#w3cboot">3.4.1.7</a>, the output will probably look pretty much the same as it did in
<a href="in-class-exercises-2.html#w3ctest">3.4.1.6</a>, but it’s not. The standard errors and test statistics in the
bootstrapped summary are derived from empirical sampling distributions, whereas
these values are based on an assumed normal sampling distribution in
<a href="in-class-exercises-2.html#w3ctest">3.4.1.6</a>.</p>
<p>The standard method of testing IEs with bootstrapping is to compute confidence
intervals (CIs) from the empirical sampling distribution of the IEs. In
<strong>lavaan</strong>, we can compute basic (percentile, 95%) CIs by adding the <code>ci = TRUE</code>
option to the <code>summary()</code> function. To evaluate our directional hypotheses at an
<span class="math inline">\(\alpha = 0.05\)</span> level, however, we need to compute 90% CIs. We can get more
control over the summary statistics (include the CIs) with the
<code>parameterEstimates()</code> function.</p>
<hr />
</div>
<div id="section-33" class="section level4" number="3.4.1.8">
<h4><span class="header-section-number">3.4.1.8</span> </h4>
<p>Check the documentation for <code>lavaan::parameterEstimates()</code>.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="in-class-exercises-2.html#cb91-1" aria-hidden="true" tabindex="-1"></a>?parameterEstimates</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-34" class="section level4" number="3.4.1.9">
<h4><span class="header-section-number">3.4.1.9</span> </h4>
<p>Use the <code>parameterEstimates()</code> function to compute bootstrapped CIs for the
hypothesized IEs.</p>
<ul>
<li>Compute percentile CIs.</li>
<li>Are the IEs significant according to the bootstrapped CIs?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="in-class-exercises-2.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(out_boot, <span class="at">ci =</span> <span class="cn">TRUE</span>, <span class="at">level =</span> <span class="fl">0.9</span>)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["lhs"],"name":[1],"type":["chr"],"align":["left"]},{"label":["op"],"name":[2],"type":["chr"],"align":["left"]},{"label":["rhs"],"name":[3],"type":["chr"],"align":["left"]},{"label":["label"],"name":[4],"type":["chr"],"align":["left"]},{"label":["est"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["se"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["z"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["pvalue"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["ci.lower"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["ci.upper"],"name":[10],"type":["dbl"],"align":["right"]}],"data":[{"1":"SelfEst","2":"~","3":"ProSoc","4":"y_m21","5":"0.25200921","6":"0.09963949","7":"2.5292102","8":"1.143196e-02","9":"0.078240770","10":"0.406909335"},{"1":"SelfEst","2":"~","3":"Aggr","4":"y_m22","5":"0.18525728","6":"0.08519934","7":"2.1743980","8":"2.967526e-02","9":"0.048696592","10":"0.330608640"},{"1":"SelfEst","2":"~","3":"Emp","4":"","5":"0.14323882","6":"0.09501828","7":"1.5074870","8":"1.316859e-01","9":"-0.009821063","10":"0.301494536"},{"1":"SelfEst","2":"~","3":"ParAtt","4":"","5":"0.24426409","6":"0.07906617","7":"3.0893630","8":"2.005862e-03","9":"0.111064552","10":"0.370537719"},{"1":"SelfEst","2":"~","3":"PeerAtt","4":"","5":"0.05057274","6":"0.09539926","7":"0.5301166","8":"5.960311e-01","9":"-0.117819122","10":"0.203412111"},{"1":"ProSoc","2":"~","3":"PeerAtt","4":"m21_x2","5":"-0.03743961","6":"0.08207241","7":"-0.4561778","8":"6.482622e-01","9":"-0.167288671","10":"0.105560640"},{"1":"ProSoc","2":"~","3":"ParAtt","4":"","5":"0.19267407","6":"0.06804978","7":"2.8313694","8":"4.634916e-03","9":"0.079964319","10":"0.295787284"},{"1":"ProSoc","2":"~","3":"Emp","4":"m21_m1","5":"0.47748439","6":"0.07837987","7":"6.0919264","8":"1.115599e-09","9":"0.343242250","10":"0.606249440"},{"1":"Aggr","2":"~","3":"PeerAtt","4":"m22_x2","5":"-0.09454515","6":"0.08652282","7":"-1.0927192","8":"2.745171e-01","9":"-0.225325182","10":"0.048949876"},{"1":"Aggr","2":"~","3":"ParAtt","4":"","5":"-0.03397870","6":"0.07591138","7":"-0.4476101","8":"6.544346e-01","9":"-0.165991422","10":"0.088036588"},{"1":"Aggr","2":"~","3":"Emp","4":"m22_m1","5":"-0.30878775","6":"0.09200262","7":"-3.3562931","8":"7.899481e-04","9":"-0.459702819","10":"-0.161096242"},{"1":"Emp","2":"~","3":"ParAtt","4":"","5":"0.07807473","6":"0.07150023","7":"1.0919507","8":"2.748548e-01","9":"-0.050603666","10":"0.188517449"},{"1":"Emp","2":"~","3":"PeerAtt","4":"m1_x2","5":"0.30581697","6":"0.07850092","7":"3.8957118","8":"9.791078e-05","9":"0.169833754","10":"0.434463188"},{"1":"ProSoc","2":"~~","3":"Aggr","4":"","5":"-0.08619117","6":"0.05771400","7":"-1.4934187","8":"1.353276e-01","9":"-0.179244977","10":"0.011231884"},{"1":"ParAtt","2":"~~","3":"PeerAtt","4":"","5":"0.53737654","6":"0.12809325","7":"4.1951979","8":"2.726335e-05","9":"0.323857572","10":"0.758577787"},{"1":"SelfEst","2":"~~","3":"SelfEst","4":"","5":"0.79618780","6":"0.08209715","7":"9.6981173","8":"0.000000e+00","9":"0.637887125","10":"0.908495254"},{"1":"ProSoc","2":"~~","3":"ProSoc","4":"","5":"0.61802926","6":"0.06781430","7":"9.1135536","8":"0.000000e+00","9":"0.489266898","10":"0.717211072"},{"1":"Aggr","2":"~~","3":"Aggr","4":"","5":"0.77720501","6":"0.10395973","7":"7.4760198","8":"7.660539e-14","9":"0.590913189","10":"0.932588725"},{"1":"Emp","2":"~~","3":"Emp","4":"","5":"0.77910040","6":"0.09005432","7":"8.6514493","8":"0.000000e+00","9":"0.618425792","10":"0.913945717"},{"1":"ParAtt","2":"~~","3":"ParAtt","4":"","5":"1.27669945","6":"0.19724327","7":"6.4727148","8":"9.625745e-11","9":"0.967138000","10":"1.626379871"},{"1":"PeerAtt","2":"~~","3":"PeerAtt","4":"","5":"0.96308503","6":"0.10464834","7":"9.2030608","8":"0.000000e+00","9":"0.789314475","10":"1.131509117"},{"1":"ie_pro","2":":=","3":"m1_x2*m21_m1*y_m21","4":"ie_pro","5":"0.03679910","6":"0.01946258","7":"1.8907621","8":"5.865611e-02","9":"0.008958209","10":"0.071529937"},{"1":"ie_agg","2":":=","3":"m1_x2*m22_m1*y_m22","4":"ie_agg","5":"-0.01749431","6":"0.01067788","7":"-1.6383700","8":"1.013445e-01","9":"-0.038636976","10":"-0.003329914"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>When evaluating a directional hypothesis with a CI, we only consider one of the
interval’s boundaries.</p>
<ul>
<li>For a hypothesized positive effect, we check only if the lower boundary is
greater than zero.</li>
<li>For a hypothesized negative effect, we check if the upper boundary is less
than zero.</li>
</ul>
<p>As with the previous tests, the IE of <em>Peer Attachment</em> on <em>Self Esteem</em>
through <em>Empathy</em> and <em>Prosocial Behavior</em> is significant
(<span class="math inline">\(\hat{\textit{IE}} = 0.037\)</span>,
<span class="math inline">\(95\% ~ CI = [0.009; \infty]\)</span>), but the analogous IE
through <em>Aggressive Behavior</em> is not quite significant
(<span class="math inline">\(\hat{\textit{IE}} = -0.017\)</span>,
<span class="math inline">\(95\% ~ CI = [-\infty; -0.003]\)</span>).</p>
</details>
</details>
<hr />
</div>
<div id="section-35" class="section level4" number="3.4.1.10">
<h4><span class="header-section-number">3.4.1.10</span> </h4>
<p>Based on the analyses you’ve conducted here, what do you conclude vis-à-vis the
original hypotheses?</p>
<details>
<summary>
Click for explanation
</summary>
<p>When using normal-theory tests, both hypothesized indirect effects between
<em>Peer Attachment</em> and <em>Self Esteem</em> were supported in that the IE through
<em>Empathy</em> and <em>Prosocial Behavior</em> as well as the IE through <em>Empathy</em> and
<em>Aggressive Behavior</em> were both significant. The hypothesized direct effect of
<em>Parent Attachment</em> on <em>Self Esteem</em> was also born out via a significant direct
effect in the model.</p>
<p>When testing the indirect effects with bootstrapping, however, the effect through
<em>Aggressive Behavior</em> was nonsignificant. Since bootstrapping gives a more
accurate test of the indirect effect, we should probably trust these results
more than the normal-theory results. We should not infer a significant indirect
effect of <em>Peer Attachment</em> on <em>Self Esteem</em> transmitted through <em>Empathy</em> and
<em>Aggressive Behavior</em>.</p>
<p>These results may not tell the whole story, though. We have not tested for
indirect effects between <em>Parent Attachment</em> and <em>Self Esteem</em>, and we have not
evaluated simpler indirect effects between <em>Peer Attachment</em> and <em>Self Esteem</em>
(e.g., <code>PeerAtt</code> <span class="math inline">\(\rightarrow\)</span> <code>Emp</code> <span class="math inline">\(\rightarrow\)</span> <code>SelfEst</code>).</p>
</details>
<hr />
</div>
</div>
<div id="moderation-1" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Moderation<a href="in-class-exercises-2.html#moderation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>We will first analyze a synthetic version of the <a href="https://doi.org/10.3886/ICPSR35348.v1"><em>Outlook on Life Survey</em></a>
data. The original data were collected in the United States in 2012 to measure,
among other things, attitudes about racial issues, opinions of the Federal
government, and beliefs about the future.</p>
<p>We will work with a synthesized subset of the original data. You can access
these synthetic data as <a href="https://github.com/kylelang/lavaan-e-learning/raw/main/5_moderation/data/outlook.rds"><em>outlook.rds</em></a>. This dataset comprises
2288 observations of the following 13 variables.</p>
<ul>
<li><code>d1:d3</code>: Three observed indicators of a construct measuring disillusionment
with the US Federal government.
<ul>
<li>Higher scores indicate more disillusionment</li>
</ul></li>
<li><code>s1:s4</code>: Four observed indicators of a construct measuring the perceived
achievability of material success.
<ul>
<li>Higher scores indicate greater perceived achievability</li>
</ul></li>
<li><code>progress</code>: A single item assessing perceived progress toward achieving the
“American Dream”
<ul>
<li>Higher scores indicate greater perceived progress</li>
</ul></li>
<li><code>merit</code>: A single item assessing endorsement of the meritocratic ideal that
hard work leads to success.
<ul>
<li>Higher scores indicate stronger endorsement of the meritocratic ideal</li>
</ul></li>
<li><code>lib2Con</code>: A single item assessing liberal-to-conservative orientation
<ul>
<li>Lower scores are more liberal, higher scores are more conservative</li>
</ul></li>
<li><code>party</code>: A four-level factor indicating self-reported political party affiliation</li>
<li><code>disillusion</code>: A scale score representing disillusionment with the US Federal
government
<ul>
<li>Created as the mean of <code>d1:d3</code></li>
</ul></li>
<li><code>success</code>: A scale score representing the perceived achievability of material
success
<ul>
<li>Created as the mean of <code>s1:s4</code></li>
</ul></li>
</ul>
<p>To satisfy the <a href="https://www.icpsr.umich.edu/web/pages/datamanagement/lifecycle/access.html">access and licensing</a> conditions under which the original
data are distributed, the data contained in <em>outlook.rds</em> were synthesized from
the original variables using the methods described by <a href="https://doi.org/10.3390/psych3040045">Volker and Vink (2021)</a>.
You can access the original data <a href="https://doi.org/10.3886/ICPSR35348.v1">here</a>, and you can access the code
used to process the data <a href="https://github.com/kylelang/lavaan-e-learning/blob/main/code/lab_prep/process_outlook_data.R">here</a>.</p>
<hr />
<div id="section-36" class="section level4" number="3.4.2.1">
<h4><span class="header-section-number">3.4.2.1</span> </h4>
<p>Read in the <code>outlook.rds</code> dataset.</p>
<p><em>Hint:</em> An RDS file is an R object that’s been saved to a file. To read in this
type of file, we use <code>readRDS()</code> from base R.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="in-class-exercises-2.html#cb93-1" aria-hidden="true" tabindex="-1"></a>outlook <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;outlook.rds&quot;</span>)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-37" class="section level4" number="3.4.2.2">
<h4><span class="header-section-number">3.4.2.2</span> </h4>
<p>Summarize the outlook data to get a sense of their characteristics.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="in-class-exercises-2.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(outlook)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["d1"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["d2"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["d3"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["s1"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["s2"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["s3"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["s4"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["progress"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["merit"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["lib2Con"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["party"],"name":[11],"type":["fct"],"align":["left"]},{"label":["disillusion"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["success"],"name":[13],"type":["dbl"],"align":["right"]}],"data":[{"1":"4","2":"4","3":"4","4":"3","5":"2","6":"3","7":"3","8":"8","9":"6","10":"5","11":"republican","12":"4.000000","13":"2.75","_rn_":"1"},{"1":"4","2":"2","3":"4","4":"3","5":"2","6":"2","7":"3","8":"4","9":"5","10":"6","11":"independent","12":"3.333333","13":"2.50","_rn_":"2"},{"1":"4","2":"4","3":"4","4":"4","5":"2","6":"4","7":"3","8":"6","9":"5","10":"4","11":"independent","12":"4.000000","13":"3.25","_rn_":"3"},{"1":"5","2":"4","3":"5","4":"2","5":"1","6":"1","7":"1","8":"1","9":"4","10":"1","11":"democrat","12":"4.666667","13":"1.25","_rn_":"4"},{"1":"5","2":"3","3":"4","4":"2","5":"1","6":"2","7":"2","8":"6","9":"3","10":"4","11":"democrat","12":"4.000000","13":"1.75","_rn_":"5"},{"1":"4","2":"5","3":"4","4":"2","5":"2","6":"1","7":"3","8":"5","9":"4","10":"4","11":"democrat","12":"4.333333","13":"2.00","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="in-class-exercises-2.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(outlook)</span></code></pre></div>
<pre><code>##        d1              d2              d3              s1       
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:2.000  
##  Median :4.000   Median :3.000   Median :4.000   Median :2.000  
##  Mean   :3.642   Mean   :3.218   Mean   :3.629   Mean   :2.288  
##  3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:3.000  
##  Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :4.000  
##        s2              s3              s4           progress     
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   : 1.000  
##  1st Qu.:1.000   1st Qu.:1.000   1st Qu.:2.000   1st Qu.: 5.000  
##  Median :2.000   Median :2.000   Median :2.000   Median : 7.000  
##  Mean   :1.922   Mean   :2.012   Mean   :2.469   Mean   : 6.432  
##  3rd Qu.:2.000   3rd Qu.:3.000   3rd Qu.:3.000   3rd Qu.: 8.000  
##  Max.   :4.000   Max.   :4.000   Max.   :4.000   Max.   :10.000  
##      merit          lib2Con              party       disillusion   
##  Min.   :1.000   Min.   :1.000   republican : 332   Min.   :1.000  
##  1st Qu.:4.000   1st Qu.:3.000   democrat   :1264   1st Qu.:3.000  
##  Median :5.000   Median :4.000   independent: 576   Median :3.667  
##  Mean   :4.826   Mean   :3.998   other      : 116   Mean   :3.497  
##  3rd Qu.:6.000   3rd Qu.:5.000                      3rd Qu.:4.000  
##  Max.   :7.000   Max.   :7.000                      Max.   :5.000  
##     success     
##  Min.   :1.000  
##  1st Qu.:1.750  
##  Median :2.000  
##  Mean   :2.173  
##  3rd Qu.:2.500  
##  Max.   :4.000</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="in-class-exercises-2.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(outlook)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2288 obs. of  13 variables:
##  $ d1         : num  4 4 4 5 5 4 5 4 4 4 ...
##  $ d2         : num  4 2 4 4 3 5 4 2 4 5 ...
##  $ d3         : num  4 4 4 5 4 4 4 3 3 4 ...
##  $ s1         : num  3 3 4 2 2 2 2 1 3 3 ...
##  $ s2         : num  2 2 2 1 1 2 1 1 2 2 ...
##  $ s3         : num  3 2 4 1 2 1 1 1 3 2 ...
##  $ s4         : num  3 3 3 1 2 3 3 2 2 2 ...
##  $ progress   : num  8 4 6 1 6 5 7 6 9 7 ...
##  $ merit      : num  6 5 5 4 3 4 2 5 5 5 ...
##  $ lib2Con    : num  5 6 4 1 4 4 4 4 4 5 ...
##  $ party      : Factor w/ 4 levels &quot;republican&quot;,&quot;democrat&quot;,..: 1 3 3 2 2 2 2 2 4 1 ...
##  $ disillusion: num  4 3.33 4 4.67 4 ...
##  $ success    : num  2.75 2.5 3.25 1.25 1.75 2 1.75 1.25 2.5 2.25 ...</code></pre>
</details>
<hr />
<p>We will first use OLS regression to estimate a model encoding the following relations:</p>
<ul>
<li>Belief in the achievability of success, <em>success</em>, predicts perceived progress
toward the American Dream, <em>progress</em>, as the focal effect.</li>
<li>Disillusionment with the US Federal government, <em>disillusion</em> moderates the
<em>success</em> <span class="math inline">\(\rightarrow\)</span> <em>progress</em> effect.</li>
<li>Placement on the liberal-to-conservative continuum, <em>lib2Con</em> is partialed out
as a covariate.</li>
</ul>
<hr />
</div>
<div id="section-38" class="section level4" number="3.4.2.3">
<h4><span class="header-section-number">3.4.2.3</span> </h4>
<p>Draw the conceptual path diagram for the model described above.</p>
<details>
<summary>
Click for explanation
</summary>
<p><img src="images/lab5_conceptual1.png" width="1334" /></p>
</details>
<hr />
</div>
<div id="section-39" class="section level4" number="3.4.2.4">
<h4><span class="header-section-number">3.4.2.4</span> </h4>
<p>Write out the regression equation necessary to evaluate the moderation
hypothesis described above.</p>
<details>
<summary>
Click for explanation
</summary>
<p><span class="math display">\[
Y_{progress} = \beta_0 + \beta_1 W_{lib2Con} + \beta_2 X_{success} + \beta_3 Z_{disillusion} + \beta_4 XZ + \varepsilon
\]</span></p>
</details>
<hr />
</div>
<div id="olsFit" class="section level4" number="3.4.2.5">
<h4><span class="header-section-number">3.4.2.5</span> </h4>
<p>Use <code>lm()</code> to estimate the moderated regression model via OLS regression.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="in-class-exercises-2.html#cb99-1" aria-hidden="true" tabindex="-1"></a>olsFit <span class="ot">&lt;-</span> <span class="fu">lm</span>(progress <span class="sc">~</span> lib2Con <span class="sc">+</span> success <span class="sc">*</span> disillusion, <span class="at">data =</span> outlook)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-40" class="section level4" number="3.4.2.6">
<h4><span class="header-section-number">3.4.2.6</span> </h4>
<p>Summarize the fitted model and interpret the results.</p>
<ul>
<li>Is the moderation hypothesis supported?</li>
<li>How does disillusionment level affect the focal effect?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="in-class-exercises-2.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(olsFit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = progress ~ lib2Con + success * disillusion, data = outlook)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.4315 -1.2525  0.1307  1.4369  5.6717 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          6.81128    0.62073  10.973  &lt; 2e-16 ***
## lib2Con              0.03052    0.03040   1.004   0.3155    
## success              0.42360    0.25853   1.638   0.1015    
## disillusion         -0.78002    0.16864  -4.625 3.95e-06 ***
## success:disillusion  0.17429    0.07273   2.396   0.0166 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.041 on 2283 degrees of freedom
## Multiple R-squared:  0.1385, Adjusted R-squared:  0.137 
## F-statistic: 91.74 on 4 and 2283 DF,  p-value: &lt; 2.2e-16</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>Yes, <em>disillusion</em> significantly moderates the relation between <em>success</em> and
<em>progress</em> (<span class="math inline">\(\beta = 0.174\)</span>, <span class="math inline">\(t[2283] = 2.396\)</span>, <span class="math inline">\(p = 0.017\)</span>) such that the
effect of <em>success</em> on <em>progress</em> increases as levels of <em>disillusion</em>
increase, after controlling for <em>lib2Con</em>.</p>
</details>
</details>
<hr />
<p>The <a href="https://cran.r-project.org/web/packages/rockchalk/index.html"><strong>rockchalk</strong></a> package contains some useful routines for probing
interactions estimated via <code>lm()</code>. Specifically, the <code>plotslopes()</code> function will
estimate and plot simple slopes, and the <code>testSlopes()</code> function tests the simple
slopes estimated by <code>plotSlopes()</code>.</p>
<hr />
</div>
<div id="ssOls" class="section level4" number="3.4.2.7">
<h4><span class="header-section-number">3.4.2.7</span> </h4>
<p>Probe the interaction.</p>
<ul>
<li>Use the <code>plotSlopes()</code> and <code>testSlopes()</code> functions from the <strong>rockchalk</strong>
package to conduct a simple slopes analysis for the model from <a href="in-class-exercises-2.html#olsFit">3.4.2.5</a>.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="in-class-exercises-2.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rockchalk)</span>
<span id="cb102-2"><a href="in-class-exercises-2.html#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="in-class-exercises-2.html#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate and plot simple slopes:</span></span>
<span id="cb102-4"><a href="in-class-exercises-2.html#cb102-4" aria-hidden="true" tabindex="-1"></a>psOut <span class="ot">&lt;-</span> <span class="fu">plotSlopes</span>(olsFit,</span>
<span id="cb102-5"><a href="in-class-exercises-2.html#cb102-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">plotx    =</span> <span class="st">&quot;success&quot;</span>, </span>
<span id="cb102-6"><a href="in-class-exercises-2.html#cb102-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">modx     =</span> <span class="st">&quot;disillusion&quot;</span>,</span>
<span id="cb102-7"><a href="in-class-exercises-2.html#cb102-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">modxVals =</span> <span class="st">&quot;std.dev&quot;</span>)</span></code></pre></div>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-100-1.png" width="672" /></p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="in-class-exercises-2.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test the simple slopes:</span></span>
<span id="cb103-2"><a href="in-class-exercises-2.html#cb103-2" aria-hidden="true" tabindex="-1"></a>tsOut <span class="ot">&lt;-</span> <span class="fu">testSlopes</span>(psOut)</span></code></pre></div>
<pre><code>## Values of disillusion OUTSIDE this interval:
##          lo          hi 
## -28.9332857   0.2672244 
## cause the slope of (b1 + b2*disillusion)success to be statistically significant</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="in-class-exercises-2.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="do">## View the results:</span></span>
<span id="cb105-2"><a href="in-class-exercises-2.html#cb105-2" aria-hidden="true" tabindex="-1"></a>tsOut<span class="sc">$</span>hypotests</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["\"disillusion\""],"name":[1],"type":["dbl"],"align":["right"]},{"label":["slope"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Std. Error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["t value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>|t|)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2.72","2":"0.8976759","3":"0.08320659","4":"10.78852","5":"1.678871e-26","_rn_":"(m-sd)"},{"1":"3.50","2":"1.0336252","3":"0.06467513","4":"15.98180","5":"1.397265e-54","_rn_":"(m)"},{"1":"4.28","2":"1.1695744","3":"0.08876398","4":"13.17623","5":"2.888389e-38","_rn_":"(m+sd)"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><em>Note:</em> The message printed by <code>testSlopes()</code> gives the boundaries of the
<em>Johnson-Neyman Region of Significance</em> <a href="http://www.worldcat.org/oclc/29082872">(Johnson &amp; Neyman, 1936)</a>.
Johnson-Neyman analysis is an alternative method of probing interactions that we
have not covered in this course. For more information, check out
<a href="https://doi.org/10.3102%2F10769986031004437">Preacher, et al. (2006)</a>.</p>
</details>
<hr />
<p>We will now use <strong>lavaan</strong> to estimate the moderated regression model from above
as a path analysis.</p>
<hr />
</div>
<div id="section-41" class="section level4" number="3.4.2.8">
<h4><span class="header-section-number">3.4.2.8</span> </h4>
<p>Define the model syntax for the path analytic version of the model described
above.</p>
<ul>
<li>Parameterize the model as in the OLS regression.</li>
<li>Use only observed items and scale scores.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="in-class-exercises-2.html#cb106-1" aria-hidden="true" tabindex="-1"></a>pathMod <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb106-2"><a href="in-class-exercises-2.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="st">progress ~ 1 + lib2Con + success + disillusion + success:disillusion</span></span>
<span id="cb106-3"><a href="in-class-exercises-2.html#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="pathFit" class="section level4" number="3.4.2.9">
<h4><span class="header-section-number">3.4.2.9</span> </h4>
<p>Estimate the path model on the outlook data.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="in-class-exercises-2.html#cb107-1" aria-hidden="true" tabindex="-1"></a>pathFit <span class="ot">&lt;-</span> <span class="fu">sem</span>(pathMod, <span class="at">data =</span> outlook)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-42" class="section level4" number="3.4.2.10">
<h4><span class="header-section-number">3.4.2.10</span> </h4>
<p>Summarize the fitted path model and interpret the results.</p>
<ul>
<li>Do the results match the OLS regression results?</li>
<li>What proportion of the variability in <em>progress</em> is explained by this model?</li>
</ul>
<p><em>Hint:</em> the function <code>lavInspect()</code> can be used to extract information from
models</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="in-class-exercises-2.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pathFit)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         6
## 
##   Number of observations                          2288
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   progress ~                                          
##     lib2Con           0.031    0.030    1.005    0.315
##     success           0.424    0.258    1.640    0.101
##     disillusion      -0.780    0.168   -4.630    0.000
##     success:dsllsn    0.174    0.073    2.399    0.016
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .progress          6.811    0.620   10.985    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .progress          4.157    0.123   33.823    0.000</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="in-class-exercises-2.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavInspect</span>(pathFit, <span class="st">&quot;r2&quot;</span>)</span></code></pre></div>
<pre><code>## progress 
##    0.138</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>Yes, the estimates and inferential conclusions are all the same as in the OLS
regression model. The model explains
13.85% of the variability in
<em>progress</em>.</p>
</details>
</details>
<hr />
<p>The <a href="https://cran.r-project.org/web/packages/semTools/index.html"><strong>semTools</strong></a> package contains some helpful routines for probing
interactions estimated via the <code>lavaan()</code> function (or one of it’s wrappers).
Specifically, the <code>probe2WayMC()</code> and <code>plotProbe()</code> functions will estimate/test
simple slopes and plot the estimated simple slopes, respectively.</p>
<hr />
</div>
<div id="section-43" class="section level4" number="3.4.2.11">
<h4><span class="header-section-number">3.4.2.11</span> </h4>
<p>Probe the interaction from <a href="in-class-exercises-2.html#pathFit">3.4.2.9</a> using <em>semTools</em> utilities.</p>
<ul>
<li>Use <code>probe2WayMC()</code> to estimate and test the simple slopes.</li>
<li>Use <code>plotProbe()</code> to visualize the simple slopes.</li>
<li>Define the simple slopes with the same conditional values of <em>disillusion</em>
that you used in <a href="in-class-exercises-2.html#ssOls">3.4.2.7</a>.</li>
<li>Which simple slopes are significant?</li>
<li>Do these results match the results from <a href="in-class-exercises-2.html#ssOls">3.4.2.7</a>?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="in-class-exercises-2.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semTools)</span>
<span id="cb112-2"><a href="in-class-exercises-2.html#cb112-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-3"><a href="in-class-exercises-2.html#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Define the conditional values at which to calculate simple slopes:</span></span>
<span id="cb112-4"><a href="in-class-exercises-2.html#cb112-4" aria-hidden="true" tabindex="-1"></a>condVals <span class="ot">&lt;-</span> <span class="fu">summarise</span>(outlook,</span>
<span id="cb112-5"><a href="in-class-exercises-2.html#cb112-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">&quot;m-sd&quot;</span> <span class="ot">=</span> <span class="fu">mean</span>(disillusion) <span class="sc">-</span> <span class="fu">sd</span>(disillusion),</span>
<span id="cb112-6"><a href="in-class-exercises-2.html#cb112-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">mean =</span> <span class="fu">mean</span>(disillusion),</span>
<span id="cb112-7"><a href="in-class-exercises-2.html#cb112-7" aria-hidden="true" tabindex="-1"></a>                      <span class="st">&quot;m+sd&quot;</span> <span class="ot">=</span> <span class="fu">mean</span>(disillusion) <span class="sc">+</span> <span class="fu">sd</span>(disillusion)</span>
<span id="cb112-8"><a href="in-class-exercises-2.html#cb112-8" aria-hidden="true" tabindex="-1"></a>                      ) <span class="sc">%&gt;%</span> <span class="fu">unlist</span>()</span>
<span id="cb112-9"><a href="in-class-exercises-2.html#cb112-9" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb112-10"><a href="in-class-exercises-2.html#cb112-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Compute simple slopes and intercepts:</span></span>
<span id="cb112-11"><a href="in-class-exercises-2.html#cb112-11" aria-hidden="true" tabindex="-1"></a>ssOut <span class="ot">&lt;-</span> <span class="fu">probe2WayMC</span>(pathFit, </span>
<span id="cb112-12"><a href="in-class-exercises-2.html#cb112-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">nameX    =</span> <span class="fu">c</span>(<span class="st">&quot;success&quot;</span>, <span class="st">&quot;disillusion&quot;</span>, <span class="st">&quot;success:disillusion&quot;</span>), </span>
<span id="cb112-13"><a href="in-class-exercises-2.html#cb112-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">nameY    =</span> <span class="st">&quot;progress&quot;</span>, </span>
<span id="cb112-14"><a href="in-class-exercises-2.html#cb112-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">modVar   =</span> <span class="st">&quot;disillusion&quot;</span>,</span>
<span id="cb112-15"><a href="in-class-exercises-2.html#cb112-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">valProbe =</span> condVals)</span>
<span id="cb112-16"><a href="in-class-exercises-2.html#cb112-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-17"><a href="in-class-exercises-2.html#cb112-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Check the results:</span></span>
<span id="cb112-18"><a href="in-class-exercises-2.html#cb112-18" aria-hidden="true" tabindex="-1"></a>ssOut</span></code></pre></div>
<pre><code>## $SimpleIntcept
##      disillusion   est    se      z pvalue
## m-sd       2.719 4.690 0.231 20.271      0
## mean       3.497 4.084 0.190 21.508      0
## m+sd       4.274 3.477 0.230 15.122      0
## 
## $SimpleSlope
##      disillusion   est    se      z pvalue
## m-sd       2.719 0.897 0.083 10.792      0
## mean       3.497 1.033 0.065 15.994      0
## m+sd       4.274 1.169 0.088 13.223      0</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="in-class-exercises-2.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Visualize the simple slopes:</span></span>
<span id="cb114-2"><a href="in-class-exercises-2.html#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotProbe</span>(ssOut,</span>
<span id="cb114-3"><a href="in-class-exercises-2.html#cb114-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlim =</span> <span class="fu">range</span>(outlook<span class="sc">$</span>success), </span>
<span id="cb114-4"><a href="in-class-exercises-2.html#cb114-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Ease of Personal Success&quot;</span>, </span>
<span id="cb114-5"><a href="in-class-exercises-2.html#cb114-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab =</span> <span class="st">&quot;Progress toward American Dream&quot;</span>,</span>
<span id="cb114-6"><a href="in-class-exercises-2.html#cb114-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">legendArgs =</span> <span class="fu">list</span>(<span class="at">legend =</span> <span class="fu">names</span>(condVals))</span>
<span id="cb114-7"><a href="in-class-exercises-2.html#cb114-7" aria-hidden="true" tabindex="-1"></a>          )</span></code></pre></div>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<p>Each of the simple slopes is significant. As level of disillusionment increases,
the effect of <em>success</em> on <em>progress</em> also increases, and this effect is
significant for all levels of <em>disillusion</em> considered here. These results
match the simple slopes from the OLS regression analysis.</p>
</details>
</details>
<hr />
<p>End of In-Class Exercises 3</p>
<hr />

</div>
</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises-2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="efa.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["willy_wallaby_from_wasatch.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"search": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
