<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.4 In-Class Exercises | Theory Construction and Statistical Modeling</title>
  <meta name="description" content="5.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="5.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.4 In-Class Exercises | Theory Construction and Statistical Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises-4.html"/>
<link rel="next" href="full-sem.html"/>
<script src="libs/jquery-3.6.1/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">TCSM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reading-questions.html"><a href="reading-questions.html"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html"><i class="fa fa-check"></i>Weekly preparation</a>
<ul>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a></li>
<li class="chapter" data-level="" data-path="attendance.html"><a href="attendance.html"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="assignment-1-path-analysis.html"><a href="assignment-1-path-analysis.html#submission"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html"><i class="fa fa-check"></i>Assignment 2: Confirmatory Factor Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html#evaluation-1"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="assignment-2-confirmatory-factor-analysis.html"><a href="assignment-2-confirmatory-factor-analysis.html#submission-1"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html"><i class="fa fa-check"></i>Assignment 3: Full Structural Equation Model</a>
<ul>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#evaluation-2"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a3_components.html"><a href="a3_components.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#results_format"><i class="fa fa-check"></i>Results</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html"><i class="fa fa-check"></i>Data</a>
<ul>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#coping-with-covid"><i class="fa fa-check"></i>Coping with Covid</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#feminist-perspectives-scale"><i class="fa fa-check"></i>Feminist Perspectives Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#hypersensitive-narcissism-scale-dirty-dozen"><i class="fa fa-check"></i>Hypersensitive Narcissism Scale &amp; Dirty Dozen</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#kentucky-inventory-of-mindfulness-skills"><i class="fa fa-check"></i>Kentucky Inventory of Mindfulness Skills</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#depression-anxiety-stress-scale"><i class="fa fa-check"></i>Depression Anxiety Stress Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#nomophobia"><i class="fa fa-check"></i>Nomophobia</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#recylced-water-acceptance"><i class="fa fa-check"></i>Recylced Water Acceptance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-3"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#group-assignments"><i class="fa fa-check"></i>Group Assignments</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#individual-assignment"><i class="fa fa-check"></i>Individual Assignment</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#resits"><i class="fa fa-check"></i>Resits</a></li>
<li class="chapter" data-level="" data-path="grading-1.html"><a href="grading-1.html#example-assignment"><i class="fa fa-check"></i>Example Assignment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html"><i class="fa fa-check"></i>Rules</a>
<ul>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#academic-integrity"><i class="fa fa-check"></i>Academic integrity</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#strict-stuff"><i class="fa fa-check"></i>Strict stuff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="at-home-exercises.html"><a href="at-home-exercises.html#visualizations-with-r"><i class="fa fa-check"></i><b>1.3.1</b> Visualizations with R</a></li>
<li class="chapter" data-level="1.3.2" data-path="at-home-exercises.html"><a href="at-home-exercises.html#programming-with-r"><i class="fa fa-check"></i><b>1.3.2</b> Programming with R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="in-class-exercises.html"><a href="in-class-exercises.html#viewing-data"><i class="fa fa-check"></i><b>1.4.1</b> Viewing Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="in-class-exercises.html"><a href="in-class-exercises.html#dissecting-data"><i class="fa fa-check"></i><b>1.4.2</b> Dissecting Data</a></li>
<li class="chapter" data-level="1.4.3" data-path="in-class-exercises.html"><a href="in-class-exercises.html#grouping-and-manipulating-data"><i class="fa fa-check"></i><b>1.4.3</b> Grouping and Manipulating Data</a></li>
<li class="chapter" data-level="1.4.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>1.4.4</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="1.4.5" data-path="in-class-exercises.html"><a href="in-class-exercises.html#visualizing-data"><i class="fa fa-check"></i><b>1.4.5</b> Visualizing Data</a></li>
<li class="chapter" data-level="1.4.6" data-path="in-class-exercises.html"><a href="in-class-exercises.html#tidying-data"><i class="fa fa-check"></i><b>1.4.6</b> Tidying Data</a></li>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.1</b> </a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.1</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.2</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.3</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.1</b> Mediation</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.2</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.1</b> Mediation</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.2</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="efa.html"><a href="efa.html"><i class="fa fa-check"></i><b>4</b> EFA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recording"><i class="fa fa-check"></i><b>4.1.1</b> Recording</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-1-1"><i class="fa fa-check"></i>Reference 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-1-1"><i class="fa fa-check"></i>Questions 1</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-2-1"><i class="fa fa-check"></i>Reference 2</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-2-1"><i class="fa fa-check"></i>Questions 2</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-44"><i class="fa fa-check"></i><b>4.3.1</b> </a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#run_pca"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#pcScores"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#trust_efa"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#efaAtt"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#factorScores"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
<li class="chapter" data-level="4.4.13" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.13</b> </a></li>
<li class="chapter" data-level="4.4.14" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.14</b> </a></li>
<li class="chapter" data-level="4.4.15" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.15</b> </a></li>
<li class="chapter" data-level="4.4.16" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-64"><i class="fa fa-check"></i><b>4.4.16</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa.html"><a href="cfa.html"><i class="fa fa-check"></i><b>5</b> CFA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lecture-4.html"><a href="lecture-4.html#recording-1"><i class="fa fa-check"></i><b>5.1.1</b> Recording</a></li>
<li class="chapter" data-level="5.1.2" data-path="lecture-4.html"><a href="lecture-4.html#slides-4"><i class="fa fa-check"></i><b>5.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-65"><i class="fa fa-check"></i><b>5.3.1</b> </a></li>
<li class="chapter" data-level="5.3.2" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#cfaSyntax"><i class="fa fa-check"></i><b>5.3.2</b> </a></li>
<li class="chapter" data-level="5.3.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-66"><i class="fa fa-check"></i><b>5.3.3</b> </a></li>
<li class="chapter" data-level="5.3.4" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-67"><i class="fa fa-check"></i><b>5.3.4</b> </a></li>
<li class="chapter" data-level="5.3.5" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-68"><i class="fa fa-check"></i><b>5.3.5</b> </a></li>
<li class="chapter" data-level="5.3.6" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-69"><i class="fa fa-check"></i><b>5.3.6</b> </a></li>
<li class="chapter" data-level="5.3.7" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-70"><i class="fa fa-check"></i><b>5.3.7</b> </a></li>
<li class="chapter" data-level="5.3.8" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-71"><i class="fa fa-check"></i><b>5.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-72"><i class="fa fa-check"></i><b>5.4.1</b> </a></li>
<li class="chapter" data-level="5.4.2" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt"><i class="fa fa-check"></i><b>5.4.2</b> </a></li>
<li class="chapter" data-level="5.4.3" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-73"><i class="fa fa-check"></i><b>5.4.3</b> </a></li>
<li class="chapter" data-level="5.4.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfaSyntaxAtt1f"><i class="fa fa-check"></i><b>5.4.4</b> </a></li>
<li class="chapter" data-level="5.4.5" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#compare1f5f"><i class="fa fa-check"></i><b>5.4.5</b> </a></li>
<li class="chapter" data-level="5.4.6" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-74"><i class="fa fa-check"></i><b>5.4.6</b> </a></li>
<li class="chapter" data-level="5.4.7" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#cfa2nd"><i class="fa fa-check"></i><b>5.4.7</b> </a></li>
<li class="chapter" data-level="5.4.8" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-75"><i class="fa fa-check"></i><b>5.4.8</b> </a></li>
<li class="chapter" data-level="5.4.9" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-76"><i class="fa fa-check"></i><b>5.4.9</b> </a></li>
<li class="chapter" data-level="5.4.10" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-77"><i class="fa fa-check"></i><b>5.4.10</b> </a></li>
<li class="chapter" data-level="5.4.11" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-78"><i class="fa fa-check"></i><b>5.4.11</b> </a></li>
<li class="chapter" data-level="5.4.12" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-79"><i class="fa fa-check"></i><b>5.4.12</b> </a></li>
<li class="chapter" data-level="5.4.13" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#section-80"><i class="fa fa-check"></i><b>5.4.13</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>6</b> Full SEM</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>6.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="lecture-5.html"><a href="lecture-5.html#recording-2"><i class="fa fa-check"></i><b>6.1.1</b> Recording</a></li>
<li class="chapter" data-level="6.1.2" data-path="lecture-5.html"><a href="lecture-5.html#slides-5"><i class="fa fa-check"></i><b>6.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>6.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#reference-4"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#questions-4"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>6.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="6.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>6.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>7</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="lecture-6.html"><a href="lecture-6.html#recordings-3"><i class="fa fa-check"></i><b>7.1.1</b> Recordings</a></li>
<li class="chapter" data-level="7.1.2" data-path="lecture-6.html"><a href="lecture-6.html#slides-6"><i class="fa fa-check"></i><b>7.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="wrap-up.html"><a href="wrap-up.html"><i class="fa fa-check"></i><b>8</b> Wrap-Up</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Theory Construction and Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises-4" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> In-Class Exercises<a href="in-class-exercises-4.html#in-class-exercises-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This week, we will wrap up our re-analysis of the Kestilä (2006) results. During
this practical, you will conduct a CFA of the <em>Attitudes toward Immigration</em>
items and compare the results to those obtained from your previous EFA- and
PCA-based replications of Kestilä (2006).</p>
<hr />
<div id="section-72" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> </h3>
<p>Load the ESS data.</p>
<ul>
<li>The relevant data are contained in the <a href="https://surfdrive.surf.nl/files/index.php/s/P8OENzmMuNXmpjq/download"><em>ess_round1_attitudes.rds</em></a> file.
<ul>
<li>This file is in R Data Set (RDS) format.</li>
<li>The dataset is already stored as a data frame with the processing and
cleaning that you should have done for previous practicals completed.</li>
</ul></li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="in-class-exercises-4.html#cb217-1" aria-hidden="true" tabindex="-1"></a>ess <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;ess_round1_attitudes.rds&quot;</span>)</span></code></pre></div>
</details>
<hr />
<p>We are going to conduct a CFA to evaluate the measurement model implied by the
five-factor representation of the <em>Attitudes toward Immigration</em> items that you
should have found via the EFA you conducted in the
<a href="in-class-exercises-3.html">Week 4 In-Class Exercises</a>.</p>
<p><em>Caveat:</em> Technically, the following CFA result have no confirmatory value
because we’ll be estimating our CFA models from the same data that we used for
our EFA. Practicing the techniques will still be useful, though.</p>
<hr />
</div>
<div id="cfaSyntaxAtt" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> </h3>
<p>Define the <code>lavaan</code> model syntax for the CFA implied by the five-factor solution
from <a href="in-class-exercises-3.html#efaAtt">4.4.9</a>.</p>
<ul>
<li>Enforce a simple structure; do not allow any cross-loadings.</li>
<li>Covary the five latent factors.</li>
<li>Do not specify any mean structure.</li>
<li>Save this model syntax as an object in your environment.</li>
</ul>
<p><em>Hints:</em></p>
<ul>
<li>You can algorithmically enforce a simple structure by assigning each item to
the factor upon which it loads most strongly.</li>
<li>You can download the fitted <code>psych::efa()</code> object for the five-factor solution
<a href="data/w4_efa_attitudes.rds">here</a>.</li>
<li>The pattern matrix for the five-factor EFA solution in our Week 4 exercises is
equivalent to the solution presented in Table 3 of Kestilä (2006).</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="in-class-exercises-4.html#cb218-1" aria-hidden="true" tabindex="-1"></a>mod_5f <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb218-2"><a href="in-class-exercises-4.html#cb218-2" aria-hidden="true" tabindex="-1"></a><span class="st">## Immigration Policy:</span></span>
<span id="cb218-3"><a href="in-class-exercises-4.html#cb218-3" aria-hidden="true" tabindex="-1"></a><span class="st">ip =~ imrcntr + eimrcnt + eimpcnt + imsmetn + impcntr + imdfetn </span></span>
<span id="cb218-4"><a href="in-class-exercises-4.html#cb218-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb218-5"><a href="in-class-exercises-4.html#cb218-5" aria-hidden="true" tabindex="-1"></a><span class="st">## Social Threat:</span></span>
<span id="cb218-6"><a href="in-class-exercises-4.html#cb218-6" aria-hidden="true" tabindex="-1"></a><span class="st">st =~ imbgeco + imbleco + imwbcnt + imwbcrm + imtcjob + imueclt</span></span>
<span id="cb218-7"><a href="in-class-exercises-4.html#cb218-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb218-8"><a href="in-class-exercises-4.html#cb218-8" aria-hidden="true" tabindex="-1"></a><span class="st">## Refugee Policy:</span></span>
<span id="cb218-9"><a href="in-class-exercises-4.html#cb218-9" aria-hidden="true" tabindex="-1"></a><span class="st">rp =~ gvrfgap + imrsprc + rfgbfml + rfggvfn + rfgawrk + rfgfrpc + shrrfg</span></span>
<span id="cb218-10"><a href="in-class-exercises-4.html#cb218-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb218-11"><a href="in-class-exercises-4.html#cb218-11" aria-hidden="true" tabindex="-1"></a><span class="st">## Cultural Threat:</span></span>
<span id="cb218-12"><a href="in-class-exercises-4.html#cb218-12" aria-hidden="true" tabindex="-1"></a><span class="st">ct =~ qfimchr + qfimwht + pplstrd + vrtrlg</span></span>
<span id="cb218-13"><a href="in-class-exercises-4.html#cb218-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb218-14"><a href="in-class-exercises-4.html#cb218-14" aria-hidden="true" tabindex="-1"></a><span class="st">## Economic Threat:</span></span>
<span id="cb218-15"><a href="in-class-exercises-4.html#cb218-15" aria-hidden="true" tabindex="-1"></a><span class="st">et =~ imwgdwn + imhecop </span></span>
<span id="cb218-16"><a href="in-class-exercises-4.html#cb218-16" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
<p><em>Note:</em> We don’t have to specify the latent covariances in the model syntax, we
can tell <code>lavaan</code> to estimate all latent covariances when we fit the model.</p>
</details>
<hr />
</div>
<div id="section-73" class="section level3" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> </h3>
<p>Estimate the CFA model you defined above, and summarize the results.</p>
<ul>
<li>Use the <code>lavaan::cfa()</code> function to estimate the model.</li>
<li>Use the default settings for the <code>cfa()</code> function.</li>
<li>Request the model fit statistics with the summary by supplying the
<code>fit.measures = TRUE</code> argument to <code>summary()</code>.</li>
<li>Request the standardized parameter estimates with the summary by supplying the
<code>standardized = TRUE</code> argument to <code>summary()</code>.</li>
</ul>
<p>Check the results, and answer the following questions:</p>
<ul>
<li>Does the model fit the data well?</li>
<li>How are the latent variances and covariances specified when using the default
settings?</li>
<li>How is the model identified when using the default settings?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="in-class-exercises-4.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the lavaan package:</span></span>
<span id="cb219-2"><a href="in-class-exercises-4.html#cb219-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb219-3"><a href="in-class-exercises-4.html#cb219-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-4"><a href="in-class-exercises-4.html#cb219-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the CFA model:</span></span>
<span id="cb219-5"><a href="in-class-exercises-4.html#cb219-5" aria-hidden="true" tabindex="-1"></a>fit_5f <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod_5f, <span class="at">data =</span> ess)</span>
<span id="cb219-6"><a href="in-class-exercises-4.html#cb219-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-7"><a href="in-class-exercises-4.html#cb219-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Summarize the fitted model:</span></span>
<span id="cb219-8"><a href="in-class-exercises-4.html#cb219-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_5f, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 71 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        60
## 
##                                                   Used       Total
##   Number of observations                         14243       19690
## 
## Model Test User Model:
##                                                        
##   Test statistic                              18630.545
##   Degrees of freedom                                265
##   P-value (Chi-square)                            0.000
## 
## Model Test Baseline Model:
## 
##   Test statistic                            160506.963
##   Degrees of freedom                               300
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.885
##   Tucker-Lewis Index (TLI)                       0.870
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)            -520659.935
##   Loglikelihood unrestricted model (H1)    -511344.662
##                                                       
##   Akaike (AIC)                             1041439.869
##   Bayesian (BIC)                           1041893.710
##   Sample-size adjusted Bayesian (SABIC)    1041703.036
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.070
##   90 Percent confidence interval - lower         0.069
##   90 Percent confidence interval - upper         0.071
##   P-value H_0: RMSEA &lt;= 0.050                    0.000
##   P-value H_0: RMSEA &gt;= 0.080                    0.000
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.049
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   ip =~                                                                 
##     imrcntr           1.000                               0.617    0.748
##     eimrcnt           0.942    0.011   84.956    0.000    0.582    0.696
##     eimpcnt           1.126    0.010  113.425    0.000    0.695    0.898
##     imsmetn           0.982    0.010   98.770    0.000    0.606    0.796
##     impcntr           1.150    0.010  113.642    0.000    0.710    0.900
##     imdfetn           1.131    0.010  111.811    0.000    0.698    0.887
##   st =~                                                                 
##     imbgeco           1.000                               1.644    0.737
##     imbleco           0.828    0.012   71.268    0.000    1.362    0.630
##     imwbcnt           1.049    0.012   90.290    0.000    1.724    0.799
##     imwbcrm           0.709    0.011   64.669    0.000    1.166    0.573
##     imtcjob           0.760    0.011   68.999    0.000    1.248    0.611
##     imueclt           1.022    0.013   80.247    0.000    1.680    0.708
##   rp =~                                                                 
##     gvrfgap           1.000                               0.649    0.601
##     imrsprc           0.865    0.017   51.063    0.000    0.561    0.533
##     rfgbfml           1.064    0.019   55.354    0.000    0.690    0.593
##     rfggvfn           0.870    0.017   51.404    0.000    0.564    0.538
##     rfgawrk           0.666    0.016   40.873    0.000    0.432    0.407
##     rfgfrpc          -0.822    0.016  -50.427    0.000   -0.533   -0.525
##     shrrfg           -1.021    0.018  -57.724    0.000   -0.662   -0.629
##   ct =~                                                                 
##     qfimchr           1.000                               1.875    0.640
##     qfimwht           0.940    0.017   55.019    0.000    1.762    0.670
##     pplstrd          -0.349    0.007  -51.093    0.000   -0.655   -0.584
##     vrtrlg            0.250    0.006   41.934    0.000    0.468    0.449
##   et =~                                                                 
##     imwgdwn           1.000                               0.728    0.671
##     imhecop           1.137    0.023   50.455    0.000    0.827    0.766
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   ip ~~                                                                 
##     st               -0.612    0.013  -48.650    0.000   -0.603   -0.603
##     rp                0.260    0.006   45.201    0.000    0.649    0.649
##     ct                0.634    0.016   40.791    0.000    0.548    0.548
##     et               -0.208    0.006  -35.659    0.000   -0.463   -0.463
##   st ~~                                                                 
##     rp               -0.815    0.017  -47.420    0.000   -0.764   -0.764
##     ct               -1.543    0.041  -37.283    0.000   -0.501   -0.501
##     et                0.704    0.018   39.849    0.000    0.588    0.588
##   rp ~~                                                                 
##     ct                0.625    0.018   34.830    0.000    0.514    0.514
##     et               -0.232    0.007  -33.112    0.000   -0.492   -0.492
##   ct ~~                                                                 
##     et               -0.583    0.020  -29.517    0.000   -0.427   -0.427
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .imrcntr           0.299    0.004   77.940    0.000    0.299    0.440
##    .eimrcnt           0.359    0.005   79.638    0.000    0.359    0.515
##    .eimpcnt           0.116    0.002   62.833    0.000    0.116    0.193
##    .imsmetn           0.212    0.003   75.579    0.000    0.212    0.366
##    .impcntr           0.119    0.002   62.453    0.000    0.119    0.191
##    .imdfetn           0.132    0.002   65.358    0.000    0.132    0.213
##    .imbgeco           2.268    0.033   69.759    0.000    2.268    0.456
##    .imbleco           2.814    0.037   76.364    0.000    2.814    0.603
##    .imwbcnt           1.681    0.027   62.609    0.000    1.681    0.361
##    .imwbcrm           2.783    0.035   78.457    0.000    2.783    0.672
##    .imtcjob           2.622    0.034   77.160    0.000    2.622    0.627
##    .imueclt           2.802    0.039   72.046    0.000    2.802    0.498
##    .gvrfgap           0.746    0.010   73.853    0.000    0.746    0.639
##    .imrsprc           0.793    0.010   77.015    0.000    0.793    0.716
##    .rfgbfml           0.877    0.012   74.258    0.000    0.877    0.648
##    .rfggvfn           0.783    0.010   76.834    0.000    0.783    0.711
##    .rfgawrk           0.943    0.012   80.731    0.000    0.943    0.835
##    .rfgfrpc           0.749    0.010   77.341    0.000    0.749    0.725
##    .shrrfg            0.670    0.009   72.132    0.000    0.670    0.604
##    .qfimchr           5.059    0.081   62.712    0.000    5.059    0.590
##    .qfimwht           3.806    0.065   58.946    0.000    3.806    0.551
##    .pplstrd           0.828    0.012   68.340    0.000    0.828    0.658
##    .vrtrlg            0.867    0.011   76.703    0.000    0.867    0.798
##    .imwgdwn           0.645    0.012   53.096    0.000    0.645    0.549
##    .imhecop           0.481    0.013   35.709    0.000    0.481    0.413
##     ip                0.381    0.007   51.585    0.000    1.000    1.000
##     st                2.702    0.056   48.680    0.000    1.000    1.000
##     rp                0.421    0.012   35.968    0.000    1.000    1.000
##     ct                3.515    0.098   35.798    0.000    1.000    1.000
##     et                0.529    0.015   35.342    0.000    1.000    1.000</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>No, the model does not seem to fit the data well.</p>
<ul>
<li>The SRMR looks good, but one good looking fit statistic is not enough.</li>
<li>The TLI and CFI are in the “unacceptable” range.</li>
<li>RMSEA is in the “questionable” range.</li>
<li>The <span class="math inline">\(\chi^2\)</span> is highly significant, but we don’t care.</li>
</ul>
<p>The <code>cfa()</code> function is just a wrapper for the <code>lavaan()</code> function with several
options set at the defaults you would want for a standard CFA.</p>
<ul>
<li>By default:
<ul>
<li>All latent variances and covariances are freely estimated (due to the
argument <code>auto.cov.lv.x = TRUE</code>)</li>
<li>The model is identified by fixing the first factor loading of each factor
to 1 (due to the argument <code>auto.fix.first = TRUE</code>)</li>
</ul></li>
</ul>
<p>To see a full list of the (many) options you can specify to tweak the behavior
of <code>lavaan</code> estimation functions run <code>?lavOptions</code>.</p>
</details>
</details>
<hr />
<p>Now, we will consider a couple of alternative factor structures for the <em>Attitudes
toward Immigration</em> CFA. First, we will go extremely simple by estimating a one-factor
model wherein all <em>Attitude</em> items are explained by a single latent variable.</p>
<hr />
</div>
<div id="cfaSyntaxAtt1f" class="section level3" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> </h3>
<p>Define the <code>lavaan</code> model syntax for a one-factor model of the <em>Immigration</em> items.</p>
<ul>
<li>Save this syntax as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="in-class-exercises-4.html#cb221-1" aria-hidden="true" tabindex="-1"></a>mod_1f <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb221-2"><a href="in-class-exercises-4.html#cb221-2" aria-hidden="true" tabindex="-1"></a><span class="st">ati =~ imrcntr + eimrcnt + eimpcnt + imsmetn + impcntr + imdfetn + imbgeco +</span></span>
<span id="cb221-3"><a href="in-class-exercises-4.html#cb221-3" aria-hidden="true" tabindex="-1"></a><span class="st">       imbleco + imwbcnt + imwbcrm + imtcjob + imueclt + gvrfgap + imrsprc +</span></span>
<span id="cb221-4"><a href="in-class-exercises-4.html#cb221-4" aria-hidden="true" tabindex="-1"></a><span class="st">       rfgbfml + rfggvfn + rfgawrk + rfgfrpc + shrrfg  + qfimchr + qfimwht +</span></span>
<span id="cb221-5"><a href="in-class-exercises-4.html#cb221-5" aria-hidden="true" tabindex="-1"></a><span class="st">       pplstrd + vrtrlg  + imwgdwn + imhecop</span></span>
<span id="cb221-6"><a href="in-class-exercises-4.html#cb221-6" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="compare1f5f" class="section level3" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> </h3>
<p>Estimate the one-factor model, and summarize the results.</p>
<ul>
<li>Compare the fit measures for the one-factor and five-factor models</li>
<li>Which model better fits the data?</li>
</ul>
<p><em>Note:</em> Remember, you can use the <code>lavaan::fitMeasures()</code> function to extract
only the model fit information from a fitted <code>lavaan</code> object.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="in-class-exercises-4.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the one factor model:</span></span>
<span id="cb222-2"><a href="in-class-exercises-4.html#cb222-2" aria-hidden="true" tabindex="-1"></a>fit_1f <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod_1f, <span class="at">data =</span> ess)</span>
<span id="cb222-3"><a href="in-class-exercises-4.html#cb222-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-4"><a href="in-class-exercises-4.html#cb222-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Summarize the results:</span></span>
<span id="cb222-5"><a href="in-class-exercises-4.html#cb222-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1f)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 48 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        50
## 
##                                                   Used       Total
##   Number of observations                         14243       19690
## 
## Model Test User Model:
##                                                        
##   Test statistic                              50540.369
##   Degrees of freedom                                275
##   P-value (Chi-square)                            0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   ati =~                                              
##     imrcntr           1.000                           
##     eimrcnt           0.937    0.012   78.516    0.000
##     eimpcnt           1.112    0.011  101.485    0.000
##     imsmetn           0.987    0.011   91.214    0.000
##     impcntr           1.146    0.011  102.640    0.000
##     imdfetn           1.151    0.011  103.290    0.000
##     imbgeco          -2.080    0.032  -65.037    0.000
##     imbleco          -1.651    0.031  -53.067    0.000
##     imwbcnt          -2.200    0.031  -71.199    0.000
##     imwbcrm          -1.455    0.029  -49.601    0.000
##     imtcjob          -1.559    0.029  -52.963    0.000
##     imueclt          -2.230    0.034  -65.546    0.000
##     gvrfgap           0.793    0.016   50.940    0.000
##     imrsprc           0.752    0.015   49.544    0.000
##     rfgbfml           0.857    0.017   51.125    0.000
##     rfggvfn           0.724    0.015   47.876    0.000
##     rfgawrk           0.530    0.015   34.483    0.000
##     rfgfrpc          -0.750    0.015  -51.225    0.000
##     shrrfg           -0.931    0.015  -61.532    0.000
##     qfimchr           1.556    0.042   36.793    0.000
##     qfimwht           1.730    0.038   45.639    0.000
##     pplstrd          -0.872    0.016  -54.018    0.000
##     vrtrlg            0.591    0.015   39.305    0.000
##     imwgdwn          -0.686    0.016  -43.889    0.000
##     imhecop          -0.774    0.016  -49.761    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .imrcntr           0.326    0.004   78.988    0.000
##    .eimrcnt           0.387    0.005   80.403    0.000
##    .eimpcnt           0.161    0.002   70.807    0.000
##    .imsmetn           0.235    0.003   77.068    0.000
##    .impcntr           0.157    0.002   69.617    0.000
##    .imdfetn           0.151    0.002   68.870    0.000
##    .imbgeco           3.438    0.042   82.179    0.000
##    .imbleco           3.704    0.045   83.099    0.000
##    .imwbcnt           2.943    0.036   81.500    0.000
##    .imwbcrm           3.395    0.041   83.296    0.000
##    .imtcjob           3.321    0.040   83.105    0.000
##    .imueclt           3.865    0.047   82.130    0.000
##    .gvrfgap           0.945    0.011   83.222    0.000
##    .imrsprc           0.909    0.011   83.299    0.000
##    .rfgbfml           1.094    0.013   83.212    0.000
##    .rfggvfn           0.916    0.011   83.385    0.000
##    .rfgawrk           1.031    0.012   83.912    0.000
##    .rfgfrpc           0.834    0.010   83.206    0.000
##    .shrrfg            0.802    0.010   82.494    0.000
##    .qfimchr           7.717    0.092   83.839    0.000
##    .qfimwht           5.851    0.070   83.492    0.000
##    .pplstrd           0.988    0.012   83.040    0.000
##    .vrtrlg            0.962    0.011   83.752    0.000
##    .imwgdwn           1.008    0.012   83.570    0.000
##    .imhecop           0.953    0.011   83.287    0.000
##     ati               0.354    0.007   49.032    0.000</code></pre>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="in-class-exercises-4.html#cb224-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Compare fit statistics:</span></span>
<span id="cb224-2"><a href="in-class-exercises-4.html#cb224-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_5f,</span>
<span id="cb224-3"><a href="in-class-exercises-4.html#cb224-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">fit.measures =</span> <span class="fu">c</span>(<span class="st">&quot;npar&quot;</span>,                  <span class="co"># Estimated parameters</span></span>
<span id="cb224-4"><a href="in-class-exercises-4.html#cb224-4" aria-hidden="true" tabindex="-1"></a>                             <span class="st">&quot;chisq&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;pvalue&quot;</span>, <span class="co"># Model fit vs. saturated</span></span>
<span id="cb224-5"><a href="in-class-exercises-4.html#cb224-5" aria-hidden="true" tabindex="-1"></a>                             <span class="st">&quot;cfi&quot;</span>, <span class="st">&quot;tli&quot;</span>,            <span class="co"># Model fit vs. baseline</span></span>
<span id="cb224-6"><a href="in-class-exercises-4.html#cb224-6" aria-hidden="true" tabindex="-1"></a>                             <span class="st">&quot;rmsea&quot;</span>, <span class="st">&quot;srmr&quot;</span>),        <span class="co"># Model fit vs. saturated</span></span>
<span id="cb224-7"><a href="in-class-exercises-4.html#cb224-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">output =</span> <span class="st">&quot;text&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Model Test User Model:
## 
##   Test statistic                             18630.545
##   Degrees of freedom                               265
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.885
##   Tucker-Lewis Index (TLI)                       0.870
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.070
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.049</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="in-class-exercises-4.html#cb226-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_1f,</span>
<span id="cb226-2"><a href="in-class-exercises-4.html#cb226-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">fit.measures =</span> <span class="fu">c</span>(<span class="st">&quot;npar&quot;</span>,                  <span class="co"># Estimated parameters</span></span>
<span id="cb226-3"><a href="in-class-exercises-4.html#cb226-3" aria-hidden="true" tabindex="-1"></a>                             <span class="st">&quot;chisq&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;pvalue&quot;</span>, <span class="co"># Model fit vs. saturated</span></span>
<span id="cb226-4"><a href="in-class-exercises-4.html#cb226-4" aria-hidden="true" tabindex="-1"></a>                             <span class="st">&quot;cfi&quot;</span>, <span class="st">&quot;tli&quot;</span>,            <span class="co"># Model fit vs. baseline</span></span>
<span id="cb226-5"><a href="in-class-exercises-4.html#cb226-5" aria-hidden="true" tabindex="-1"></a>                             <span class="st">&quot;rmsea&quot;</span>, <span class="st">&quot;srmr&quot;</span>),        <span class="co"># Model fit vs. saturated</span></span>
<span id="cb226-6"><a href="in-class-exercises-4.html#cb226-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">output =</span> <span class="st">&quot;text&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Model Test User Model:
## 
##   Test statistic                             50540.369
##   Degrees of freedom                               275
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.686
##   Tucker-Lewis Index (TLI)                       0.658
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.113
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.088</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>The one-factor model definitely seems to fit worse than the five-factor model.</p>
</details>
</details>
<hr />
</div>
<div id="section-74" class="section level3" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> </h3>
<p>Given the CFA results from the five factor model, would a second-order CFA be
appropriate for the <em>Attitudes towards Immigration</em> data? Why or why not?</p>
<details>
<summary>
Click for explanation
</summary>
<p>Yes, a second-order CFA model is a theoretically appropriate representation of
the <em>Attitudes towards Immigration</em> items.</p>
<ul>
<li>The first order latent variables in the five-factor model are all
significantly correlated.</li>
<li>The first order latent variables in the five-factor model seem to tap
different aspects of some single underlying construct.</li>
</ul>
</details>
<hr />
</div>
<div id="cfa2nd" class="section level3" number="5.4.7">
<h3><span class="header-section-number">5.4.7</span> </h3>
<p>Define the <code>lavaan</code> model syntax for a second-order CFA model of the <em>Attitudes
towards Immigration</em> items, estimate it, and inspect the results.</p>
<ul>
<li>Use the five factors defined in <a href="in-class-exercises-4.html#cfaSyntaxAtt">5.4.2</a> as the first order factors.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="in-class-exercises-4.html#cb228-1" aria-hidden="true" tabindex="-1"></a>mod_2o <span class="ot">&lt;-</span> <span class="fu">paste</span>(mod_5f,</span>
<span id="cb228-2"><a href="in-class-exercises-4.html#cb228-2" aria-hidden="true" tabindex="-1"></a>                <span class="st">&#39;ati =~ ip + rp + st + ct + et&#39;</span>,</span>
<span id="cb228-3"><a href="in-class-exercises-4.html#cb228-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">sep =</span> <span class="st">&#39;</span><span class="sc">\n</span><span class="st">&#39;</span>)</span>
<span id="cb228-4"><a href="in-class-exercises-4.html#cb228-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb228-5"><a href="in-class-exercises-4.html#cb228-5" aria-hidden="true" tabindex="-1"></a>fit_2o <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod_2o, <span class="at">data =</span> ess)</span>
<span id="cb228-6"><a href="in-class-exercises-4.html#cb228-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_2o, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 97 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        55
## 
##                                                   Used       Total
##   Number of observations                         14243       19690
## 
## Model Test User Model:
##                                                        
##   Test statistic                              19103.443
##   Degrees of freedom                                270
##   P-value (Chi-square)                            0.000
## 
## Model Test Baseline Model:
## 
##   Test statistic                            160506.963
##   Degrees of freedom                               300
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.882
##   Tucker-Lewis Index (TLI)                       0.869
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)            -520896.384
##   Loglikelihood unrestricted model (H1)    -511344.662
##                                                       
##   Akaike (AIC)                             1041902.767
##   Bayesian (BIC)                           1042318.788
##   Sample-size adjusted Bayesian (SABIC)    1042144.003
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.070
##   90 Percent confidence interval - lower         0.069
##   90 Percent confidence interval - upper         0.071
##   P-value H_0: RMSEA &lt;= 0.050                    0.000
##   P-value H_0: RMSEA &gt;= 0.080                    0.000
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.049
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   ip =~                                               
##     imrcntr           1.000                           
##     eimrcnt           0.943    0.011   85.103    0.000
##     eimpcnt           1.126    0.010  113.541    0.000
##     imsmetn           0.982    0.010   98.923    0.000
##     impcntr           1.149    0.010  113.687    0.000
##     imdfetn           1.130    0.010  111.787    0.000
##   st =~                                               
##     imbgeco           1.000                           
##     imbleco           0.824    0.012   70.853    0.000
##     imwbcnt           1.051    0.012   90.406    0.000
##     imwbcrm           0.707    0.011   64.414    0.000
##     imtcjob           0.754    0.011   68.469    0.000
##     imueclt           1.029    0.013   80.734    0.000
##   rp =~                                               
##     gvrfgap           1.000                           
##     imrsprc           0.862    0.017   50.603    0.000
##     rfgbfml           1.059    0.019   54.809    0.000
##     rfggvfn           0.868    0.017   51.004    0.000
##     rfgawrk           0.667    0.016   40.676    0.000
##     rfgfrpc          -0.835    0.016  -50.724    0.000
##     shrrfg           -1.033    0.018  -57.819    0.000
##   ct =~                                               
##     qfimchr           1.000                           
##     qfimwht           0.937    0.018   52.705    0.000
##     pplstrd          -0.373    0.007  -50.868    0.000
##     vrtrlg            0.267    0.006   42.424    0.000
##   et =~                                               
##     imwgdwn           1.000                           
##     imhecop           1.146    0.023   49.359    0.000
##   ati =~                                              
##     ip                1.000                           
##     rp                1.229    0.023   53.071    0.000
##     st               -3.072    0.051  -60.780    0.000
##     ct                2.590    0.057   45.080    0.000
##     et               -1.008    0.023  -43.069    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .imrcntr           0.299    0.004   77.901    0.000
##    .eimrcnt           0.359    0.005   79.599    0.000
##    .eimpcnt           0.116    0.002   62.714    0.000
##    .imsmetn           0.211    0.003   75.507    0.000
##    .impcntr           0.119    0.002   62.458    0.000
##    .imdfetn           0.133    0.002   65.444    0.000
##    .imbgeco           2.267    0.033   69.679    0.000
##    .imbleco           2.834    0.037   76.468    0.000
##    .imwbcnt           1.668    0.027   62.244    0.000
##    .imwbcrm           2.793    0.036   78.490    0.000
##    .imtcjob           2.645    0.034   77.290    0.000
##    .imueclt           2.765    0.039   71.650    0.000
##    .gvrfgap           0.749    0.010   73.863    0.000
##    .imrsprc           0.798    0.010   77.089    0.000
##    .rfgbfml           0.885    0.012   74.412    0.000
##    .rfggvfn           0.786    0.010   76.876    0.000
##    .rfgawrk           0.944    0.012   80.716    0.000
##    .rfgfrpc           0.742    0.010   77.025    0.000
##    .shrrfg            0.663    0.009   71.643    0.000
##    .qfimchr           5.269    0.082   64.348    0.000
##    .qfimwht           4.010    0.065   61.244    0.000
##    .pplstrd           0.797    0.012   65.994    0.000
##    .vrtrlg            0.850    0.011   75.681    0.000
##    .imwgdwn           0.649    0.012   52.727    0.000
##    .imhecop           0.475    0.014   34.383    0.000
##    .ip                0.173    0.004   43.678    0.000
##    .st                0.734    0.025   29.357    0.000
##    .rp                0.103    0.005   22.069    0.000
##    .ct                1.905    0.063   30.027    0.000
##    .et                0.313    0.010   31.643    0.000
##     ati               0.209    0.006   37.582    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-75" class="section level3" number="5.4.8">
<h3><span class="header-section-number">5.4.8</span> </h3>
<p>Compare the model fit of the first- and second-order five-factor models using
the <code>fitMeasures()</code> function.</p>
<ul>
<li>Which model offers the better fit?</li>
<li>Which model is more complex?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="in-class-exercises-4.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_5f,</span>
<span id="cb230-2"><a href="in-class-exercises-4.html#cb230-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="fu">c</span>(<span class="st">&quot;npar&quot;</span>,                  <span class="co"># Estimated parameters</span></span>
<span id="cb230-3"><a href="in-class-exercises-4.html#cb230-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;chisq&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;pvalue&quot;</span>, <span class="co"># Model fit vs. saturated</span></span>
<span id="cb230-4"><a href="in-class-exercises-4.html#cb230-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;cfi&quot;</span>, <span class="st">&quot;tli&quot;</span>,            <span class="co"># Model fit vs. baseline</span></span>
<span id="cb230-5"><a href="in-class-exercises-4.html#cb230-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;rmsea&quot;</span>, <span class="st">&quot;srmr&quot;</span>),        <span class="co"># Model fit vs. saturated</span></span>
<span id="cb230-6"><a href="in-class-exercises-4.html#cb230-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">&quot;text&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Model Test User Model:
## 
##   Test statistic                             18630.545
##   Degrees of freedom                               265
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.885
##   Tucker-Lewis Index (TLI)                       0.870
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.070
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.049</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="in-class-exercises-4.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_2o,</span>
<span id="cb232-2"><a href="in-class-exercises-4.html#cb232-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="fu">c</span>(<span class="st">&quot;npar&quot;</span>,                  <span class="co"># Estimated parameters</span></span>
<span id="cb232-3"><a href="in-class-exercises-4.html#cb232-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;chisq&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;pvalue&quot;</span>, <span class="co"># Model fit vs. saturated</span></span>
<span id="cb232-4"><a href="in-class-exercises-4.html#cb232-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;cfi&quot;</span>, <span class="st">&quot;tli&quot;</span>,            <span class="co"># Model fit vs. baseline</span></span>
<span id="cb232-5"><a href="in-class-exercises-4.html#cb232-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;rmsea&quot;</span>, <span class="st">&quot;srmr&quot;</span>),        <span class="co"># Model fit vs. saturated</span></span>
<span id="cb232-6"><a href="in-class-exercises-4.html#cb232-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">&quot;text&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Model Test User Model:
## 
##   Test statistic                             19103.443
##   Degrees of freedom                               270
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.882
##   Tucker-Lewis Index (TLI)                       0.869
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.070
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.049</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>The CFI and TLI are both slightly better in the original five factor model,
but the RMSEA and SRMR of both models don’t differ out to three decimal places.
As usual, both models have a significant <span class="math inline">\(\chi^2\)</span>, but that doesn’t tell us much.</p>
</details>
</details>
<hr />
<p>Qualitative comparisons of model fit are fine, but we’d like to have an actual
statistical test for these fit differences. As it happens, we have just such a
test: a nested model <span class="math inline">\(\Delta \chi^2\)</span> test (AKA, chi-squared difference test,
change in chi-squared test, likelihood ratio test).</p>
<p>In the Week 7 lecture, we’ll cover nested models and tests thereof, but it will
be useful to start thinking about these concepts now. Two models are said to be
<em>nested</em> if you can define one model by placing constraints on the other model.</p>
<p>By way of example, consider the following two CFA models.</p>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-169-1.png" width="672" /><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-169-2.png" width="672" /></p>
<p>The second model is nested within the first model, because we can define the
second model by fixing the latent covariance to zero in the first model.</p>
<p>Notice that the data contain <span class="math inline">\(6(6 + 1) / 2 = 21\)</span> unique pieces of information.
The first model estimates 13 parameters, and
the second model estimates 12 parameters. Hence the first model has
8 degrees of freedom, and the second model has 9
degrees of freedom.</p>
<p>In general, the following must hold whenever <em>Model B</em> is nested within <em>Model A</em>.</p>
<ul>
<li>Model B will have <em>fewer</em> estimated parameters than Model A.</li>
<li>Model B will have <em>more</em> degrees of freedom than Model A.</li>
<li>Model A will be <em>more</em> complex than model B.</li>
<li>Model A will fit the data <em>better</em> than model B.</li>
</ul>
<hr />
<p><strong>Saturated Model</strong></p>
<p>All models are nested within the saturated model, because the saturated model
estimates all possible relations among the variables. Regardless of what model
we may be considering, we can always convert that model to a saturated model by
estimating all possible associations. Hence, all models are nested within the
saturated model.</p>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-170-1.png" width="672" /></p>
<hr />
<p><strong>Baseline Model</strong></p>
<p>Similarly, the baseline model (AKA, independence model) is nested within all
other models. In the baseline model, we only estimate the variances of the
observed items; all associations are constrained to zero. We can always convert
our model to the baseline model by fixing all associations to zero. Hence, the
baseline model is nested within all other models.</p>
<p><img src="willy_wallaby_from_wasatch_files/figure-html/unnamed-chunk-171-1.png" width="672" /></p>
<hr />
<p>When two models are nested, we can use a <span class="math inline">\(\Delta \chi^2\)</span> test to check if the
nested model fits <em>significantly worse</em> than its parent model. Whenever we place
constraints on the model, the fit will deteriorate, but we want to know if the
constraints we imposed to define the nested model have produced <em>too much</em> loss
of fit.</p>
<p>We can use the <code>anova()</code> function to easily conduct <span class="math inline">\(\Delta \chi^2\)</span> tests
comparing models that we’ve estimated with <code>cfa()</code> or <code>sem()</code>.</p>
<hr />
</div>
<div id="section-76" class="section level3" number="5.4.9">
<h3><span class="header-section-number">5.4.9</span> </h3>
<p>Use the <code>anova()</code> function to compare the five-factor model from
<a href="in-class-exercises-4.html#cfaSyntaxAtt">5.4.2</a> and one-factor model from <a href="in-class-exercises-4.html#cfaSyntaxAtt1f">5.4.4</a>.</p>
<ul>
<li>Explain what <code>Df</code>, <code>Chisq</code>, <code>Chisq diff</code>, <code>Df diff</code>, and <code>Pr(&gt;Chisq)</code> mean.</li>
<li>Which model is more complex?</li>
<li>Which model fits better?</li>
<li>What is the conclusion of the test?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="in-class-exercises-4.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_1f, fit_5f)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Chisq diff"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["RMSEA"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Df diff"],"name":[7],"type":["int"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"265","2":"1041440","3":"1041894","4":"18630.55","5":"NA","6":"NA","7":"NA","8":"NA","_rn_":"fit_5f"},{"1":"275","2":"1073330","3":"1073708","4":"50540.37","5":"31909.82","6":"0.473253","7":"10","8":"0","_rn_":"fit_1f"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>The <code>Df</code> column contains the degrees of freedom of each model.</p>
<ul>
<li>Higher df <span class="math inline">\(\Rightarrow\)</span> Less complex model</li>
</ul>
<p>The <code>Chisq</code> column shows the <span class="math inline">\(\chi^2\)</span> statistics (AKA, likelihood ratio
statistics) for each model.</p>
<ul>
<li><span class="math inline">\(\chi^2\)</span> = The ratio of the likelihoods for the estimated model and the
saturated model).</li>
<li>Larger <span class="math inline">\(\chi^2\)</span> <span class="math inline">\(\Rightarrow\)</span> Worse fit</li>
</ul>
<p><code>Chisq diff</code> is the difference between the two <span class="math inline">\(\chi^2\)</span> values (i.e.,
<span class="math inline">\(\Delta \chi^2\)</span>.</p>
<ul>
<li>How much better the more complex model fits the data</li>
<li>Larger <span class="math inline">\(\Delta \chi^2\)</span> values indicate greater losses of fit induced by the
constraints needed to define the nested model.</li>
</ul>
<p><code>Df diff</code> is the difference in the degrees of freedom between the models.</p>
<ul>
<li>Since both models must be estimated from the same pool of variables, this
difference also represents the number of parameters that were constrained
to define the nested model.</li>
</ul>
<p><code>Pr(&gt;Chisq)</code> is a p-value for the <span class="math inline">\(\Delta \chi^2\)</span> test.</p>
<ul>
<li><span class="math inline">\(H_0: \Delta \chi^2 = 0\)</span></li>
<li><span class="math inline">\(H_1: \Delta \chi^2 &gt; 0\)</span></li>
</ul>
<p>The five-factor model is more complex than the one-factor model, but the extra
complexity is justified The five-factor model fits significantly better than
the one-factor model.</p>
</details>
</details>
<hr />
</div>
<div id="section-77" class="section level3" number="5.4.10">
<h3><span class="header-section-number">5.4.10</span> </h3>
<p>Use the <code>anova()</code> function to compare the first- and second-order five-factor
models from <a href="in-class-exercises-4.html#cfaSyntaxAtt">5.4.2</a> and <a href="in-class-exercises-4.html#cfa2nd">5.4.7</a>.</p>
<ul>
<li>Which model is more complex?</li>
<li>What is the conclusion of the test?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="in-class-exercises-4.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_5f, fit_2o)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Chisq diff"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["RMSEA"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Df diff"],"name":[7],"type":["int"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"265","2":"1041440","3":"1041894","4":"18630.55","5":"NA","6":"NA","7":"NA","8":"NA","_rn_":"fit_5f"},{"1":"270","2":"1041903","3":"1042319","4":"19103.44","5":"472.898","6":"0.08105687","7":"5","8":"5.639394e-100","_rn_":"fit_2o"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>The first-order model is more complex than the second-order model
(df = 265 vs. df = 270),
and the extra complexity is necessary. The first-order model fits significantly
better than the second-order model.</p>
</details>
</details>
<hr />
</div>
<div id="section-78" class="section level3" number="5.4.11">
<h3><span class="header-section-number">5.4.11</span> </h3>
<p>Based on the results above, would you say that you have successfully confirmed
the five-factor structure implied by the EFA?</p>
<details>
<summary>
Click for explanation
</summary>
<p>Nope, not so much. The first-order five-factor model may fit the data best out
of the three models considered here, but it still fits terribly. None of these
models is an adequate representation of the <em>Attitudes toward Immigration</em> items.</p>
<p>This result is particularly embarrassing when you consider that we’ve stacked the
deck in our favor by using the same data to conduct the EFA and the CFA.</p>
<p>When we fail to support the hypothesized measurement model, the confirmatory
phase of our analysis is over. At this point, we’ve essentially rejected our
hypothesized measurement structure, and that’s the conclusion of our analysis.
We don’t have to throw up our hands in despair, however. We can still contribute
something useful by modifying the theoretical measurement model through an
exploratory, data-driven, post-hoc analysis.</p>
<p>We’ll give that a shot below.</p>
</details>
<hr />
</div>
<div id="section-79" class="section level3" number="5.4.12">
<h3><span class="header-section-number">5.4.12</span> </h3>
<p>Modify the five-factor CFA from <a href="in-class-exercises-4.html#cfaSyntaxAtt">5.4.2</a> by freeing the following
parameters.</p>
<ul>
<li>The residual covariance between <code>imrcntr</code> and <code>eimrcnt</code>
<ul>
<li>These questions both ask about allowing immigration from wealthy countries.</li>
<li>It makes sense that answers on these two items share some additional,
unique variance above-and-beyond what they contribute to the common factors.</li>
</ul></li>
<li>The residual covariance between <code>qfimchr</code> and <code>qfimwht</code>
<ul>
<li>These questions are both about imposing qualifications on immigration
(specifically Christian religion and “white” race).</li>
</ul></li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="in-class-exercises-4.html#cb236-1" aria-hidden="true" tabindex="-1"></a>fit_5f_cov <span class="ot">&lt;-</span> <span class="fu">paste</span>(mod_5f, </span>
<span id="cb236-2"><a href="in-class-exercises-4.html#cb236-2" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&#39;imrcntr ~~ eimrcnt&#39;</span>, </span>
<span id="cb236-3"><a href="in-class-exercises-4.html#cb236-3" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&#39;qfimchr ~~ qfimwht&#39;</span>, </span>
<span id="cb236-4"><a href="in-class-exercises-4.html#cb236-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sep =</span> <span class="st">&#39;</span><span class="sc">\n</span><span class="st">&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb236-5"><a href="in-class-exercises-4.html#cb236-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cfa</span>(<span class="at">data =</span> ess)</span>
<span id="cb236-6"><a href="in-class-exercises-4.html#cb236-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb236-7"><a href="in-class-exercises-4.html#cb236-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_5f_cov, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 74 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        62
## 
##                                                   Used       Total
##   Number of observations                         14243       19690
## 
## Model Test User Model:
##                                                       
##   Test statistic                              9725.604
##   Degrees of freedom                               263
##   P-value (Chi-square)                           0.000
## 
## Model Test Baseline Model:
## 
##   Test statistic                            160506.963
##   Degrees of freedom                               300
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.941
##   Tucker-Lewis Index (TLI)                       0.933
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)            -516207.464
##   Loglikelihood unrestricted model (H1)    -511344.662
##                                                       
##   Akaike (AIC)                             1032538.927
##   Bayesian (BIC)                           1033007.897
##   Sample-size adjusted Bayesian (SABIC)    1032810.866
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.050
##   90 Percent confidence interval - lower         0.049
##   90 Percent confidence interval - upper         0.051
##   P-value H_0: RMSEA &lt;= 0.050                    0.307
##   P-value H_0: RMSEA &gt;= 0.080                    0.000
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.035
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   ip =~                                               
##     imrcntr           1.000                           
##     eimrcnt           0.928    0.007  126.266    0.000
##     eimpcnt           1.183    0.011  106.527    0.000
##     imsmetn           1.012    0.011   92.456    0.000
##     impcntr           1.213    0.011  107.105    0.000
##     imdfetn           1.181    0.011  104.575    0.000
##   st =~                                               
##     imbgeco           1.000                           
##     imbleco           0.828    0.012   71.006    0.000
##     imwbcnt           1.053    0.012   90.311    0.000
##     imwbcrm           0.711    0.011   64.656    0.000
##     imtcjob           0.759    0.011   68.719    0.000
##     imueclt           1.029    0.013   80.517    0.000
##   rp =~                                               
##     gvrfgap           1.000                           
##     imrsprc           0.868    0.017   51.183    0.000
##     rfgbfml           1.062    0.019   55.299    0.000
##     rfggvfn           0.869    0.017   51.354    0.000
##     rfgawrk           0.666    0.016   40.828    0.000
##     rfgfrpc          -0.825    0.016  -50.578    0.000
##     shrrfg           -1.024    0.018  -57.852    0.000
##   ct =~                                               
##     qfimchr           1.000                           
##     qfimwht           0.978    0.020   48.007    0.000
##     pplstrd          -0.592    0.015  -40.195    0.000
##     vrtrlg            0.399    0.011   36.002    0.000
##   et =~                                               
##     imwgdwn           1.000                           
##     imhecop           1.141    0.023   50.347    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##  .imrcntr ~~                                          
##    .eimrcnt           0.230    0.004   59.902    0.000
##  .qfimchr ~~                                          
##    .qfimwht           2.617    0.064   40.671    0.000
##   ip ~~                                               
##     st               -0.586    0.012  -47.994    0.000
##     rp                0.251    0.006   44.837    0.000
##     ct                0.461    0.014   34.074    0.000
##     et               -0.199    0.006  -35.351    0.000
##   st ~~                                               
##     rp               -0.812    0.017  -47.392    0.000
##     ct               -1.349    0.039  -34.298    0.000
##     et                0.700    0.018   39.737    0.000
##   rp ~~                                               
##     ct                0.530    0.016   32.121    0.000
##     et               -0.232    0.007  -33.081    0.000
##   ct ~~                                               
##     et               -0.465    0.017  -27.756    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .imrcntr           0.330    0.004   78.901    0.000
##    .eimrcnt           0.396    0.005   80.392    0.000
##    .eimpcnt           0.109    0.002   60.413    0.000
##    .imsmetn           0.220    0.003   75.978    0.000
##    .impcntr           0.107    0.002   58.862    0.000
##    .imdfetn           0.131    0.002   64.653    0.000
##    .imbgeco           2.280    0.033   70.047    0.000
##    .imbleco           2.825    0.037   76.519    0.000
##    .imwbcnt           1.673    0.027   62.636    0.000
##    .imwbcrm           2.783    0.035   78.509    0.000
##    .imtcjob           2.633    0.034   77.307    0.000
##    .imueclt           2.777    0.039   71.947    0.000
##    .gvrfgap           0.747    0.010   74.008    0.000
##    .imrsprc           0.792    0.010   77.058    0.000
##    .rfgbfml           0.880    0.012   74.449    0.000
##    .rfggvfn           0.784    0.010   76.968    0.000
##    .rfgawrk           0.944    0.012   80.793    0.000
##    .rfgfrpc           0.747    0.010   77.367    0.000
##    .shrrfg            0.669    0.009   72.185    0.000
##    .qfimchr           6.887    0.091   75.331    0.000
##    .qfimwht           5.297    0.072   73.350    0.000
##    .pplstrd           0.667    0.013   51.552    0.000
##    .vrtrlg            0.817    0.011   72.865    0.000
##    .imwgdwn           0.647    0.012   53.266    0.000
##    .imhecop           0.478    0.014   35.353    0.000
##     ip                0.350    0.007   48.654    0.000
##     st                2.689    0.055   48.557    0.000
##     rp                0.420    0.012   35.958    0.000
##     ct                1.687    0.073   23.045    0.000
##     et                0.527    0.015   35.255    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-80" class="section level3" number="5.4.13">
<h3><span class="header-section-number">5.4.13</span> </h3>
<p>Evaluate the model modifications.</p>
<ul>
<li>Did the model fit significantly improve?</li>
<li>Is the fit of the modified model acceptable?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="in-class-exercises-4.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_5f_cov, fit_5f)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["AIC"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Chisq diff"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["RMSEA"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Df diff"],"name":[7],"type":["int"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"263","2":"1032539","3":"1033008","4":"9725.604","5":"NA","6":"NA","7":"NA","8":"NA","_rn_":"fit_5f_cov"},{"1":"265","2":"1041440","3":"1041894","4":"18630.545","5":"8904.942","6":"0.5590505","7":"2","8":"0","_rn_":"fit_5f"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="in-class-exercises-4.html#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_5f_cov)</span></code></pre></div>
<pre><code>##                  npar                  fmin                 chisq 
##                62.000                 0.341              9725.604 
##                    df                pvalue        baseline.chisq 
##               263.000                 0.000            160506.963 
##           baseline.df       baseline.pvalue                   cfi 
##               300.000                 0.000                 0.941 
##                   tli                  nnfi                   rfi 
##                 0.933                 0.933                 0.931 
##                   nfi                  pnfi                   ifi 
##                 0.939                 0.824                 0.941 
##                   rni                  logl     unrestricted.logl 
##                 0.941           -516207.464           -511344.662 
##                   aic                   bic                ntotal 
##           1032538.927           1033007.897             14243.000 
##                  bic2                 rmsea        rmsea.ci.lower 
##           1032810.866                 0.050                 0.049 
##        rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue 
##                 0.051                 0.900                 0.307 
##        rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 
##                 0.050                 0.000                 0.080 
##                   rmr            rmr_nomean                  srmr 
##                 0.103                 0.103                 0.035 
##          srmr_bentler   srmr_bentler_nomean                  crmr 
##                 0.035                 0.035                 0.037 
##           crmr_nomean            srmr_mplus     srmr_mplus_nomean 
##                 0.037                 0.035                 0.035 
##                 cn_05                 cn_01                   gfi 
##               443.020               468.574                 0.944 
##                  agfi                  pgfi                   mfi 
##                 0.931                 0.764                 0.717 
##                  ecvi 
##                 0.692</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>Yes, the model fit improved significantly. In this case, the original five-factor
model is nested within the modified model. So, our <span class="math inline">\(\Delta \chi^2\)</span> test is
evaluating the improvement in fit contributed by freeing the two residual
covariances. The <span class="math inline">\(\Delta \chi^2\)</span> test is significant, so we can conclude that
including the two new parameter estimates has significantly improved the model fit.</p>
<ul>
<li>I.e., Estimating these two residual covariances is “worth it” in the sense of
balancing model fit and model complexity.</li>
</ul>
<p>Also, the fit of the modified model is now acceptable.</p>
<p><strong>Caveat</strong></p>
<p>If we had found this result when testing our original model, we would be
well-situated to proceed with our analysis. In this case, however, we are no
longer justified in generalizing these estimates to the population. We only
arrived at this well-fitting model by modifying our original theoretical model
to better fit the data using estimates derived from those same data to guide our
model modifications.</p>
<p>We’ve conducted this post-hoc analysis to help inform future research, and this
result is useful as a starting point for future studies. Now, anyone analyzing
these scales in the future could incorporate these residual covariances into
their initial theoretical model. Basically, we conduct these types of post-hoc
analyses to help future researchers learn from our mistakes.</p>
</details>
</details>
<!------------------------------------------------------------------------------

---

###

Examine the sections Latent Variables and Covariances in the lavaan output. 

- Determine whether the latent variable `refugeepolicy` represents a person's
  tendency to be either for or against policies targeting refugees.
- With which latent variables is `refugeepolicy` positively correlated?
- With which latent variables is `refugeepolicy` negatively correlated?

<details>
  <summary>Click to show code</summary>
  

```r
summary(fit_5f_cov, standardized = TRUE)
```

```
## lavaan 0.6.16 ended normally after 74 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        62
## 
##                                                   Used       Total
##   Number of observations                         14243       19690
## 
## Model Test User Model:
##                                                       
##   Test statistic                              9725.604
##   Degrees of freedom                               263
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
##   ip =~                                                                 
##     imrcntr           1.000                               0.592    0.718
##     eimrcnt           0.928    0.007  126.266    0.000    0.549    0.658
##     eimpcnt           1.183    0.011  106.527    0.000    0.700    0.905
##     imsmetn           1.012    0.011   92.456    0.000    0.599    0.787
##     impcntr           1.213    0.011  107.105    0.000    0.718    0.910
##     imdfetn           1.181    0.011  104.575    0.000    0.699    0.888
##   st =~                                                                 
##     imbgeco           1.000                               1.640    0.736
##     imbleco           0.828    0.012   71.006    0.000    1.358    0.628
##     imwbcnt           1.053    0.012   90.311    0.000    1.727    0.800
##     imwbcrm           0.711    0.011   64.656    0.000    1.167    0.573
##     imtcjob           0.759    0.011   68.719    0.000    1.244    0.608
##     imueclt           1.029    0.013   80.517    0.000    1.688    0.712
##   rp =~                                                                 
##     gvrfgap           1.000                               0.648    0.600
##     imrsprc           0.868    0.017   51.183    0.000    0.562    0.534
##     rfgbfml           1.062    0.019   55.299    0.000    0.688    0.592
##     rfggvfn           0.869    0.017   51.354    0.000    0.563    0.536
##     rfgawrk           0.666    0.016   40.828    0.000    0.431    0.406
##     rfgfrpc          -0.825    0.016  -50.578    0.000   -0.535   -0.526
##     shrrfg           -1.024    0.018  -57.852    0.000   -0.664   -0.630
##   ct =~                                                                 
##     qfimchr           1.000                               1.299    0.444
##     qfimwht           0.978    0.020   48.007    0.000    1.270    0.483
##     pplstrd          -0.592    0.015  -40.195    0.000   -0.768   -0.685
##     vrtrlg            0.399    0.011   36.002    0.000    0.518    0.497
##   et =~                                                                 
##     imwgdwn           1.000                               0.726    0.670
##     imhecop           1.141    0.023   50.347    0.000    0.829    0.768
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
##  .imrcntr ~~                                                            
##    .eimrcnt           0.230    0.004   59.902    0.000    0.230    0.636
##  .qfimchr ~~                                                            
##    .qfimwht           2.617    0.064   40.671    0.000    2.617    0.433
##   ip ~~                                                                 
##     st               -0.586    0.012  -47.994    0.000   -0.604   -0.604
##     rp                0.251    0.006   44.837    0.000    0.654    0.654
##     ct                0.461    0.014   34.074    0.000    0.600    0.600
##     et               -0.199    0.006  -35.351    0.000   -0.463   -0.463
##   st ~~                                                                 
##     rp               -0.812    0.017  -47.392    0.000   -0.764   -0.764
##     ct               -1.349    0.039  -34.298    0.000   -0.633   -0.633
##     et                0.700    0.018   39.737    0.000    0.588    0.588
##   rp ~~                                                                 
##     ct                0.530    0.016   32.121    0.000    0.629    0.629
##     et               -0.232    0.007  -33.081    0.000   -0.492   -0.492
##   ct ~~                                                                 
##     et               -0.465    0.017  -27.756    0.000   -0.493   -0.493
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
##    .imrcntr           0.330    0.004   78.901    0.000    0.330    0.485
##    .eimrcnt           0.396    0.005   80.392    0.000    0.396    0.567
##    .eimpcnt           0.109    0.002   60.413    0.000    0.109    0.181
##    .imsmetn           0.220    0.003   75.978    0.000    0.220    0.381
##    .impcntr           0.107    0.002   58.862    0.000    0.107    0.172
##    .imdfetn           0.131    0.002   64.653    0.000    0.131    0.211
##    .imbgeco           2.280    0.033   70.047    0.000    2.280    0.459
##    .imbleco           2.825    0.037   76.519    0.000    2.825    0.605
##    .imwbcnt           1.673    0.027   62.636    0.000    1.673    0.359
##    .imwbcrm           2.783    0.035   78.509    0.000    2.783    0.672
##    .imtcjob           2.633    0.034   77.307    0.000    2.633    0.630
##    .imueclt           2.777    0.039   71.947    0.000    2.777    0.494
##    .gvrfgap           0.747    0.010   74.008    0.000    0.747    0.640
##    .imrsprc           0.792    0.010   77.058    0.000    0.792    0.715
##    .rfgbfml           0.880    0.012   74.449    0.000    0.880    0.650
##    .rfggvfn           0.784    0.010   76.968    0.000    0.784    0.712
##    .rfgawrk           0.944    0.012   80.793    0.000    0.944    0.835
##    .rfgfrpc           0.747    0.010   77.367    0.000    0.747    0.723
##    .shrrfg            0.669    0.009   72.185    0.000    0.669    0.603
##    .qfimchr           6.887    0.091   75.331    0.000    6.887    0.803
##    .qfimwht           5.297    0.072   73.350    0.000    5.297    0.767
##    .pplstrd           0.667    0.013   51.552    0.000    0.667    0.530
##    .vrtrlg            0.817    0.011   72.865    0.000    0.817    0.753
##    .imwgdwn           0.647    0.012   53.266    0.000    0.647    0.551
##    .imhecop           0.478    0.014   35.353    0.000    0.478    0.410
##     ip                0.350    0.007   48.654    0.000    1.000    1.000
##     st                2.689    0.055   48.557    0.000    1.000    1.000
##     rp                0.420    0.012   35.958    0.000    1.000    1.000
##     ct                1.687    0.073   23.045    0.000    1.000    1.000
##     et                0.527    0.015   35.255    0.000    1.000    1.000
```
  
  <details>
    <summary>Click for explanation</summary>
 
We can tell from the factor loadings that `refugeepolicy` represents a 
favorable stance towards refugees. The first indicator provides the scale
for the latent variable. In this case, this is the indicator `gvrfgap` 
("Government should be generous judging applications for refugee status").
The other indicators in support of allowing refugees to work or bring
close family members also have positive loadings, which makes sense. 
 
The variables `rfgfrpc` and `shrrfg` have negative loadings, because they are
attitudes towards the statements "Most refugee applicants not in real fear
of persecution own countries" and "Country has more than its fair share of
people applying refugee status". This makes sense, because someone who has
a high degree of support for policies helping refugees is likely to have a
low degree of support for those statements.
 
Refugee policy correlates positively with `immigpolicy` and `culturalthreat`
and negatively with `socialthreat` and `economicthreat`.
  
  </details>
</details>

---

###

Which indicator has the highest amount of shared variance / is the item most
representative of each of the latent variables?

<details>
  <summary>Click for explanation</summary>

We can look either at `Std.lv` or `Std.all` under the Latent Variables section
of the output. 

- For `immigpolicy`, `impcntr` has the highest absolute value.
- For `socialthreat`, `imwbcnt` has the highest absolute value.
- For `refugeepolicy`, `shrrfg` has the highest absolute value.
- For `culturalthreat`, `pplstrd` has the highest absolute value.
- For `economicthreat`, `imhecop` has the highest absolute value.
  
</details>

------------------------------------------------------------------------------->
<hr />
<p>End of In-Class Exercises</p>
<hr />

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises-4.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="full-sem.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["willy_wallaby_from_wasatch.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"search": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
