<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.5 In-Class Exercises | Theory Construction and Statistical Modeling</title>
  <meta name="description" content="1.5 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="1.5 In-Class Exercises | Theory Construction and Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.5 In-Class Exercises | Theory Construction and Statistical Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">TCSM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a>
<ul>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reading-questions.html"><a href="reading-questions.html"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html"><i class="fa fa-check"></i>Weekly preparation</a>
<ul>
<li class="chapter" data-level="" data-path="weekly-preparation.html"><a href="weekly-preparation.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a></li>
<li class="chapter" data-level="" data-path="attendance.html"><a href="attendance.html"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="0.1" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i><b>0.1</b> Typographic Conventions</a></li>
<li class="chapter" data-level="0.2" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i><b>0.2</b> Installing software</a>
<ul>
<li class="chapter" data-level="0.2.1" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i><b>0.2.1</b> Installing R</a></li>
<li class="chapter" data-level="0.2.2" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i><b>0.2.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="0.2.3" data-path="installing-software.html"><a href="installing-software.html#installPackages"><i class="fa fa-check"></i><b>0.2.3</b> Installing packages</a></li>
</ul></li>
<li class="chapter" data-level="0.3" data-path="getting-the-course-data.html"><a href="getting-the-course-data.html"><i class="fa fa-check"></i><b>0.3</b> Getting the course data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-tutorial.html"><a href="r-tutorial.html"><i class="fa fa-check"></i>R Tutorial</a>
<ul>
<li class="chapter" data-level="0.4" data-path="who-r-you.html"><a href="who-r-you.html"><i class="fa fa-check"></i><b>0.4</b> Who R you?</a></li>
<li class="chapter" data-level="0.5" data-path="rstudio.html"><a href="rstudio.html"><i class="fa fa-check"></i><b>0.5</b> RStudio</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="rstudio.html"><a href="rstudio.html#no-pane-no-gain"><i class="fa fa-check"></i><b>0.5.1</b> No ‘pane’, no gain!</a></li>
<li class="chapter" data-level="0.5.2" data-path="rstudio.html"><a href="rstudio.html#create-a-new-r-script"><i class="fa fa-check"></i><b>0.5.2</b> Create a new R script</a></li>
<li class="chapter" data-level="0.5.3" data-path="rstudio.html"><a href="rstudio.html#what-do-the-four-panes-do"><i class="fa fa-check"></i><b>0.5.3</b> What do the four panes do?</a></li>
</ul></li>
<li class="chapter" data-level="0.6" data-path="rstudio-projects.html"><a href="rstudio-projects.html"><i class="fa fa-check"></i><b>0.6</b> RStudio projects</a>
<ul>
<li class="chapter" data-level="0.6.1" data-path="rstudio-projects.html"><a href="rstudio-projects.html#starting-a-new-project-in-rstudio"><i class="fa fa-check"></i><b>0.6.1</b> Starting a new project in Rstudio</a></li>
</ul></li>
<li class="chapter" data-level="0.7" data-path="loading-data.html"><a href="loading-data.html"><i class="fa fa-check"></i><b>0.7</b> Loading data</a>
<ul>
<li class="chapter" data-level="0.7.1" data-path="loading-data.html"><a href="loading-data.html#via-clicky-box-options"><i class="fa fa-check"></i><b>0.7.1</b> Via clicky-box options</a></li>
<li class="chapter" data-level="0.7.2" data-path="loading-data.html"><a href="loading-data.html#via-r-code"><i class="fa fa-check"></i><b>0.7.2</b> Via R code</a></li>
<li class="chapter" data-level="0.7.3" data-path="loading-data.html"><a href="loading-data.html#from-excel-files"><i class="fa fa-check"></i><b>0.7.3</b> From Excel files</a></li>
</ul></li>
<li class="chapter" data-level="0.8" data-path="exploring-data-via-r-functions.html"><a href="exploring-data-via-r-functions.html"><i class="fa fa-check"></i><b>0.8</b> Exploring data via R functions</a>
<ul>
<li class="chapter" data-level="0.8.1" data-path="exploring-data-via-r-functions.html"><a href="exploring-data-via-r-functions.html#head"><i class="fa fa-check"></i><b>0.8.1</b> <code>head()</code></a></li>
<li class="chapter" data-level="0.8.2" data-path="exploring-data-via-r-functions.html"><a href="exploring-data-via-r-functions.html#str"><i class="fa fa-check"></i><b>0.8.2</b> <code>str()</code></a></li>
<li class="chapter" data-level="0.8.3" data-path="exploring-data-via-r-functions.html"><a href="exploring-data-via-r-functions.html#summary"><i class="fa fa-check"></i><b>0.8.3</b> <code>summary()</code></a></li>
</ul></li>
<li class="chapter" data-level="0.9" data-path="tutorialPlotting.html"><a href="tutorialPlotting.html"><i class="fa fa-check"></i><b>0.9</b> Plotting data</a>
<ul>
<li class="chapter" data-level="0.9.1" data-path="tutorialPlotting.html"><a href="tutorialPlotting.html#r-packages-and-ggplot2"><i class="fa fa-check"></i><b>0.9.1</b> R packages and <code>ggplot2</code></a></li>
<li class="chapter" data-level="0.9.2" data-path="tutorialPlotting.html"><a href="tutorialPlotting.html#histogram"><i class="fa fa-check"></i><b>0.9.2</b> Histogram</a></li>
<li class="chapter" data-level="0.9.3" data-path="tutorialPlotting.html"><a href="tutorialPlotting.html#boxplot"><i class="fa fa-check"></i><b>0.9.3</b> Boxplot</a></li>
<li class="chapter" data-level="0.9.4" data-path="tutorialPlotting.html"><a href="tutorialPlotting.html#scatterplot"><i class="fa fa-check"></i><b>0.9.4</b> Scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="0.10" data-path="manipulating-data.html"><a href="manipulating-data.html"><i class="fa fa-check"></i><b>0.10</b> Manipulating Data</a>
<ul>
<li class="chapter" data-level="0.10.1" data-path="manipulating-data.html"><a href="manipulating-data.html#data-types"><i class="fa fa-check"></i><b>0.10.1</b> Data types</a></li>
<li class="chapter" data-level="0.10.2" data-path="manipulating-data.html"><a href="manipulating-data.html#factors"><i class="fa fa-check"></i><b>0.10.2</b> Factors</a></li>
<li class="chapter" data-level="0.10.3" data-path="manipulating-data.html"><a href="manipulating-data.html#subsetting-extracting-one-variable"><i class="fa fa-check"></i><b>0.10.3</b> Subsetting: Extracting one variable</a></li>
<li class="chapter" data-level="0.10.4" data-path="manipulating-data.html"><a href="manipulating-data.html#subsetting-extracting-rows-and-columns"><i class="fa fa-check"></i><b>0.10.4</b> Subsetting: Extracting rows and columns</a></li>
<li class="chapter" data-level="0.10.5" data-path="manipulating-data.html"><a href="manipulating-data.html#subsetting-based-on-logical-conditions"><i class="fa fa-check"></i><b>0.10.5</b> Subsetting based on logical conditions</a></li>
<li class="chapter" data-level="0.10.6" data-path="manipulating-data.html"><a href="manipulating-data.html#changing-cell-values"><i class="fa fa-check"></i><b>0.10.6</b> Changing cell values</a></li>
</ul></li>
<li class="chapter" data-level="0.11" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>0.11</b> Getting Help</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading.html"><a href="reading.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading.html"><a href="reading.html#questions"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="formative-assessment.html"><a href="formative-assessment.html"><i class="fa fa-check"></i><b>1.3</b> Formative Assessment</a></li>
<li class="chapter" data-level="1.4" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.4</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="at-home-exercises.html"><a href="at-home-exercises.html#section"><i class="fa fa-check"></i><b>1.4.1</b> </a></li>
<li class="chapter" data-level="1.4.2" data-path="at-home-exercises.html"><a href="at-home-exercises.html#slr1"><i class="fa fa-check"></i><b>1.4.2</b> </a></li>
<li class="chapter" data-level="1.4.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html#slr2"><i class="fa fa-check"></i><b>1.4.3</b> </a></li>
<li class="chapter" data-level="1.4.4" data-path="at-home-exercises.html"><a href="at-home-exercises.html#slr3"><i class="fa fa-check"></i><b>1.4.4</b> </a></li>
<li class="chapter" data-level="1.4.5" data-path="at-home-exercises.html"><a href="at-home-exercises.html#mlr"><i class="fa fa-check"></i><b>1.4.5</b> </a></li>
<li class="chapter" data-level="1.4.6" data-path="at-home-exercises.html"><a href="at-home-exercises.html#section-1"><i class="fa fa-check"></i><b>1.4.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.5</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="in-class-exercises.html"><a href="in-class-exercises.html#part-1-data-exploration"><i class="fa fa-check"></i><b>1.5.1</b> Part 1: Data Exploration</a></li>
<li class="chapter" data-level="1.5.2" data-path="in-class-exercises.html"><a href="in-class-exercises.html#part-2-regression-analysis"><i class="fa fa-check"></i><b>1.5.2</b> Part 2: Regression Analysis</a></li>
<li class="chapter" data-level="1.5.3" data-path="in-class-exercises.html"><a href="in-class-exercises.html#part-3-anova"><i class="fa fa-check"></i><b>1.5.3</b> Part 3: ANOVA</a></li>
<li class="chapter" data-level="1.5.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html#part-4-ancova"><i class="fa fa-check"></i><b>1.5.4</b> Part 4: ANCOVA</a></li>
<li class="chapter" data-level="1.5.5" data-path="in-class-exercises.html"><a href="in-class-exercises.html#part-5-back-to-regression"><i class="fa fa-check"></i><b>1.5.5</b> Part 5: Back to Regression</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Theory Construction and Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> In-Class Exercises<a href="in-class-exercises.html#in-class-exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>During this practical, you will work through some exercises about ANOVA, ANCOVA, and regression.</p>
<ul>
<li>Note that ANOVA and ANCOVA are special cases of regression.</li>
<li>Or, more accurately, ANOVA, ANCOVA, and regression are all different flavors
of the <em>general linear model</em>.</li>
</ul>
<p>If you need to refresh your knowledge on ANOVA, ANCOVA, or regression consider
the resources listed in the <a href="weekly-preparation.html#background">Background knowledge</a> section.</p>
<hr />
<div id="part-1-data-exploration" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Part 1: Data Exploration<a href="in-class-exercises.html#part-1-data-exploration" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<div id="section-2" class="section level4" number="1.5.1.1">
<h4><span class="header-section-number">1.5.1.1</span> </h4>
<p>Open the file Sesam.sav:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="in-class-exercises.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the &#39;foreign&#39; library for reading SPSS files:</span></span>
<span id="cb47-2"><a href="in-class-exercises.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign)</span>
<span id="cb47-3"><a href="in-class-exercises.html#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="in-class-exercises.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the &#39;Sesam.sav&#39; data into an object called &#39;sesam&#39;:</span></span>
<span id="cb47-5"><a href="in-class-exercises.html#cb47-5" aria-hidden="true" tabindex="-1"></a>sesam <span class="ot">&lt;-</span> <span class="fu">read.spss</span>(<span class="st">&quot;sesam.sav&quot;</span>, <span class="at">to.data.frame =</span> <span class="cn">TRUE</span>, <span class="at">use.value.labels =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<hr />
<p>This file is part of a larger dataset that evaluates the impact of the first
year of the Sesame Street television series. Sesame Street is mainly concerned
with teaching preschool related skills to children in the 3–5 year age range.</p>
<p>The following variables will be used in this exercise:</p>
<ul>
<li><strong>age</strong>: measured in months</li>
<li><strong>prelet</strong>: knowledge of letters before watching Sesame Street (range 0–58)</li>
<li><strong>prenumb</strong>: knowledge of numbers before watching Sesame Street (range 0–54)</li>
<li><strong>prerelat</strong>: knowledge of relations before watching Sesame Street (range 0–17)</li>
<li><strong>peabody</strong>: vocabulary maturity before watching Sesame Street (range 20–120)</li>
<li><strong>postnumb</strong>: knowledge of numbers after a year of Sesame Street (range 0–54)</li>
</ul>
<p><em>Note</em>: Unless otherwise noted, the following questions refer to the <code>sesam</code>
data and the above variables.</p>
<hr />
</div>
<div id="section-3" class="section level4" number="1.5.1.2">
<h4><span class="header-section-number">1.5.1.2</span> </h4>
<p>What is the measurement level of each variable?</p>
<p><em>Hint:</em> The output of the <code>str()</code> function should be helpful here.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="in-class-exercises.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Examine the data structure:</span></span>
<span id="cb48-2"><a href="in-class-exercises.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sesam)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    240 obs. of  8 variables:
##  $ id      : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ age     : num  66 67 56 49 69 54 47 51 69 53 ...
##  $ prelet  : num  23 26 14 11 47 26 12 48 44 38 ...
##  $ prenumb : num  40 39 9 14 51 33 13 52 42 31 ...
##  $ prerelat: num  14 16 9 9 17 14 11 15 15 10 ...
##  $ peabody : num  62 80 32 27 71 32 28 38 49 32 ...
##  $ postnumb: num  44 39 40 19 54 39 44 51 48 52 ...
##  $ gain    : num  4 0 31 5 3 6 31 -1 6 21 ...
##  - attr(*, &quot;codepage&quot;)= int 65001</code></pre>
<p>All variables are numeric.</p>
</details>
<hr />
</div>
<div id="section-4" class="section level4" number="1.5.1.3">
<h4><span class="header-section-number">1.5.1.3</span> </h4>
<ul>
<li>What is the average age in the sample?</li>
<li>What is the age range (youngest and oldest child)?</li>
</ul>
<p><em>Hint:</em> Use <code>tidySEM::descriptives()</code></p>
<details>
<summary>
Click for explanation
</summary>
<p>As in the take home exercises, you can use the <code>descriptives()</code> function from
the <code>tidySEM</code> package to describe the data:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="in-class-exercises.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidySEM)</span>
<span id="cb50-2"><a href="in-class-exercises.html#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="in-class-exercises.html#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(sesam)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["name"],"name":[1],"type":["chr"],"align":["left"]},{"label":["type"],"name":[2],"type":["chr"],"align":["left"]},{"label":["n"],"name":[3],"type":["int"],"align":["right"]},{"label":["missing"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["unique"],"name":[5],"type":["int"],"align":["right"]},{"label":["mean"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["mode"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["mode_value"],"name":[9],"type":["lgl"],"align":["right"]},{"label":["sd"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["v"],"name":[11],"type":["lgl"],"align":["right"]},{"label":["min"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["range"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["skew"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["skew_2se"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["kurt"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["kurt_2se"],"name":[18],"type":["dbl"],"align":["right"]}],"data":[{"1":"id","2":"numeric","3":"240","4":"0","5":"240","6":"120.500000","7":"120.5","8":"120.5","9":"NA","10":"69.426220","11":"NA","12":"1","13":"240","14":"239","15":"0.000000000","16":"0.000000000","17":"-1.21501007","18":"-1.9408393"},{"1":"age","2":"numeric","3":"240","4":"0","5":"33","6":"51.525000","7":"52.0","8":"52.0","9":"NA","10":"6.281356","11":"NA","12":"34","13":"69","14":"35","15":"-0.233536030","16":"-0.743094143","17":"0.31130095","18":"0.4972676"},{"1":"prelet","2":"numeric","3":"240","4":"0","5":"40","6":"15.937500","7":"14.0","8":"14.0","9":"NA","10":"8.536425","11":"NA","12":"1","13":"55","14":"54","15":"1.969433485","16":"6.266589723","17":"4.76701118","18":"7.6147537"},{"1":"prenumb","2":"numeric","3":"240","4":"0","5":"47","6":"20.895833","7":"19.0","8":"19.0","9":"NA","10":"10.685382","11":"NA","12":"1","13":"52","14":"51","15":"0.729616854","16":"2.321586139","17":"0.07849738","18":"0.1253906"},{"1":"prerelat","2":"numeric","3":"240","4":"0","5":"16","6":"9.937500","7":"10.0","8":"10.0","9":"NA","10":"3.073753","11":"NA","12":"2","13":"17","14":"15","15":"-0.177273429","16":"-0.564070762","17":"-0.47484928","18":"-0.7585173"},{"1":"peabody","2":"numeric","3":"240","4":"0","5":"46","6":"46.775000","7":"42.0","8":"42.0","9":"NA","10":"15.986900","11":"NA","12":"27","13":"99","14":"72","15":"1.026881773","16":"3.267460828","17":"0.46567388","18":"0.7438606"},{"1":"postnumb","2":"numeric","3":"240","4":"0","5":"50","6":"30.054167","7":"29.0","8":"29.0","9":"NA","10":"12.845769","11":"NA","12":"0","13":"54","14":"54","15":"0.002760256","16":"0.008782928","17":"-1.10201172","18":"-1.7603374"},{"1":"gain","2":"numeric","3":"240","4":"0","5":"45","6":"9.158333","7":"9.0","8":"9.0","9":"NA","10":"9.682401","11":"NA","12":"-35","13":"33","14":"68","15":"-0.393891365","16":"-1.253332797","17":"1.87658414","18":"2.9976280"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</details>
<hr />
</div>
<div id="changeScore" class="section level4" number="1.5.1.4">
<h4><span class="header-section-number">1.5.1.4</span> </h4>
<ul>
<li>What is the average gain in knowledge of numbers?</li>
<li>What is the standard deviation of this gain?</li>
</ul>
<p><em>Hints:</em></p>
<ul>
<li>You will need to compute the gain and save the change score as a new object.</li>
<li>You can then use the base-R functions mean() and sd() to do the calculations.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<p>Create a new variable that represents the difference between pre- and post-test
scores on knowledge of numbers:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="in-class-exercises.html#cb51-1" aria-hidden="true" tabindex="-1"></a>sesam<span class="sc">$</span>ndif <span class="ot">&lt;-</span> sesam<span class="sc">$</span>postnumb <span class="sc">-</span> sesam<span class="sc">$</span>prenumb</span></code></pre></div>
<p>Compute the mean and SD of the change score:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="in-class-exercises.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sesam<span class="sc">$</span>ndif)</span></code></pre></div>
<pre><code>## [1] 9.158333</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="in-class-exercises.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(sesam<span class="sc">$</span>ndif)</span></code></pre></div>
<pre><code>## [1] 9.682401</code></pre>
</details>
<hr />
</div>
<div id="section-5" class="section level4" number="1.5.1.5">
<h4><span class="header-section-number">1.5.1.5</span> </h4>
<ul>
<li>Create an appropriate visualization of the gain scores you computed in
<a href="in-class-exercises.html#changeScore">1.5.1.4</a>.</li>
<li>Justify your choice of visualization.</li>
</ul>
<p><em>Hint:</em> Some applicable visualizations are explained in <a href="tutorialPlotting.html#tutorialPlotting">0.9</a>.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="in-class-exercises.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-2"><a href="in-class-exercises.html#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="in-class-exercises.html#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Create an empty baseline plot object:</span></span>
<span id="cb56-4"><a href="in-class-exercises.html#cb56-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sesam, <span class="fu">aes</span>(<span class="at">x =</span> ndif))</span>
<span id="cb56-5"><a href="in-class-exercises.html#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="in-class-exercises.html#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Add some appropriate geoms:</span></span>
<span id="cb56-7"><a href="in-class-exercises.html#cb56-7" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="in-class-exercises.html#cb57-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-49-2.png" width="672" /></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="in-class-exercises.html#cb58-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-49-3.png" width="672" /></p>
</details>
<hr />
</div>
<div id="section-6" class="section level4" number="1.5.1.6">
<h4><span class="header-section-number">1.5.1.6</span> </h4>
<ul>
<li>Create a visualization that provides information about the bivariate
relationship between two of the variables.</li>
<li>Justify your choice of visualization.</li>
</ul>
<p><em>Hint:</em> Again, Section <a href="tutorialPlotting.html#tutorialPlotting">0.9</a> may provide some useful insights.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="in-class-exercises.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Create a scatterplot of the pre- and post-test number knowledge</span></span>
<span id="cb59-2"><a href="in-class-exercises.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sesam, <span class="fu">aes</span>(<span class="at">x =</span> prenumb, <span class="at">y =</span> postnumb)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
</details>
<hr />
</div>
</div>
<div id="part-2-regression-analysis" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Part 2: Regression Analysis<a href="in-class-exercises.html#part-2-regression-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<div id="section-7" class="section level4" number="1.5.2.1">
<h4><span class="header-section-number">1.5.2.1</span> </h4>
<p>Are there significant, bivariate associations between <em>postnumb</em> and the
following variables?</p>
<ul>
<li><em>age</em></li>
<li><em>prelet</em></li>
<li><em>prenumb</em></li>
<li><em>prerelat</em></li>
<li><em>peabody</em></li>
</ul>
<p>Use Pearson correlations to answer this question.</p>
<ul>
<li>You do not need to check the assumptions here (though you would in real life).</li>
</ul>
<p><em>Hint:</em> The base-R <code>cor.test()</code> function and the <code>corr.test()</code> function from the
<code>psych</code> package will both conduct hypothesis tests for a correlation
coefficients (the base-R <code>cor()</code> function only computes the coefficients).</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="in-class-exercises.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb60-2"><a href="in-class-exercises.html#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="in-class-exercises.html#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Test the correlations using psych::corr.test():</span></span>
<span id="cb60-4"><a href="in-class-exercises.html#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">corr.test</span>(</span>
<span id="cb60-5"><a href="in-class-exercises.html#cb60-5" aria-hidden="true" tabindex="-1"></a>  sesam[ , <span class="fu">c</span>(<span class="st">&quot;postnumb&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;prelet&quot;</span>, <span class="st">&quot;prenumb&quot;</span>, <span class="st">&quot;prerelat&quot;</span>, <span class="st">&quot;peabody&quot;</span>)]</span>
<span id="cb60-6"><a href="in-class-exercises.html#cb60-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Call:corr.test(x = sesam[, c(&quot;postnumb&quot;, &quot;age&quot;, &quot;prelet&quot;, &quot;prenumb&quot;, 
##     &quot;prerelat&quot;, &quot;peabody&quot;)])
## Correlation matrix 
##          postnumb  age prelet prenumb prerelat peabody
## postnumb     1.00 0.34   0.50    0.68     0.54    0.52
## age          0.34 1.00   0.33    0.43     0.44    0.29
## prelet       0.50 0.33   1.00    0.72     0.47    0.40
## prenumb      0.68 0.43   0.72    1.00     0.72    0.61
## prerelat     0.54 0.44   0.47    0.72     1.00    0.56
## peabody      0.52 0.29   0.40    0.61     0.56    1.00
## Sample Size 
## [1] 240
## Probability values (Entries above the diagonal are adjusted for multiple tests.) 
##          postnumb age prelet prenumb prerelat peabody
## postnumb        0   0      0       0        0       0
## age             0   0      0       0        0       0
## prelet          0   0      0       0        0       0
## prenumb         0   0      0       0        0       0
## prerelat        0   0      0       0        0       0
## peabody         0   0      0       0        0       0
## 
##  To see confidence intervals of the correlations, print with the short=FALSE option</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="in-class-exercises.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="do">## OR ##</span></span>
<span id="cb62-2"><a href="in-class-exercises.html#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="in-class-exercises.html#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Test the correlations using multiple cor.test() calls:</span></span>
<span id="cb62-4"><a href="in-class-exercises.html#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sesam<span class="sc">$</span>postnumb, sesam<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sesam$postnumb and sesam$age
## t = 5.5972, df = 238, p-value = 5.979e-08
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2241066 0.4483253
## sample estimates:
##       cor 
## 0.3410578</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="in-class-exercises.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sesam<span class="sc">$</span>postnumb, sesam<span class="sc">$</span>prelet)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sesam$postnumb and sesam$prelet
## t = 8.9986, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4029239 0.5926632
## sample estimates:
##       cor 
## 0.5038464</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="in-class-exercises.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sesam<span class="sc">$</span>postnumb, sesam<span class="sc">$</span>prenumb)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sesam$postnumb and sesam$prenumb
## t = 14.133, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6002172 0.7389277
## sample estimates:
##       cor 
## 0.6755051</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="in-class-exercises.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sesam<span class="sc">$</span>postnumb, sesam<span class="sc">$</span>prerelat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sesam$postnumb and sesam$prerelat
## t = 9.9857, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4475469 0.6268773
## sample estimates:
##       cor 
## 0.5433818</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="in-class-exercises.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sesam<span class="sc">$</span>postnumb, sesam<span class="sc">$</span>peabody)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sesam$postnumb and sesam$peabody
## t = 9.395, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4212427 0.6067923
## sample estimates:
##      cor 
## 0.520128</code></pre>
</details>
<hr />
</div>
<div id="reg1" class="section level4" number="1.5.2.2">
<h4><span class="header-section-number">1.5.2.2</span> </h4>
<p>Do <em>age</em> and <em>prenumb</em> explain a significant proportion of the variance in <em>postnumb</em>?</p>
<ul>
<li>What statistic did you use to justify your conclusion?</li>
<li>Interpret the model fit.</li>
</ul>
<p><em>Hints:</em></p>
<ul>
<li>The <code>lm()</code> function (short for linear model) estimates linear regression models.</li>
<li>The <code>summary()</code> function provides relevant summary statistics for the model.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="in-class-exercises.html#cb72-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">lm</span>(postnumb <span class="sc">~</span> age <span class="sc">+</span> prenumb, <span class="at">data =</span> sesam)</span>
<span id="cb72-2"><a href="in-class-exercises.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = postnumb ~ age + prenumb, data = sesam)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.130  -6.456  -0.456   5.435  22.568 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.4242     5.1854   1.432    0.154    
## age           0.1225     0.1084   1.131    0.259    
## prenumb       0.7809     0.0637  12.259   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.486 on 237 degrees of freedom
## Multiple R-squared:  0.4592, Adjusted R-squared:  0.4547 
## F-statistic: 100.6 on 2 and 237 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>Yes, <em>age</em> and <em>prenumb</em> explain a significant amount of variability in <em>postnumb</em>
(<span class="math inline">\(R^2 = 0.459\)</span>, <span class="math inline">\(F[2, 237] = 100.629\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
<li>We use the F statistic for the overall test of model fit to support this conclusion.</li>
<li>The variables <em>age</em> and <em>prenumb</em> together explain 45.9% of the
variability in <em>postnumb</em>.</li>
</ul>
</details>
<hr />
</div>
<div id="section-8" class="section level4" number="1.5.2.3">
<h4><span class="header-section-number">1.5.2.3</span> </h4>
<p>Write the null and alternative hypotheses for tested in <a href="in-class-exercises.html#reg1">1.5.2.2</a>.</p>
<details>
<summary>
Click for explanation
</summary>
<p>Since we are testing for explained variance, our hypotheses concern the <span class="math inline">\(R^2\)</span>.</p>
<p><span class="math display">\[
\begin{align*}
H_0: R^2 = 0\\
H_1: R^2 &gt; 0
\end{align*}
\]</span></p>
<p>Note that this is a directional hypotheses because the <span class="math inline">\(R^2\)</span> cannot be negative.</p>
</details>
<hr />
</div>
<div id="section-9" class="section level4" number="1.5.2.4">
<h4><span class="header-section-number">1.5.2.4</span> </h4>
<p>Consider the path model below.</p>
<ul>
<li>How many regression coefficients are estimated in this model?</li>
<li>How many variances are estimated?</li>
<li>How many covariances are estimated?</li>
<li>How many degrees of freedom does this model have?</li>
</ul>
<p><em>Hint:</em> As you learned in <a href="pdf/tcsm_week_1.pdf">Lecture 1</a>, <span class="math inline">\(df = N_{obs} – N_{par}\)</span>.</p>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<hr />
</div>
<div id="section-10" class="section level4" number="1.5.2.5">
<h4><span class="header-section-number">1.5.2.5</span> </h4>
<p>Consider a multiple regression analysis with three continuous independent
variables: scores on tests of language, history, and logic, and one continuous
dependent variable: score on a math test. We want to know if scores on the language, history, and logic tests can predict the math test score.</p>
<ul>
<li>Sketch a path model that you could use to answer this question</li>
<li>How many regression parameters are there?</li>
<li>How many variances could you estimate?</li>
<li>How many covariances could you estimate?</li>
<li>How many degrees of freedom does this model have?</li>
</ul>
<hr />
</div>
</div>
<div id="part-3-anova" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Part 3: ANOVA<a href="in-class-exercises.html#part-3-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<div id="section-11" class="section level4" number="1.5.3.1">
<h4><span class="header-section-number">1.5.3.1</span> </h4>
<p>Load the <code>Drivers.sav</code> data.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="in-class-exercises.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data into a data frame named &#39;drivers&#39;:</span></span>
<span id="cb74-2"><a href="in-class-exercises.html#cb74-2" aria-hidden="true" tabindex="-1"></a>drivers <span class="ot">&lt;-</span> <span class="fu">read.spss</span>(<span class="st">&quot;Drivers.sav&quot;</span>, <span class="at">to.data.frame =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<hr />
<p>In this section, we will use ANOVA to evaluate the following research question:</p>
<ul>
<li>Does talking on the phone interfere with people’s driving skills?</li>
</ul>
<p>These data come from an experiment. The <em>condition</em> variable represents the
three experimental conditions:</p>
<ul>
<li>Hand-held phone</li>
<li>Hands-free phone</li>
<li>Control (no phone)</li>
</ul>
<p>We will use <em>condition</em> as the IV in our ANOVA models. The DV, <em>RT</em>, represents
the participant’s reaction time (in milliseconds) during a driving simulation.</p>
<hr />
<div id="anova-vs.-linear-regression" class="section level5 unnumbered hasAnchor">
<h5>ANOVA vs. Linear Regression<a href="in-class-exercises.html#anova-vs.-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>As you may know, the mathematical model underlying ANOVA is just a linear
regression model with nominal IVs. So, in terms of the underlying statistical
models, there is no difference between ANOVA and regression; the differences lie
in the focus of the analysis.</p>
<ul>
<li>ANOVA is really a type of statistical test wherein we are testing hypotheses
about the effects of some set of nominal grouping factors on some continuous
outcome.
<ul>
<li>When doing an ANOVA, we usually don’t interact directly with the parameter
estimates from the underlying model.</li>
</ul></li>
<li>Regression is a type of statistical model (i.e., a way to represent a
univariate distribution with a conditional mean and fixed variance).
<ul>
<li>When we do a regression analysis, we primarily focus on the estimated
parameters of the underling linear model.</li>
</ul></li>
</ul>
<p>When doing ANOVA in R, we estimate the model exactly as we would for linear
regression; we simply summarize the results differently.</p>
<hr />
</div>
</div>
<div id="anova1" class="section level4" number="1.5.3.2">
<h4><span class="header-section-number">1.5.3.2</span> </h4>
<p>Perform the ANOVA to test the above research question.</p>
<p><em>Hint:</em> After estimating the model with <code>lm()</code>, you can use the <code>anova()</code>
function to compute the sums-of-squares and significance tests for each factor
in your model.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="in-class-exercises.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the underlying model:</span></span>
<span id="cb75-2"><a href="in-class-exercises.html#cb75-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">lm</span>(RT <span class="sc">~</span> condition, <span class="at">data =</span> drivers)</span>
<span id="cb75-3"><a href="in-class-exercises.html#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="in-class-exercises.html#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Summarize the model as a regression analysis:</span></span>
<span id="cb75-5"><a href="in-class-exercises.html#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = RT ~ condition, data = drivers)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -317.50  -71.25    2.98   89.55  243.45 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           654.50      29.08  22.506   &lt;2e-16 ***
## conditionhands-free   -36.95      41.13  -0.898   0.3727    
## conditioncontrol     -100.75      41.13  -2.450   0.0174 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 130.1 on 57 degrees of freedom
## Multiple R-squared:  0.09729,    Adjusted R-squared:  0.06562 
## F-statistic: 3.072 on 2 and 57 DF,  p-value: 0.05408</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="in-class-exercises.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Summarize the model as an ANOVA:</span></span>
<span id="cb77-2"><a href="in-class-exercises.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"103908.7","3":"51954.35","4":"3.071729","5":"0.05408477","_rn_":"condition"},{"1":"57","2":"964081.7","3":"16913.71","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</details>
<hr />
<p>Of course the results of any analysis are only valid if the assumptions of the
analysis/model are satisfied. In particular, we should probably check at least
three conditions:</p>
<ol style="list-style-type: decimal">
<li>There are no overly influential cases</li>
<li>The residual variance is homogonous across groups</li>
<li>The residuals are normally distributed</li>
</ol>
<hr />
</div>
<div id="section-12" class="section level4" number="1.5.3.3">
<h4><span class="header-section-number">1.5.3.3</span> </h4>
<p>Check for influential cases.</p>
<p><em>Hint:</em> You can use the <code>cooks.distance()</code> function to compute Cook’s Distance
statistic for each observation.</p>
<ul>
<li>Observations with Cook’s D values substantially larger than, and qualitatively
distinct from, the rest of the data may be overly influential.</li>
<li>You can evaluate the relative sizes of the distances by making an index plot
of the estimated distance statistics.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="in-class-exercises.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Compute the Cook&#39;s distances:</span></span>
<span id="cb78-2"><a href="in-class-exercises.html#cb78-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(results)</span>
<span id="cb78-3"><a href="in-class-exercises.html#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="in-class-exercises.html#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Plot the distances:</span></span>
<span id="cb78-5"><a href="in-class-exercises.html#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(d)</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>In the figure above, we’re looking for any distances that clearly “stand out
from the crowd”.</p>
<ul>
<li>None of the distances in the above figure look notable.</li>
<li>We do not see evidence of influential observations.</li>
</ul>
</details>
<hr />
</div>
<div id="section-13" class="section level4" number="1.5.3.4">
<h4><span class="header-section-number">1.5.3.4</span> </h4>
<p>Check the normality of the residuals.</p>
<p><em>Hints:</em></p>
<ul>
<li>One of the best ways to check the normality of residuals is with a Normal QQplot.</li>
<li>We can easily create a Normal QQ-Plot of the residuals by plotting the <code>results</code> object from <a href="in-class-exercises.html#anova1">1.5.3.2</a>.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="in-class-exercises.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(results, <span class="dv">2</span>)</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>In the QQ-Plot created above, we want to see all of the points follow the
diagonal, dashed line.</p>
<ul>
<li>Perfectly normal residuals will fall exactly along this line</li>
<li>Deviations away from the line indicate devations from normality.</li>
</ul>
<p>The residuals in this figure look quite good.</p>
<ul>
<li>We only see very minor deviations from the idealized line.</li>
<li>The residuals appear to be more-or-less normally distributed.</li>
</ul>
</details>
<hr />
</div>
<div id="section-14" class="section level4" number="1.5.3.5">
<h4><span class="header-section-number">1.5.3.5</span> </h4>
<p>Check the homogeneity of the residual variances.</p>
<p><em>Hints:</em></p>
<ul>
<li>A <em>scale-location plot</em> is one of the best ways to check the homogeneity
of variances assumption.</li>
<li>Plot an estimate of the residual variance against the predicted values
<ul>
<li>Any trend indicates differences in residual variance between groups</li>
</ul></li>
<li>Plotting the <code>results</code> object from <a href="in-class-exercises.html#anova1">1.5.3.2</a> will also produce a
scale-location plot.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="in-class-exercises.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(results, <span class="dv">3</span>)</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>The red line in this figure is a <em>loess line</em> which represents the trend of the
plotted data.</p>
<ul>
<li>If this loess line is flat, there is no evidence of differences in the residual variances between groups.</li>
<li>Trends in this line indicate violations of the homogeneity assumption.</li>
</ul>
<p>In this case, the line is pretty much flat and we have little-to-no evidence of
heterogeneous residual variances.</p>
</details>
<hr />
</div>
<div id="section-15" class="section level4" number="1.5.3.6">
<h4><span class="header-section-number">1.5.3.6</span> </h4>
<p>Summarize your conclusions regarding the assumption.</p>
<ul>
<li>Are the assumptions satisfied?</li>
<li>Can we trust the model results?</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<p>There are no observations that stand out as particularly influential.
Furthermore, we have no evidence of heterogeneous residual variances or
substantial violations of normality for the residuals. Hence, the assumptions
appear to be satisfied, and we can trust the conclusions of our analysis.</p>
</details>
<hr />
</div>
<div id="section-16" class="section level4" number="1.5.3.7">
<h4><span class="header-section-number">1.5.3.7</span> </h4>
<p>Use your results to answer the research question.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="in-class-exercises.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"103908.7","3":"51954.35","4":"3.071729","5":"0.05408477","_rn_":"condition"},{"1":"57","2":"964081.7","3":"16913.71","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The effect of <em>condition</em> on <em>RT</em> was nonsignificant (<span class="math inline">\(F[2, 57] = 3.07\)</span>, <span class="math inline">\(p = 0.054\)</span>). Therefore, based on these results, we do not have evidence
for an effect of mobile phone usage on driving performance.</p>
</details>
<hr />
</div>
</div>
<div id="part-4-ancova" class="section level3 hasAnchor" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Part 4: ANCOVA<a href="in-class-exercises.html#part-4-ancova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>We will now conduct an ANCOVA to assess the following research question.</p>
<ul>
<li>Are there differences in reaction times between the phone conditions after
controlling for age?</li>
</ul>
<p>As with ANOVA, the statistical model underlying an ANCOVA is simply a linear
regression model. The model for an ANCOVA, however, includes at least one
continuous covariate in addition to the categorical IVs.</p>
<p>Consequently, when we conduct ANCOVA in R, we again use the <code>lm()</code> function to
estimate the model.</p>
<hr />
<div id="ancova1" class="section level4" number="1.5.4.1">
<h4><span class="header-section-number">1.5.4.1</span> </h4>
<p>Estimate the ANCOVA model needed to test the above research question.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="in-class-exercises.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the model:</span></span>
<span id="cb82-2"><a href="in-class-exercises.html#cb82-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">lm</span>(RT <span class="sc">~</span> condition <span class="sc">+</span> age, <span class="at">data =</span> drivers)</span>
<span id="cb82-3"><a href="in-class-exercises.html#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="in-class-exercises.html#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Conduct the statistical tests:</span></span>
<span id="cb82-5"><a href="in-class-exercises.html#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"103908.7","3":"51954.35","4":"4.520385","5":"1.513790e-02","_rn_":"condition"},{"1":"1","2":"320454.4","3":"320454.37","4":"27.881732","5":"2.176237e-06","_rn_":"age"},{"1":"56","2":"643627.3","3":"11493.35","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</details>
<hr />
<div id="ancova-and-interactions" class="section level5 unnumbered hasAnchor">
<h5>ANCOVA and Interactions<a href="in-class-exercises.html#ancova-and-interactions" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>As you can see above, when we run an ANCOVA, we’re just estimating a multiple
linear regression model. We call the analysis ANCOVA because we are interested
in a specific hypothesis.</p>
<ul>
<li>Our substantive interest lies in the categorical IVs.</li>
<li>The continuous covariates are uninteresting, nuisance variables that we are
controlling for to get better estimates of the interesting treatment effects.</li>
</ul>
<p>One implication of this hypothesis is the absence of any interaction between the
covariates and grouping factors.</p>
<ul>
<li>If the covariate moderates the treatment effect, the covariate has a direct impact on the substantively interesting group differences. Such a covariate is not a covariate; it’s a substantively integral feature of the model.</li>
</ul>
<p>If we want to report our analysis as an ANCOVA, we need to show that the covariate effects are equivalent in each group. In other words, there is no interaction between the grouping factors and the covariates.</p>
<hr />
</div>
</div>
<div id="ancova2" class="section level4" number="1.5.4.2">
<h4><span class="header-section-number">1.5.4.2</span> </h4>
<p>Test for an interaction between <em>age</em> and <em>condition</em> in the model from
<a href="in-class-exercises.html#ancova1">1.5.4.1</a>.</p>
<ul>
<li>What is your conclusion?</li>
<li>Can we report our analysis as an ANCOVA?</li>
</ul>
<p><em>Hint:</em> You can include an interaction term in an R formulas ‘multiplying’ the two variable names using the <code>*</code> operator.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="in-class-exercises.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add the interaction between &#39;age&#39; and &#39;condition&#39; to the model:</span></span>
<span id="cb83-2"><a href="in-class-exercises.html#cb83-2" aria-hidden="true" tabindex="-1"></a>results_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(RT <span class="sc">~</span> condition <span class="sc">*</span> age, <span class="at">data =</span> drivers)</span>
<span id="cb83-3"><a href="in-class-exercises.html#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="in-class-exercises.html#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Conduct the hypothesis tests.</span></span>
<span id="cb83-5"><a href="in-class-exercises.html#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results_int)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"103908.70","3":"51954.35","4":"4.532329","5":"1.514985e-02","_rn_":"condition"},{"1":"1","2":"320454.37","3":"320454.37","4":"27.955398","5":"2.298385e-06","_rn_":"age"},{"1":"2","2":"24622.15","3":"12311.08","4":"1.073978","5":"3.488307e-01","_rn_":"condition:age"},{"1":"54","2":"619005.18","3":"11463.06","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The interaction between <em>condition</em> and <em>age</em> is not significant
(<span class="math inline">\(F[2, 54] = 1.07\)</span>, <span class="math inline">\(p = 0.349\)</span>). Therefore, the covariate effects should be more-or-less equivalent in each group, and we can report our analysis
as an ANCOVA.</p>
</details>
<hr />
</div>
<div id="section-17" class="section level4" number="1.5.4.3">
<h4><span class="header-section-number">1.5.4.3</span> </h4>
<p>Answer the research from above question.</p>
<ul>
<li>If you did find a significant, partial effect of condition, do a post hoc
comparison of pairwise mean differences to see which groups showed significantly
different reaction times, after controlling for age.</li>
<li>Use Tukey’s HSD correction for all pairwise comparisons to control the Type I error rate.</li>
</ul>
<p><em>Hints:</em></p>
<ul>
<li>You can conduct the appropriate post hoc test with the <code>TukeyHSD()</code> function.</li>
<li>The <code>TukeyHSD()</code> function only works on models estimated using the <code>aov()</code>
function (which is the same as <code>lm()</code> but summarizes the results in ANOVA
style).</li>
<li>To satisfy <code>TukeyHSD()</code>, you can either rerun your model with <code>aov()</code> or
convert your <code>results</code> object to the correct format via <code>aov(results)</code>.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="in-class-exercises.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Check the hypothesis tests for the ANCOVA from above:</span></span>
<span id="cb84-2"><a href="in-class-exercises.html#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"103908.7","3":"51954.35","4":"4.520385","5":"1.513790e-02","_rn_":"condition"},{"1":"1","2":"320454.4","3":"320454.37","4":"27.881732","5":"2.176237e-06","_rn_":"age"},{"1":"56","2":"643627.3","3":"11493.35","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="in-class-exercises.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Run the post hoc comparisons:</span></span>
<span id="cb85-2"><a href="in-class-exercises.html#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(results))</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = results)
## 
## $condition
##                         diff       lwr       upr     p adj
## hands-free-hand-held  -36.95 -118.5708  44.67082 0.5242511
## control-hand-held    -100.75 -182.3708 -19.12918 0.0119407
## control-hands-free    -63.80 -145.4208  17.82082 0.1533777</code></pre>
<p>After controlling for age, phone usage significantly affects driving performance
(<span class="math inline">\(F[2, 56] = 4.52\)</span>, <span class="math inline">\(p = 0.015\)</span>). Specifically, the hand-held
condition has a significant <strong>higher</strong> reaction time than the control condition.</p>
<hr />
</div>
</div>
<div id="part-5-back-to-regression" class="section level3 hasAnchor" number="1.5.5">
<h3><span class="header-section-number">1.5.5</span> Part 5: Back to Regression<a href="in-class-exercises.html#part-5-back-to-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>As we saw above, we can use ANOVA or ANCOVA to test hypotheses about differences
between groups in some continuous outcome. AN(C)OVA is a type of statistical
test, though, not a type of model. The statistical model underlying an AN(C)OVA
is just a linear regression model. Since this class is about statistical
modeling, it won’t do us much good to keep thinking in terms of statistical
tests; we’re better off approaching these problems from a modeling perspective.</p>
<p>We can just as easily make the inferences from above by working directly within
a regression modeling framework. In this section, we will explore linear
regression models with categorical predictors.</p>
<hr />
<div id="section-18" class="section level4" number="1.5.5.1">
<h4><span class="header-section-number">1.5.5.1</span> </h4>
<p>Load the <code>Sesam2.sav</code> data.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="in-class-exercises.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data into an object called &#39;sesam2&#39;:</span></span>
<span id="cb87-2"><a href="in-class-exercises.html#cb87-2" aria-hidden="true" tabindex="-1"></a>sesam2 <span class="ot">&lt;-</span> <span class="fu">read.spss</span>(<span class="st">&quot;Sesam2.sav&quot;</span>, <span class="at">to.data.frame =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="section-19" class="section level4" number="1.5.5.2">
<h4><span class="header-section-number">1.5.5.2</span> </h4>
<p><em>VIEWCAT</em> is a nominal grouping variable, but it is represented as a numeric
variable in the <code>sesam2</code> data.</p>
<ul>
<li>Convert <em>VIEWCAT</em> into a factor.</li>
<li>Make sure that <code>VIEWCAT = 1</code> is the reference group.</li>
</ul>
<p><em>Hints:</em></p>
<ul>
<li>You can identify the reference group with the <code>levels()</code> or <code>contrasts()</code> functions.</li>
<li>The reference group is the group labelled with the first level printed by
<code>levels()</code>.</li>
<li>When you run <code>contrasts()</code>, you will see a pattern matrix that defines a
certain dummy coding scheme. The reference group is the group that has zeros in
each column of this matrix.</li>
<li>If you need to change the reference group, you can use the <code>relevel()</code> function.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="in-class-exercises.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert &#39;VIEWCAT&#39; to a factor:</span></span>
<span id="cb88-2"><a href="in-class-exercises.html#cb88-2" aria-hidden="true" tabindex="-1"></a>sesam2<span class="sc">$</span>VIEWCAT <span class="ot">&lt;-</span> <span class="fu">factor</span>(sesam2<span class="sc">$</span>VIEWCAT)</span>
<span id="cb88-3"><a href="in-class-exercises.html#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="in-class-exercises.html#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Check the reference group:</span></span>
<span id="cb88-5"><a href="in-class-exercises.html#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(sesam2<span class="sc">$</span>VIEWCAT)</span></code></pre></div>
<pre><code>## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot;</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="in-class-exercises.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(sesam2<span class="sc">$</span>VIEWCAT)</span></code></pre></div>
<pre><code>##   2 3 4
## 1 0 0 0
## 2 1 0 0
## 3 0 1 0
## 4 0 0 1</code></pre>
</details>
<hr />
</div>
<div id="reg2" class="section level4" number="1.5.5.3">
<h4><span class="header-section-number">1.5.5.3</span> </h4>
<p>Estimate a multiple regression model wherein <em>VIEWCAT</em> predicts <em>POSTNUMB</em>.</p>
<ul>
<li>Summarize the model.</li>
<li>Interpret the estimates.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="in-class-exercises.html#cb92-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">lm</span>(POSTNUMB <span class="sc">~</span> VIEWCAT, <span class="at">data =</span> sesam2)</span>
<span id="cb92-2"><a href="in-class-exercises.html#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = POSTNUMB ~ VIEWCAT, data = sesam2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.474  -7.942   0.240   8.526  25.240 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   18.760      2.316   8.102 8.95e-14 ***
## VIEWCAT2       9.331      2.900   3.218  0.00154 ** 
## VIEWCAT3      14.714      2.777   5.298 3.49e-07 ***
## VIEWCAT4      18.032      2.809   6.419 1.24e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.58 on 175 degrees of freedom
## Multiple R-squared:  0.2102, Adjusted R-squared:  0.1967 
## F-statistic: 15.53 on 3 and 175 DF,  p-value: 5.337e-09</code></pre>
</details>
<hr />
</div>
<div id="section-20" class="section level4" number="1.5.5.4">
<h4><span class="header-section-number">1.5.5.4</span> </h4>
<p>Use <code>ggplot()</code> to make a scatterplot with <em>AGE</em> on the x-axis and <em>POSTNUMB</em> on
the y-axis.</p>
<ul>
<li>Color the points according to the their <em>VIEWCAT</em> level.</li>
<li>Save the plot object to a variable in your environment.</li>
</ul>
<p><em>Hint:</em> You can map color to the levels of a variable on your dataset by
assigning the variable names to the <code>color</code> argument of the <code>aes()</code> function in
<code>ggplot()</code>.</p>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="in-class-exercises.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb94-2"><a href="in-class-exercises.html#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="in-class-exercises.html#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Add aes(..., color = VIEWCAT) to get different colors for each group:</span></span>
<span id="cb94-4"><a href="in-class-exercises.html#cb94-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sesam2, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">y =</span> POSTNUMB, <span class="at">color =</span> VIEWCAT)) <span class="sc">+</span> </span>
<span id="cb94-5"><a href="in-class-exercises.html#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="co"># Add points for scatterplot</span></span>
<span id="cb94-6"><a href="in-class-exercises.html#cb94-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-7"><a href="in-class-exercises.html#cb94-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Print the plot stored as &#39;p&#39;:</span></span>
<span id="cb94-8"><a href="in-class-exercises.html#cb94-8" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>We assigned the global color aesthetic to the <em>VIEWCAT</em> variable, so the points
are colored based on their group.</p>
</details>
<hr />
</div>
<div id="section-21" class="section level4" number="1.5.5.5">
<h4><span class="header-section-number">1.5.5.5</span> </h4>
<p>Add linear regression lines for each group to the above scatterplot.</p>
<p><em>Hints:</em></p>
<ul>
<li>You can add regression lines with <code>ggplot2::geom_smooth()</code>
<ul>
<li>To get linear regression lines, set the argument <code>method = "lm"</code></li>
<li>To omit error envelopes, set the argument <code>se = FALSE</code></li>
</ul></li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="in-class-exercises.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add OLS best-fit lines:</span></span>
<span id="cb95-2"><a href="in-class-exercises.html#cb95-2" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="duddly_bumble_pocket_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p>The global color aesthetic assignment from above carries through to any
additional plot elements that we add, including the regression lines. So, we
also get a separate regression line for each <em>VIEWCAT</em> group.</p>
</details>
<hr />
</div>
<div id="section-22" class="section level4" number="1.5.5.6">
<h4><span class="header-section-number">1.5.5.6</span> </h4>
<p>How would you interpret the pattern of regression lines above?</p>
<details>
<summary>
Click for explanation
</summary>
<p>All the lines show a positive slope, so post-test number recognition appears to
increase along with increasing age. The lines are not parallel, though. So,
<em>VIEWCAT</em> may be moderating the effect of <em>AGE</em> on <em>POSTNUMB</em>.</p>
</details>
<hr />
<div id="moderated-regression" class="section level5 unnumbered hasAnchor">
<h5>Moderated Regression<a href="in-class-exercises.html#moderated-regression" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Based on the figure we just created, we may want to test for moderation in our
regression model. To do so, we need to add an interaction between <em>AGE</em> and
<em>VIEWCAT</em>. The <em>VIEWCAT</em> factor is represented by
3 in our model, though. So, when we
interact <em>AGE</em> and <em>VIEWCAT</em>, we will create 3 interaction terms.</p>
<p>To test the overall moderating influence of <em>VIEWCAT</em>, we need to conduct a
multiparameter hypothesis test of all 3 interaction terms. One way that
we can go about implementing such a test is through a hierarchical regression
analysis entailing three steps:</p>
<ol style="list-style-type: decimal">
<li>Estimate the additive model wherein we regress <em>POSTNUMB</em> onto <em>AGE</em> and
<em>VIEWCAT</em> without any interaction.</li>
<li>Estimate the moderated model by adding the interaction between <em>AGE</em> and
<em>VIEWCAT</em> into the additive model.</li>
<li>Conduct a <span class="math inline">\(\Delta R^2\)</span> test to compare the fit of the two models.</li>
</ol>
<hr />
</div>
</div>
<div id="hReg" class="section level4" number="1.5.5.7">
<h4><span class="header-section-number">1.5.5.7</span> </h4>
<p>Conduct the hierarchical regression analysis described above.</p>
<ul>
<li>Does <em>VIEWCAT</em> significantly moderate the effect of <em>AGE</em> on <em>POSTNUMB</em>?</li>
<li>Provide statistical justification for your conclusion.</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="in-class-exercises.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the additive model a view the results:</span></span>
<span id="cb96-2"><a href="in-class-exercises.html#cb96-2" aria-hidden="true" tabindex="-1"></a>results_add <span class="ot">&lt;-</span> <span class="fu">lm</span>(POSTNUMB <span class="sc">~</span> VIEWCAT <span class="sc">+</span> AGE, <span class="at">data =</span> sesam2)</span>
<span id="cb96-3"><a href="in-class-exercises.html#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results_add)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = POSTNUMB ~ VIEWCAT + AGE, data = sesam2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -23.680  -8.003  -0.070   8.464  22.635 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -10.1056     6.5091  -1.553  0.12235    
## VIEWCAT2      9.1453     2.7390   3.339  0.00103 ** 
## VIEWCAT3     13.8602     2.6294   5.271 3.98e-07 ***
## VIEWCAT4     16.9215     2.6636   6.353 1.79e-09 ***
## AGE           0.5750     0.1221   4.708 5.08e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.94 on 174 degrees of freedom
## Multiple R-squared:  0.2995, Adjusted R-squared:  0.2834 
## F-statistic:  18.6 on 4 and 174 DF,  p-value: 9.642e-13</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="in-class-exercises.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimate the moderated model and view the results:</span></span>
<span id="cb98-2"><a href="in-class-exercises.html#cb98-2" aria-hidden="true" tabindex="-1"></a>results_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(POSTNUMB <span class="sc">~</span> VIEWCAT <span class="sc">*</span> AGE, <span class="at">data =</span> sesam2)</span>
<span id="cb98-3"><a href="in-class-exercises.html#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = POSTNUMB ~ VIEWCAT * AGE, data = sesam2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -23.8371  -8.2387   0.6158   8.7988  22.5611 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  -18.7211    15.5883  -1.201   0.2314  
## VIEWCAT2       9.9741    20.6227   0.484   0.6293  
## VIEWCAT3      23.5825    19.3591   1.218   0.2248  
## VIEWCAT4      34.3969    19.3600   1.777   0.0774 .
## AGE            0.7466     0.3074   2.429   0.0162 *
## VIEWCAT2:AGE  -0.0175     0.4060  -0.043   0.9657  
## VIEWCAT3:AGE  -0.1930     0.3782  -0.510   0.6104  
## VIEWCAT4:AGE  -0.3416     0.3770  -0.906   0.3663  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.99 on 171 degrees of freedom
## Multiple R-squared:  0.3046, Adjusted R-squared:  0.2762 
## F-statistic:  10.7 on 7 and 171 DF,  p-value: 3.79e-11</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="in-class-exercises.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test for moderation:</span></span>
<span id="cb100-2"><a href="in-class-exercises.html#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results_add, results_mod)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Res.Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"174","2":"20806.26","3":"NA","4":"NA","5":"NA","6":"NA","_rn_":"1"},{"1":"171","2":"20653.50","3":"3","4":"152.7625","5":"0.4215975","6":"0.7377438","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><em>VIEWCAT</em> does not significantly moderate the effect of <em>AGE</em> on <em>POSTNUMB</em>
(<span class="math inline">\(F[3, 171] = 0.422\)</span>, <span class="math inline">\(p = 0.738\)</span>).</p>
</details>
<hr />
<!------------------------------------------------------------------------------
####

Sketch path diagrams for the additive and moderated models you estimated in
\@ref(hReg) (on paper).



<details>
<summary>Click for explanation</summary>

**Additive Model**

![](images/3_g1.png)

**Moderated Model**

![](images/3_g2.png)

</details>

---
------------------------------------------------------------------------------->
</div>
<div id="section-23" class="section level4" number="1.5.5.8">
<h4><span class="header-section-number">1.5.5.8</span> </h4>
<p>Write the regression equations for the additive and moderated models from
<a href="in-class-exercises.html#hReg">1.5.5.7</a>.</p>
<details>
<summary>
Click for explanation
</summary>
<p><strong>Additive Model</strong></p>
<p><span class="math display">\[
\begin{align*}
Y_{postnumb} = \beta_0 + \beta_1 X_{view2} + \beta_2 X_{view3} + \beta_3 X_{view4} + \beta_4 X_{age} + \varepsilon
\end{align*}
\]</span></p>
<p><strong>Moderated Model</strong></p>
<p><span class="math display">\[
\begin{align*}
Y_{postnumb} = \beta_0 + &amp;\beta_1 X_{view2} + \beta_2 X_{view3} + \beta_3 X_{view4} + \beta_4 X_{age} +\\
&amp;\beta_5 X_{view2} X_{age} + \beta_6 X_{view3} X_{age} + \beta_7 X_{view4} X_{age} + \varepsilon
\end{align*}
\]</span></p>
</details>
<hr />
</div>
<div id="section-24" class="section level4" number="1.5.5.9">
<h4><span class="header-section-number">1.5.5.9</span> </h4>
<p>Write the null and alternative hypotheses for the test of moderation you
conducted in <a href="in-class-exercises.html#hReg">1.5.5.7</a>.</p>
<details>
<summary>
Click for explanation
</summary>
<p><span class="math display">\[
\begin{align*}
H_0: \Delta R^2 = 0\\
H_1: \Delta R^2 &gt; 0
\end{align*}
\]</span></p>
</details>
<hr />
</div>
<div id="section-25" class="section level4" number="1.5.5.10">
<h4><span class="header-section-number">1.5.5.10</span> </h4>
<p>Write the regression equation for each of the four <em>VIEWCAT</em> groups.</p>
<details>
<summary>
Click for explanation
</summary>
<p><strong><em>VIEWCAT</em> 1:</strong></p>
<p><span class="math display">\[
Y_{postnumb} = \beta_0 + \beta_4 X_{age} + \varepsilon
\]</span></p>
<p><strong><em>VIEWCAT</em> 2:</strong></p>
<p><span class="math display">\[
Y_{postnumb} = \beta_0 + \beta_1 X_{view2} + \beta_4 X_{age} + \beta_5 X_{view2} X_{age} + \varepsilon
\]</span></p>
<p><strong><em>VIEWCAT</em> 3:</strong></p>
<p><span class="math display">\[
Y_{postnumb} = \beta_0 + \beta_2 X_{view3} + \beta_4 X_{age} + \beta_6 X_{view3} X_{age} + \varepsilon
\]</span></p>
<p><strong><em>VIEWCAT</em> 4:</strong></p>
<p><span class="math display">\[
Y_{postnumb} = \beta_0 + \beta_3 X_{view4} + \beta_4 X_{age} + \beta_7 X_{view4} X_{age} + \varepsilon
\]</span></p>
</details>
<hr />
</div>
<div id="section-26" class="section level4" number="1.5.5.11">
<h4><span class="header-section-number">1.5.5.11</span> </h4>
<p>Run the <code>anova()</code> function on only the moderated regression model from <a href="in-class-exercises.html#hReg">1.5.5.7</a>.</p>
<ul>
<li>Compare the result to the <code>anova()</code> output from <a href="in-class-exercises.html#hReg">1.5.5.7</a>.</li>
<li>What do you notice when comparing the two <code>anova()</code> outputs?</li>
<li>Does this comparison offer any insight into the relation between regression
and AN(C)OVA?</li>
</ul>
<details>
<summary>
Click for explanation
</summary>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="in-class-exercises.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results_mod)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"3","2":"6243.7812","3":"2081.26039","4":"17.2317276","5":"8.001597e-10","_rn_":"VIEWCAT"},{"1":"1","2":"2650.8590","3":"2650.85900","4":"21.9477008","5":"5.690653e-06","_rn_":"AGE"},{"1":"3","2":"152.7625","3":"50.92085","4":"0.4215975","5":"7.377438e-01","_rn_":"VIEWCAT:AGE"},{"1":"171","2":"20653.5023","3":"120.78072","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="in-class-exercises.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(results_add, results_mod)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Res.Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"174","2":"20806.26","3":"NA","4":"NA","5":"NA","6":"NA","_rn_":"1"},{"1":"171","2":"20653.50","3":"3","4":"152.7625","5":"0.4215975","6":"0.7377438","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>When we run the <code>anova()</code> function on only the moderated regression model, we
get ANCOVA-style tests like those we used in <a href="in-class-exercises.html#ancova2">1.5.4.2</a>. The marginal test
for the interaction between <em>AGE</em> and <em>VIEWCAT</em> in this ANCOVA-style result is identical to the model comparison test from <a href="in-class-exercises.html#hReg">1.5.5.7</a>.</p>
<p>This comparison shows that the significance tests for marginal effects in an
AN(C)OVA model can be equivalent to certain model comparison tests in a
regression model.</p>
<ul>
<li>Indeed, although you cannot know this from only the examples explored here,
any significance test in an AN(C)OVA can be reformulated as a comparison
between two appropriately nested linear regression models.</li>
</ul>
</details>
<hr />
<p>End of In-Class Exercises 1</p>
<hr />

</div>
</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["duddly_bumble_pocket.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"search": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
